import {bookProfiles,type BookProfile} from './books-data';

export const nineteenEightyFour:BookProfile={
  id:'nineteen-eighty-four',
  title:'Nineteen Eighty-Four',
  author:'George Orwell',
  year:'1949',
  form:'Dystopian political fiction novel',
  language:'English',
  level:'SL studied work',
  context:'Written shortly after World War II during the early Cold War. The profile links the novel to Orwell’s opposition to totalitarianism in both fascist and Stalinist forms, his wartime propaganda experience at the BBC, and his observation of authoritarian politics during the Spanish Civil War. These contexts support analysis of surveillance, propaganda, historical revision, and the manipulation of truth.',
  overview:'Winston Smith is a low-ranking Party member in Oceania who works at the Ministry of Truth rewriting historical records to match the Party’s changing claims. Secretly disillusioned, he begins an illegal diary and enters a forbidden relationship with Julia. Winston believes Inner Party member O’Brien may connect him to the underground Brotherhood, but O’Brien is actually a loyal Party agent. Winston and Julia are arrested, and Winston is tortured and psychologically broken at the Ministry of Love until he abandons his inner rebellion, betrays Julia, and accepts Big Brother.',
  characters:[
    {name:'Winston Smith',role:'Protagonist; 39, employed at the Ministry of Truth; intellectually curious and quietly disillusioned.',development:'Moves from private rebellion through the diary and affair, to hope in imagined organized resistance, and finally to complete psychological defeat.',themes:'Individuality vs. control, truth, rebellion, memory, psychological power.',methods:'Close third-person narration follows his thoughts, doubts, hopes, fears, and self-deceptions in detail.'},
    {name:'Julia',role:'Winston’s lover; younger, practical, and resistant through personal and sexual freedom more than abstract ideology.',development:'Maintains a pragmatic form of rebellion before she is also broken by torture.',themes:'The body, private life, intimacy, resistance, betrayal.',methods:'Characterized through contrast with Winston: action-oriented and unsentimental where he is reflective and ideological.'},
    {name:'O’Brien',role:'Inner Party member Winston imagines as an ally, later revealed as his interrogator and torturer.',development:'His apparent warmth is retrospectively reinterpreted as part of a long surveillance and manipulation operation.',themes:'Betrayal, psychological control, power, manufactured truth.',methods:'Calm, intimate, intellectually controlled cruelty makes his violence more disturbing than simple brutality.'},
    {name:'Big Brother',role:'The Party’s symbolic figurehead, never directly encountered or confirmed as an individual person.',development:'Functions as a static, manufactured presence rather than a developing character.',themes:'Propaganda, personality cult, surveillance, manufactured loyalty.',methods:'Characterized through absence: posters, slogans, reported speech, and constant symbolic presence rather than direct appearance.'},
    {name:'Mr. Charrington',role:'Shopkeeper who rents Winston and Julia their secret room, later revealed as a Thought Police agent.',development:'His reveal transforms earlier apparently safe scenes into evidence that Winston and Julia were watched all along.',themes:'Surveillance, betrayal, privacy, nostalgia.',methods:'Initially characterized as warm and nostalgic, then abruptly recontextualized as an instrument of the Party.'},
    {name:'Syme',role:'Winston’s intelligent colleague working on the Newspeak dictionary.',development:'Disappears after Winston predicts that his perceptiveness makes him dangerous to the Party.',themes:'Language, thought control, intelligence, disappearance.',methods:'Used structurally as an early warning that even loyal competence and intellectual clarity can become liabilities.'}
  ],
  themes:[
    {name:'Totalitarian surveillance and control',appears:'Telescreens, the Thought Police, the Two Minutes Hate, informants, and Winston’s constant awareness that private behavior may be observed.',choices:'Close narration keeps the possibility of surveillance present in Winston’s thoughts and behavior.',interpretation:'Control works through visible monitoring and through internalized fear, self-censorship, and anticipation of punishment.',compare:'The Handmaid’s Tale — pervasive state surveillance and ideological conformity.'},
    {name:'Language and thought control',appears:'Newspeak, doublethink, thoughtcrime, “unperson,” and the Party’s paradoxical slogans.',choices:'Orwell invents political vocabulary the reader must learn from inside the regime’s logic.',interpretation:'The novel presents language control as an attempt to reduce the very possibility of imagining or expressing dissent.',compare:'The Handmaid’s Tale — euphemistic institutional vocabulary as a parallel control mechanism.'},
    {name:'Manipulation of truth and history',appears:'Winston’s daily work altering records and the routine destruction of evidence that contradicts the Party’s current claims.',choices:'Historical revision is presented as ordinary bureaucratic labor rather than an occasional extraordinary act.',interpretation:'Control of the past becomes inseparable from control of the present because evidence itself can be continually remade.',compare:'Persepolis — propaganda and manufactured belief, but through memoir-based historical experience.'},
    {name:'Betrayal and psychological control',appears:'O’Brien’s trap, imprisonment, Room 101, and Winston and Julia’s mutual betrayal under torture.',choices:'The final section shifts from political rebellion to intimate psychological destruction.',interpretation:'The Party seeks not just obedience but internal surrender, destroying the private loyalties that might compete with state power.',compare:'The Stranger — a contrasting relationship between an individual and forces larger than himself.'},
    {name:'The body and private life as resistance',appears:'Winston and Julia’s affair, the rented room, sensory pleasures, and the desire for unmonitored intimacy.',choices:'Private desire is repeatedly contrasted with the Party’s sterile, regulated public world.',interpretation:'The Party treats bodily autonomy, intimacy, memory, and private pleasure as politically dangerous because they create loyalties beyond the state.',compare:'The Handmaid’s Tale — state regulation of intimacy and reproduction.'}
  ],
  symbols:[
    {title:'Big Brother',text:'Represents the Party’s manufactured personality cult and the illusion of a benevolent, all-seeing authority.'},
    {title:'Glass paperweight',text:'Represents the beauty and fragility of the past and private memory. Its destruction during the arrest mirrors the destruction of Winston’s imagined private world.'},
    {title:'Telescreens',text:'Represent the collapse of the boundary between public and private space through constant state surveillance.'},
    {title:'Room 101',text:'Represents individualized psychological domination: the Party identifies and weaponizes each person’s deepest fear.'},
    {title:'The golden country',text:'A recurring pastoral image representing freedom, nature, bodily autonomy, and an imagined life beyond the Party’s reach.'},
    {title:'The prole woman singing',text:'Represents ordinary human continuity and a kind of hope Winston associates with lives less completely absorbed into Party ideology.'}
  ],
  motifs:[
    {title:'Party slogans',text:'Recurring paradoxical propaganda normalizes doublethink by making contradiction itself part of everyday political language.'},
    {title:'Rats',text:'Repeated references gradually build toward their use as Winston’s personalized instrument of terror in Room 101.'},
    {title:'Memory holes and altered documents',text:'The routine repetition of record destruction reinforces historical manipulation as a permanent bureaucratic process.'}
  ],
  choices:[
    {title:'Invented political vocabulary',text:'Terms such as Newspeak, doublethink, thoughtcrime, and unperson immerse the reader in the Party’s linguistic system instead of merely describing it from outside.'},
    {title:'Close third-person narration',text:'The narrative remains tightly aligned with Winston’s consciousness, creating claustrophobic access to fear, hope, uncertainty, and eventual collapse.'},
    {title:'Embedded text within the novel',text:'Goldstein’s book interrupts the narrative with ideological exposition while also leaving its authenticity uncertain because it may be part of the Party’s trap.'},
    {title:'Three-part structural arc',text:'The novel moves from private rebellion, to connection and imagined resistance, to imprisonment and destruction, mirroring Winston’s movement toward total defeat.'},
    {title:'Newspeak appendix in past tense',text:'The appendix is written from a later-looking perspective. The profile treats this as a structural detail that some readers interpret as suggesting Newspeak and the Party do not last forever, without presenting that interpretation as certain.'}
  ],
  voice:'The novel uses close third-person narration focused tightly on Winston Smith. The reader receives privileged access to his doubts, memories, private rebellions, hopes, and misjudgments — precisely the internal life the Party aims to eliminate. This perspective also creates dramatic irony because the reader can sense danger accumulating around figures such as Mr. Charrington and O’Brien even while Winston continues to invest them with hope.',
  structure:'The novel is divided into three broad movements. Part One establishes Winston’s world and private disillusionment; Part Two develops his relationship with Julia and his movement toward the apparent Brotherhood; Part Three follows imprisonment, torture, and psychological “reeducation” at the Ministry of Love. The Newspeak appendix follows the main narrative and is written in past tense, which some readers interpret as a subtle indication that the Party’s linguistic project eventually ends.',
  setting:'The novel is set in Airstrip One, formerly Great Britain, a province of the totalitarian superstate Oceania. London is bleak, rationed, war-scarred, and saturated with propaganda and surveillance. Oceania remains in apparently endless conflict with one of two rival superstates, with alliances changing without official acknowledgment. This unstable geopolitical setting supports the Party’s manufacture of crisis, loyalty, and historical uncertainty.',
  moments:[
    {n:1,title:'Winston passes a Big Brother poster',why:'Establishes the Party’s visual presence and the sense of being watched from the opening of the novel.',choices:'Repeated propaganda imagery.',themes:'Surveillance, control, propaganda.',paper2:'Compare propaganda imagery with Persepolis.'},
    {n:2,title:'Winston begins the illegal diary',why:'Marks his first deliberate private act of rebellion and immediately connects thought with political danger.',choices:'Intimate internal narration and forbidden writing.',themes:'Individuality, rebellion, thought control.'},
    {n:3,title:'The Two Minutes Hate',why:'Shows collective emotion being manufactured and directed as a political technology.',choices:'Frenzied, ritualized group scene.',themes:'Propaganda, control, collective emotion.',paper2:'Compare orchestrated public ritual with The Handmaid’s Tale.'},
    {n:4,title:'Winston and Julia exchange early glances',why:'Introduces the possibility of private connection within a world defined by suspicion.',choices:'Suspicion gradually shifting toward intrigue.',themes:'Resistance, intimacy, surveillance.'},
    {n:5,title:'Julia passes Winston a brief love note',why:'Launches their relationship through a tiny, dangerous written act.',choices:'Compressed, risky written communication.',themes:'Intimacy, resistance, secrecy.'},
    {n:6,title:'The secret meeting in the golden country',why:'Creates a symbolic space of freedom beyond the Party’s immediate social world.',choices:'Pastoral and idyllic natural imagery.',themes:'Freedom, hope, the body.'},
    {n:7,title:'Winston and Julia rent the room above the shop',why:'Creates the illusion of a protected private refuge that later proves completely false.',choices:'Nostalgic, apparently safe setting.',themes:'Privacy, resistance, surveillance.'},
    {n:8,title:'Winston buys the glass paperweight',why:'Connects him materially to beauty, memory, and a past the Party cannot fully control in his imagination.',choices:'Symbolic object associated with private history.',themes:'Memory, individuality, fragility.'},
    {n:9,title:'O’Brien invites Winston to his apartment',why:'Deepens Winston’s false belief that organized resistance exists and that O’Brien shares his doubts.',choices:'Deceptively warm and trusting tone.',themes:'Hope, betrayal, manipulation.'},
    {n:10,title:'Winston and Julia read Goldstein’s book',why:'Provides the novel’s densest ideological explanation while also placing the document inside a possible Party trap.',choices:'Extended embedded political text.',themes:'Truth, ideology, manipulation.'},
    {n:11,title:'Mr. Charrington is revealed as Thought Police',why:'Destroys the illusion of privacy and retroactively reinterprets the rented room as a surveillance space.',choices:'Sudden reversal and revelation.',themes:'Surveillance, betrayal, privacy.',paper2:'Compare surveillance betrayal with The Handmaid’s Tale.'},
    {n:12,title:'Winston enters the Ministry of Love as a prisoner',why:'Marks the structural transition from rebellion and hope into systematic psychological destruction.',choices:'Bleak institutional setting.',themes:'Control, imprisonment, psychological torture.'},
    {n:13,title:'O’Brien reveals himself as Winston’s torturer',why:'Reframes the supposed Brotherhood connection as deliberate manipulation.',choices:'Calm, intimate, controlled cruelty.',themes:'Betrayal, power, psychological control.'},
    {n:14,title:'O’Brien forces Winston toward doublethink under torture',why:'Dramatizes the Party’s goal of controlling what Winston accepts as reality, not merely what he says publicly.',choices:'Philosophical dialogue conducted through physical coercion.',themes:'Truth, doublethink, psychological control.',paper2:'Compare manufactured truth with regime narratives in The Handmaid’s Tale.'},
    {n:15,title:'Room 101 and Winston’s fear of rats',why:'Represents the Party’s most individualized method of breaking resistance by weaponizing a private terror.',choices:'Personalized horror rather than generalized punishment.',themes:'Fear, betrayal, total control.'},
    {n:16,title:'Winston betrays Julia',why:'Shows the destruction of his final private loyalty under the pressure of Room 101.',choices:'Climactic psychological reversal.',themes:'Betrayal, intimacy, defeat.'},
    {n:17,title:'Winston and Julia meet again after torture',why:'Shows that both have been permanently altered and that their former intimacy has been emptied out.',choices:'Flat, emotionally hollow tone.',themes:'Loss, betrayal, defeat.'},
    {n:18,title:'Winston accepts Big Brother at the end',why:'Closes the main narrative with complete psychological capitulation rather than external obedience alone.',choices:'Quiet, unsettling finality.',themes:'Total control, defeat, internalized power.',paper2:'Compare the finality of defeat with more open endings in other studied works.'},
    {n:19,title:'Syme disappears',why:'Provides an early understated warning that intelligence and loyal service do not protect someone the Party considers dangerous.',choices:'Underexplained absence.',themes:'Thought control, disappearance, intelligence.'},
    {n:20,title:'Parsons is arrested after being denounced by his child',why:'Shows the Party’s success in turning family loyalty into another instrument of surveillance and control.',choices:'Darkly ironic treatment of enthusiastic loyalty.',themes:'Betrayal, family, surveillance, control.',paper2:'Compare erosion of family trust with state-mandated relationships in The Handmaid’s Tale.'}
  ],
  evidence:[
    {title:'Ministry of Truth propaganda',text:'Use the Party’s paradoxical building slogans as an evidence location for arguments about doublethink, propaganda, and the weaponization of contradiction. Verify the exact wording in your assigned copy before quoting.'},
    {title:'Winston on controlling history',text:'Use the point where Winston reflects on the relationship between control of the past and control of the present. It supports arguments about record manipulation, memory, truth, and political power. Verify exact wording before quoting.'},
    {title:'The final Chestnut Tree Café scene',text:'Use Winston’s final internal state as evidence for the Party’s psychological victory. The restrained ending supports arguments that the regime succeeds by remaking belief, not merely enforcing outward obedience.'}
  ],
  connections:[
    {theme:'Surveillance and control',with:'The Handmaid’s Tale',similarity:'Both depict constant surveillance that pressures people toward ideological conformity.',difference:'Orwell’s control targets the population broadly through political and psychological mechanisms; Atwood’s system is especially gendered and reproductive.',methods:'Invented political vocabulary, telescreens, and public ritual vs. euphemistic ritual language and regulation of women’s bodies.',why:'Shows how similar totalizing aims can operate through different social targets and techniques.'},
    {theme:'Manipulation of truth and history',with:'Persepolis',similarity:'Both depict regimes manufacturing belief through propaganda and ideological narratives.',difference:'Orwell constructs a fictional, total system of continuous record alteration; Satrapi presents memoir-based historical experience and witnessed propaganda.',methods:'Bureaucratic record editing and invented vocabulary vs. graphic memoir, witnessed propaganda, and retrospective narration.',why:'Useful for comparing imagined systemic control with personal testimony about historical ideological pressure.'},
    {theme:'Individual vs. oppressive system',with:'The Stranger',similarity:'Both protagonists are ultimately overwhelmed by forces larger than themselves.',difference:'Winston is deliberately broken through targeted political and psychological torture; Meursault’s fate is tied more to social judgment, existential estrangement, and the justice system.',methods:'Close third-person psychological interiority vs. detached first-person narration.',why:'Clarifies contrasting psychological and existential ways of constructing an individual’s defeat.'},
    {theme:'Betrayal and destruction of trust',with:'The Handmaid’s Tale',similarity:'Both explore how authoritarian systems corrode intimate loyalty and private trust.',difference:'Orwell concentrates betrayal in explicit torture and Room 101, while Atwood more often develops mistrust through surveillance, coercion, and accumulated compromise.',methods:'Acute torture-centered climax vs. gradual pressure, ambiguity, and forced complicity.',why:'Shows different mechanisms by which institutional power enters private relationships.'}
  ],
  arguments:[
    'The Party’s control depends as much on manufactured internal belief as on external force.',
    'Newspeak is presented as one of the Party’s most powerful long-term tools because restricting language also restricts imaginable dissent.',
    'Winston’s diary and affair function as doomed assertions of private individuality against institutional control.',
    'The past tense of the Newspeak appendix can support a subtle hopeful interpretation, although the main narrative itself remains bleak.',
    'O’Brien demonstrates that betrayal and psychological intimacy can be more destructive than impersonal force.',
    'The proles are associated with ordinary human continuity and a potential source of resistance that Winston never manages to activate.',
    'The novel treats control of historical records as inseparable from control of present political reality.',
    'Room 101 shows the Party’s preference for individualized psychological attack over generalized punishment.',
    'The main narrative ending deliberately denies a comforting triumph of individual resistance.',
    'Syme and Parsons show that neither intelligence nor enthusiastic loyalty offers reliable protection under totalitarian power.'
  ],
  misunderstandings:[
    'Do not present Big Brother as a confirmed individual person. The novel deliberately leaves his literal existence unresolved and uses him as a constructed symbol.',
    'Do not treat the Party’s paradoxical slogans as accidental contradictions. Their contradiction is purposeful and connected to doublethink.',
    'Do not turn Winston into a conventional heroic rebel. His resistance is limited, private, often self-interested, and ultimately defeated.',
    'Do not skip the Newspeak appendix in analysis. The profile treats its past-tense perspective as structurally important, while keeping its hopeful implication open to interpretation.'
  ],
  faqs:[
    {q:'Is Big Brother a real person in the novel?',a:'The profile treats this as deliberately ambiguous. Analyze the uncertainty and symbolic function rather than resolving it as a definite fact.'},
    {q:'What is doublethink?',a:'The capacity to accept contradictory beliefs at the same time. In the profile, it is central to understanding how the Party tries to control internal thought rather than only public behavior.'},
    {q:'Does the novel end hopefully or hopelessly?',a:'The main narrative is bleak and ends with Winston’s psychological capitulation. The past tense of the Newspeak appendix is often read as a subtle structural note of hope, but that reading should be argued rather than treated as certain.'},
    {q:'Can I memorize the Party slogans from this profile as exact quotations?',a:'No. This profile paraphrases evidence locations. Verify exact wording against your assigned copy before using any direct quotation.'}
  ]
};

if(!bookProfiles.some(profile=>profile.id===nineteenEightyFour.id))bookProfiles.push(nineteenEightyFour);
