import {bookProfiles,type BookProfile} from './books-data';

export const frankenstein:BookProfile={
  id:'frankenstein',
  title:'Frankenstein; or, The Modern Prometheus',
  author:'Mary Shelley',
  year:'1818 / revised 1831',
  form:'Gothic novel • frame narrative • early science-fiction precursor',
  language:'English',
  level:'HL studied work',
  context:'Conceived in 1816 during the famous ghost-story challenge near Lake Geneva and written by Mary Shelley at eighteen or nineteen. The novel reflects Romantic-era interest in the sublime power of nature and contemporary scientific debates such as galvanism, while its subtitle invokes Prometheus and the danger of transgressive knowledge. The first edition appeared anonymously in 1818; Shelley revised the novel for the 1831 edition, so class analysis should confirm which edition is being studied.',
  overview:'Victor Frankenstein becomes obsessed with discovering the secret of life and creates a living being from assembled body parts. Horrified by the Creature’s appearance, he abandons it immediately. The Creature begins gentle and eager for connection, but repeated rejection drives him toward revenge. William is murdered, Justine is wrongly executed, and the Creature demands a female companion. Victor begins one, then destroys it, triggering the murders of Clerval and Elizabeth. Victor pursues the Creature into the Arctic, where he dies after telling his story to explorer Robert Walton. The Creature appears one final time to mourn Victor before disappearing into the ice.',
  characters:[
    {name:'Victor Frankenstein',role:'Protagonist and central narrator inside Walton’s frame; brilliant, ambitious, increasingly guilt-ridden.',development:'Moves from confident intellectual ambition through horror, guilt, secrecy, and obsession into a consuming pursuit of the Creature.',themes:'Dangerous knowledge, ambition, responsibility, guilt, isolation, revenge.',methods:'First-person retrospective narration addressed to Walton, shaped by warning, self-justification, guilt, and hindsight.'},
    {name:'The Creature',role:'Victor’s creation; initially gentle, curious, articulate, and eager for human connection, later deliberately vengeful.',development:'Moves from innocence and hope through repeated rejection to calculated revenge against Victor and those close to him.',themes:'Isolation, rejection, nature vs. nurture, monstrosity, responsibility, revenge.',methods:'Given an extended eloquent first-person narrative within Victor’s account, forcing the reader to reconsider Victor’s initial framing of him.'},
    {name:'Robert Walton',role:'Arctic explorer whose letters frame the novel; ambitious and initially isolated.',development:'Recognizes himself in Victor’s story and ultimately chooses restraint by turning the ship back.',themes:'Ambition, isolation, warning, responsibility.',methods:'Functions as Victor’s structural double: another glory-seeking man whose choices show that ambition does not have to end in Victor’s way.'},
    {name:'Elizabeth Lavenza',role:'Victor’s adopted cousin and eventual wife; associated with domestic affection and family stability.',development:'Remains largely idealized through Victor’s perspective and is murdered by the Creature on her wedding night.',themes:'Family, domestic ideal, loss, consequences of Victor’s secrecy.',methods:'Characterized mainly through Victor’s idealizing narration rather than an independent narrative voice.'},
    {name:'Henry Clerval',role:'Victor’s childhood friend; warm, imaginative, sociable, and emotionally balanced.',development:'Provides a contrast to Victor’s obsessive isolation before being murdered by the Creature.',themes:'Friendship, balance, isolation, revenge, guilt.',methods:'Used as Victor’s foil: humane and connected where Victor becomes withdrawn and consumed by his work.'},
    {name:'Justine Moritz',role:'Kind family servant who is falsely accused and executed for William’s murder.',development:'Her death exposes the consequences of Victor’s silence and refusal to reveal what he knows.',themes:'Guilt, silence, injustice, moral responsibility.',methods:'Used to dramatize the human cost of Victor’s secrecy and inaction beyond his immediate relationship with the Creature.'}
  ],
  themes:[
    {name:'Dangerous knowledge and ambition',appears:'Victor’s obsessive pursuit of the secret of life and Walton’s dangerous Arctic ambition echo the Prometheus myth in the subtitle.',choices:'Victor retrospectively narrates his life as a warning to Walton, while Walton acts as a structural double who can still choose differently.',interpretation:'Unchecked ambition can produce devastating consequences when intellectual achievement becomes detached from responsibility.',compare:'1984 — punished or dangerous knowledge-seeking, though the source of danger differs.'},
    {name:'Creation and parental responsibility',appears:'Victor animates the Creature and immediately abandons him, refusing responsibility for the life he has made.',choices:'The novel repeatedly parallels creation with parenthood and makes abandonment the central ethical failure after the act of creation.',interpretation:'The critique falls not only on creation itself but on refusing care, accountability, and responsibility toward what one creates.',compare:'The Handmaid’s Tale — a contrast between uncontrolled individual creation and state-controlled reproduction.'},
    {name:'Isolation and rejection',appears:'Victor chooses isolation during his research; the Creature is isolated because others reject his appearance.',choices:'Parallel first-person narratives let both Victor and the Creature describe their isolation from inside their own perspectives.',interpretation:'Isolation can be chosen or imposed, but both forms become destructive when human connection collapses.',compare:'The Stranger — contrasting self-generated and socially imposed forms of alienation.'},
    {name:'Monstrosity vs. appearance',appears:'The Creature begins capable of gentleness, sympathy, learning, and wonder but is repeatedly treated as monstrous because of how he looks.',choices:'The gap between his articulate self-narration and other characters’ immediate revulsion destabilizes easy judgments about who the “monster” is.',interpretation:'The novel can locate monstrosity in rejection and cruelty rather than in appearance or inherent nature alone.',compare:'Carol Ann Duffy — first-person voicing of figures treated as rejected, othered, or monstrous.'},
    {name:'Nature and the sublime',appears:'The Alps, Mont Blanc, storms, remote landscapes, and the Arctic repeatedly surround moments of emotional crisis.',choices:'Romantic pathetic fallacy and extended landscape description connect the external world to characters’ psychological states.',interpretation:'Nature is not passive background; it amplifies emotional and moral crisis through distinctly Romantic conventions.'}
  ],
  symbols:[
    {title:'Fire',text:'Connects to the Prometheus myth and embodies knowledge as both transformative and destructive. The Creature’s discovery that fire can warm and burn mirrors that duality.'},
    {title:'Light and darkness',text:'Scientific “illumination” promises knowledge but produces horror, making light imagery morally ambiguous rather than simply positive.'},
    {title:'Arctic ice',text:'Represents isolation, moral bleakness, extremity, and a landscape beyond ordinary human society, fitting the novel’s final pursuit.'},
    {title:'The De Lacey cottage',text:'Represents the domestic warmth, acceptance, and ordinary human belonging the Creature desires but is ultimately denied.'}
  ],
  motifs:[
    {title:'Pursuit and chase',text:'Victor pursues forbidden knowledge, the Creature pursues connection and revenge, and Victor finally pursues the Creature, reinforcing obsession as a structural pattern.'},
    {title:'Storms and sublime landscapes',text:'Recurring natural imagery mirrors psychological turmoil and reinforces the novel’s Romantic relationship between emotion and environment.'},
    {title:'Doubling',text:'Victor / Creature and Victor / Walton parallels repeatedly show how ambition, isolation, and responsibility can produce mirrored or diverging fates.'}
  ],
  choices:[
    {title:'Nested frame narrative',text:'Walton’s letters contain Victor’s narrative, which contains the Creature’s narrative. The layering gives competing perspectives on the same events and allows the Creature to directly challenge Victor’s framing.'},
    {title:'Epistolary outer frame',text:'Walton’s letters place the novel inside secondhand testimony and invite questions about reliability, mediation, and whose account the reader is receiving.'},
    {title:'Vagueness about the creation method',text:'Shelley avoids explaining the exact scientific procedure, keeping attention on ethical, emotional, and human consequences rather than technical plausibility.'},
    {title:'The Creature’s extended first-person voice',text:'Giving the Creature eloquent, philosophical narration works against expectations of a mute or simple monster and actively builds reader sympathy.'},
    {title:'Pathetic fallacy and landscape description',text:'Extended Romantic descriptions of nature repeatedly mirror or intensify characters’ psychological states.'}
  ],
  voice:'The novel uses nested first-person narration. Robert Walton’s letters frame Victor Frankenstein’s retrospective account, and Victor’s account contains the Creature’s own extended first-person story. Each speaker has a distinct agenda: Victor is guilt-laden and often self-justifying, while the Creature is eloquent, philosophical, and increasingly embittered. The reader therefore has to weigh competing accounts rather than treating one narrator as objective truth.',
  structure:'The structure moves inward and then outward again: Walton’s letters open the novel and contain Victor’s life story; Victor’s narrative pauses for the Creature’s extended account; the text then returns to Victor before finally returning to Walton for the conclusion. This nesting formally reinforces the novel’s concern with testimony, sympathy, responsibility, and how stories pass between people.',
  setting:'The novel moves from domestic Geneva to Ingolstadt, where Victor creates the Creature; the Swiss Alps and Mont Blanc, where Victor and the Creature confront one another; a remote Scottish island, where Victor destroys the unfinished female creature; and finally the Arctic, where Victor dies. The movement toward increasingly remote and desolate settings mirrors Victor’s movement away from family life and deeper into destructive isolation.',
  moments:[
    {n:1,title:'Walton’s opening Arctic letters',why:'Establish Walton’s ambition and isolation before Victor appears, preparing him as Victor’s structural double.',choices:'Epistolary frame opening.',themes:'Ambition, isolation, doubling.'},
    {n:2,title:'Walton discovers Victor on the ice',why:'Launches the frame narrative and connects the explorer’s ambitions to Victor’s warning story.',choices:'Dramatic rescue scene within the letter frame.',themes:'Isolation, ambition, warning.'},
    {n:3,title:'Victor’s Geneva childhood and Elizabeth',why:'Establishes the domestic ideal and family warmth that Victor’s later choices help destroy.',choices:'Warm, nostalgic retrospective tone.',themes:'Family, domestic ideal, loss.'},
    {n:4,title:'Victor’s fascination with alchemists',why:'Shows the intellectual roots of his later obsession with forbidden knowledge.',choices:'Retrospective self-analysis.',themes:'Dangerous knowledge, ambition.'},
    {n:5,title:'Victor secretly creates the Creature',why:'The central act that drives the novel while showing how ambition narrows Victor’s world.',choices:'Scientific detail is elided; narration emphasizes obsession and isolation.',themes:'Creation, ambition, dangerous knowledge.'},
    {n:6,title:'Animation and immediate abandonment',why:'Victor’s horror and flight create the novel’s central ethical failure: creation without responsibility.',choices:'Abrupt tonal shift from anticipation to revulsion.',themes:'Parental responsibility, creation, rejection.',paper2:'Compare anxieties around creation and reproduction with The Handmaid’s Tale.'},
    {n:7,title:'William’s murder and Justine’s execution',why:'Shows the human cost of Victor’s secrecy, silence, and refusal to accept responsibility.',choices:'Tragic consequence and unjust outcome.',themes:'Guilt, responsibility, injustice.'},
    {n:8,title:'Victor meets the Creature near Mont Blanc',why:'The Creature demands to be heard and the narrative perspective shifts at a pivotal moment.',choices:'Direct confrontation followed by an embedded narrative.',themes:'Voice, sympathy, responsibility.'},
    {n:9,title:'The Creature recounts early rejection',why:'Establishes his initial innocence and shows how repeated human rejection shapes his bitterness.',choices:'First-person embedded narrative.',themes:'Monstrosity, appearance, rejection.',paper2:'Compare the voicing of rejected or “othered” figures with Carol Ann Duffy.'},
    {n:10,title:'The Creature observes the De Lacey family',why:'Demonstrates his capacity for sympathy, language, learning, and moral reasoning.',choices:'Extended sympathetic narration and observation.',themes:'Nature vs. nurture, connection, isolation.'},
    {n:11,title:'The Creature reads Victor’s journal and other works',why:'Shapes his self-understanding through literary, religious, and creator/creation comparisons.',choices:'Intertextual reference and reflective narration.',themes:'Identity, monstrosity, self-knowledge.'},
    {n:12,title:'The De Laceys reject the Creature',why:'Destroys his hope of acceptance and helps catalyze his movement toward revenge.',choices:'Devastating rejection scene.',themes:'Rejection, isolation, monstrosity.'},
    {n:13,title:'The Creature murders William and frames Justine',why:'Marks the shift from suffering rejection to deliberate revenge against Victor.',choices:'Escalating violence and calculated retaliation.',themes:'Revenge, guilt, responsibility.'},
    {n:14,title:'The Creature demands a female companion',why:'Creates a major ethical dilemma around responsibility, autonomy, companionship, and further creation.',choices:'Tense negotiation scene.',themes:'Isolation, responsibility, creation.',paper2:'Compare demands for autonomy and constrained choices with The Handmaid’s Tale.'},
    {n:15,title:'Victor destroys the unfinished female creature',why:'A central moral decision driven by fear of consequences and followed by escalating revenge.',choices:'Abrupt, fearful destruction.',themes:'Responsibility, fear, control, creation.'},
    {n:16,title:'The Creature threatens Victor’s wedding night',why:'Directly foreshadows the novel’s climax and shows revenge becoming controlled and calculated.',choices:'Ominous verbal threat and foreshadowing.',themes:'Revenge, fear, anticipation.'},
    {n:17,title:'Clerval is murdered',why:'Deepens Victor’s guilt and isolation while escalating the Creature’s campaign of revenge.',choices:'Violence occurs off-page and is revealed through devastating discovery.',themes:'Revenge, guilt, isolation.'},
    {n:18,title:'Elizabeth is murdered on the wedding night',why:'Fulfills the Creature’s threat and destroys Victor’s remaining domestic future.',choices:'Dramatic irony because Victor expects the threat to target himself.',themes:'Revenge, loss, responsibility.'},
    {n:19,title:'Victor pursues the Creature into the Arctic',why:'Returns the story toward the setting of Walton’s opening and turns Victor’s life into single-minded pursuit.',choices:'Structural return to the frame; obsessive pursuit motif.',themes:'Ambition, revenge, isolation.'},
    {n:20,title:'Victor dies and the Creature mourns him',why:'Closes both inner and outer narrative frames while refusing a simple moral resolution.',choices:'Ambiguous, mournful final tone and return to Walton’s perspective.',themes:'Guilt, loss, isolation, responsibility.',paper2:'Compare unresolved endings with The Handmaid’s Tale.'}
  ],
  evidence:[
    {title:'The moment of animation',text:'Use Victor’s immediate horror and regret after the Creature awakens. The sudden change from anticipation to revulsion supports arguments about irresponsible creation, abandonment, ambition, and parental responsibility.'},
    {title:'The Creature’s early consciousness',text:'Use the Creature’s account of initial innocence, curiosity, and wonder. His eloquent first-person voice supports arguments that monstrosity develops through rejection rather than existing naturally from the beginning.'},
    {title:'The wedding-night threat',text:'Use the Creature’s controlled warning after Victor destroys the female creature. Its direct foreshadowing supports arguments about calculated revenge, fear, and the structure of the final act.'}
  ],
  connections:[
    {theme:'Creation and control over life / reproduction',with:'The Handmaid’s Tale',similarity:'Both center anxieties about creating life and controlling reproduction.',difference:'Victor’s creation is individual, transgressive, and outside women’s bodies; Gilead’s reproductive control is systematic, enforced, and centered on women’s bodies.',methods:'Gothic nested frame narrative vs. dystopian first-person testimony and institutional ritual.',why:'Creates a strong contrast between uncontrolled individual transgression and systemic institutional control over reproduction.'},
    {theme:'Isolation and alienation',with:'The Stranger',similarity:'Both explore protagonists separated from ordinary human connection.',difference:'Victor and the Creature’s isolation is emotionally heightened and often sympathy-building; Meursault’s alienation is flatter and more detached.',methods:'Romantic / Gothic emotional intensity vs. restrained existential narration.',why:'Useful for comparing how radically different narrative registers construct alienation.'},
    {theme:'Monstrosity, rejection, and otherness',with:'Carol Ann Duffy',similarity:'Both can give sustained sympathetic voice to figures others define as monstrous, rejected, or lesser.',difference:'Shelley develops the perspective through an extended prose narrative; Duffy can compress a reclaimed voice into lyric or dramatic monologue.',methods:'Embedded first-person prose narrative vs. concentrated poetic voice.',why:'Shows how a similar reclamation-of-voice project can operate at very different formal scales.'},
    {theme:'Ambition and its consequences',with:'1984',similarity:'Both show individuals whose pursuit of forbidden goals leads to devastating personal consequences.',difference:'Victor’s ambition is self-directed and unchecked; Winston’s rebellion responds to an external totalitarian system.',methods:'Gothic tragedy and frame narrative vs. political dystopia.',why:'Clarifies the contrast between self-generated transgression and resistance to externally imposed control.'}
  ],
  arguments:[
    'The novel locates the true “monster” in social rejection and cruelty rather than in the Creature’s inherent nature.',
    'Victor’s abandonment of the Creature is framed as a failure of parental responsibility, not merely scientific responsibility.',
    'The nested narrative structure forces the reader to weigh competing, self-interested accounts instead of accepting a single version of events.',
    'The novel critiques unchecked ambition through the parallel figures of Victor and Walton.',
    'Nature functions as an active mirror of psychological states rather than as mere background.',
    'The Creature’s eloquence and capacity for sympathy directly challenge assumptions created by his appearance.',
    'Victor’s destruction of the female creature reflects fear of uncontrollable consequences more than a fully reasoned ethical decision.',
    'The mournful ending resists offering a simple moral resolution to the conflict between creator and creation.',
    'Justine’s wrongful execution demonstrates how the consequences of Victor’s secrecy spread beyond his direct victims.',
    'The novel critiques rational and scientific ambition when it becomes detached from responsibility and empathy.'
  ],
  misunderstandings:[
    'Do not call the Creature “Frankenstein.” Frankenstein is Victor’s surname; the Creature is never formally named, which is itself analytically significant.',
    'Do not treat the Creature as mute or intellectually simple. He receives an extended, sophisticated first-person narrative.',
    'Do not reduce the novel to straightforward horror. The profile treats it as a Gothic / Romantic work deeply concerned with ethics, responsibility, sympathy, and ambition.',
    'Avoid making Victor a simple villain or the Creature a simple victim. The nested perspectives deliberately complicate moral judgment of both.'
  ],
  faqs:[
    {q:'Which edition should we study: 1818 or 1831?',a:'Confirm the assigned class edition with your teacher. The profile notes that textual differences exist, including differences relevant to Victor’s characterization and ideas of fate versus free will.'},
    {q:'Is Frankenstein science fiction?',a:'The profile describes it as widely regarded as an early precursor to science fiction while also emphasizing that it is strongly Gothic and Romantic. Those framings can coexist in analysis.'},
    {q:'Why does the novel not explain exactly how the Creature is made?',a:'The profile treats the vagueness as an authorial choice that keeps attention on the ethical and emotional consequences of creation rather than on technical plausibility.'}
  ]
};

if(!bookProfiles.some(profile=>profile.id===frankenstein.id))bookProfiles.push(frankenstein);
