import './contributor-program-v3.css';

const U='https://qdqseajcukfdbfikjptu.supabase.co',K='sb_publishable_FNjxRB0rtl5TwnC8NtCDGg_RHEpSZLN',S='litlabSupabaseSession',HV=1;
const VT='litlabContributionVisitorToken',FT='litlabContributionFeedbackToken';
type Row=Record<string,any>;
type W=Row&{id:string;status:string;applicant_type:'student'|'teacher';topics:string;contribution_type:string;brief?:Row|null;tasks?:Row[];revisions?:Row[];documents?:Row[];reviews?:Row[];activities?:Row[];reviewer?:Row|null;v3?:Row|null};
let ws:W[]=[],selected='',noticeRows:Row[]=[],noticePanel:HTMLElement|null=null,noticeTimer=0,enhanceTimer=0;

function tok(){try{return String(JSON.parse(localStorage.getItem(S)||'null')?.access_token||'')}catch{return ''}}
function route(){return location.hash.replace(/^#/,'').split('#')[0].split('?')[0]||'home'}
function e(v:any){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
function lab(v:any){return String(v??'').replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function date(v?:string){if(!v)return 'Not recorded';const d=new Date(v);return Number.isNaN(d.getTime())?'Not recorded':d.toLocaleDateString([],{year:'numeric',month:'short',day:'numeric'})}
function stamp(v?:string){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function uid(key:string){try{const x=localStorage.getItem(key);if(x&&/^[0-9a-f-]{36}$/i.test(x))return x;const n=crypto.randomUUID();localStorage.setItem(key,n);return n}catch{return crypto.randomUUID()}}
function app(){return ws.find(x=>x.id===selected)||ws[0]||null}
async function rpc<T=any>(name:string,body:Row={},auth=true):Promise<T>{const c=new AbortController(),t=setTimeout(()=>c.abort(),12000),h:Row={'Content-Type':'application/json',Accept:'application/json',apikey:K};if(auth){if(!tok())throw new Error('Sign in required');h.Authorization=`Bearer ${tok()}`}try{const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:h as HeadersInit,body:JSON.stringify(body),signal:c.signal});if(!r.ok){let m=`${name} failed (${r.status})`;try{m=(await r.json()).message||m}catch{}throw new Error(m)}const x=await r.text();return (x?JSON.parse(x):null) as T}finally{clearTimeout(t)}}
function refresh(){window.dispatchEvent(new CustomEvent('litlab:contributor-workspace-updated'))}

function standards(role:string){return role==='teacher'?[['Scope','Review only student work LitLab assigns to you.'],['Accuracy','Check claims, DP terminology and sources; flag uncertainty instead of guessing.'],['Actionable feedback','Name a specific strength, issue, reason and next revision target.'],['Student ownership','Do not rewrite assessed work or provide ready-to-submit answers.'],['Privacy','Keep student documents and private feedback inside the assigned LitLab workflow.'],['Decision','Approve only when the current DOCX is genuinely ready; otherwise request changes.']]:[['Original work','Write your own explanations and examples; do not copy study-guide material.'],['Reliable sources','Use dependable sources when research is needed and make source use visible.'],['IB boundaries','Do not upload leaked papers, mark schemes, full copyrighted texts or ready-to-submit assessed work.'],['Clear claims','Separate official/course facts from student strategies and verify uncertain requirements.'],['Feedback','Respond specifically to requested revisions and explain what changed.'],['CAS accuracy','Log only genuine work; your school, not LitLab, decides CAS approval.'],['Privacy','Do not include student IDs, phone numbers, home addresses or sensitive personal information.']];}
function standardCard(a:W){const done=a.v3?.onboarding?.handbook_version===HV,items=standards(a.applicant_type);return `<article class="ll-workspace-card ll-v3-standard" data-v3-standard id="ll-v3-standard"><div class="ll-card-title"><div><span>${a.applicant_type==='teacher'?'TEACHER REVIEWER STANDARD':'CONTRIBUTOR STANDARD'}</span><h3>${done?'Orientation complete':'Read this once before active work'}</h3></div><em>${done?`Completed ${e(date(a.v3?.onboarding?.completed_at))}`:`Version ${HV}`}</em></div><p class="ll-muted">${a.applicant_type==='teacher'?'A short professional standard for fair, constructive and private mentoring.':'A short quality and integrity standard so every LitLab contribution is useful, original and accurately represented.'}</p><div class="ll-v3-standard-list">${items.map((x,i)=>`<label><input type="checkbox" data-v3-standard-check ${done?'checked disabled':''}/><span><b>${i+1}. ${e(x[0])}</b>${e(x[1])}</span></label>`).join('')}</div>${done?'<div class="ll-v3-success">✓ Current orientation completed.</div>':`<button class="ll-v3-primary" type="button" data-v3-onboard="${a.applicant_type}">Complete orientation</button><small data-v3-state role="status"></small>`}</article>`}

function milestones(a:W){const v=a.v3||{},work=Boolean(a.documents?.length||a.activities?.length||v.evidence?.length||v.reflections?.length||a.tasks?.some((x:Row)=>x.status&&x.status!=='pending')),review=Boolean(a.reviews?.length||a.revisions?.length);return [['Application','Submitted',true],['Approval','Accepted',['accepted','reviewing','completed'].includes(a.status)],['Project brief','Agreed',Boolean(v.brief_agreement?.is_current)],['Contribution','Work started',work],['Feedback','Reviewed / revised',review],['Final approval','Completed',a.status==='completed'],['Publication','Published if selected',Boolean(v.publication?.active)],['Recognition','Certificate issued',Boolean(v.certificate)]]}
function next(a:W){const v=a.v3||{},rev=a.revisions?.find((x:Row)=>x.status==='open'||x.status==='responded');if(a.status==='new')return ['waiting','Application under review','Wait for LitLab review; you can complete orientation now.','standard'];if(a.status==='declined')return ['closed','Application closed','Your saved application and feedback remain available.',''];if(a.status==='completed'&&v.publication?.active)return ['impact','Your contribution is live','Review showcase interactions and anonymous usefulness feedback.','impact'];if(a.status==='completed')return ['complete','Contribution complete',v.certificate?'Your certificate is ready in contribution history.':'Final approval is saved; LitLab can issue a certificate from the verified record.','history'];if(!v.onboarding||v.onboarding.handbook_version<HV)return ['action','Complete contributor orientation','Read the short quality, integrity and privacy standard before active work.','standard'];if(a.brief&&!v.brief_agreement?.is_current)return ['action','Accept the latest project brief','Confirm the goal, audience, deliverable, standard and deadline before continuing.','brief'];if(rev)return ['revision','Revision needs attention','Use the revision request as your source of truth, then explain what you changed.','revisions'];if(!a.documents?.length)return ['action','Prepare your first DOCX','Follow the agreed brief and upload a clear first draft when it is ready.','documents'];if(a.reviewer?.name&&!a.reviews?.length)return ['waiting','Your work is with the reviewer',`${a.reviewer.name} is assigned. You will be notified when feedback is available.`,''];return ['progress','Keep moving toward final approval','Use tasks, revisions and reviews as the source of truth. Add evidence/reflections only when meaningful.','journey']}
function journey(a:W){const m=milestones(a),n=next(a),count=m.filter(x=>x[2]).length;return `<section class="ll-v3-journey" data-v3-journey id="ll-v3-journey"><div class="ll-v3-journey-head"><div><span>CONTRIBUTOR JOURNEY</span><h2>One clear path from application to impact.</h2><p>This summarizes records already in your workspace; it does not create a second task list.</p></div><strong>${count}/${m.length}<small>milestones</small></strong></div><div class="ll-v3-next is-${e(n[0])}"><div><span>NEXT ACTION</span><h3>${e(n[1])}</h3><p>${e(n[2])}</p></div>${n[3]?`<button type="button" data-v3-jump="${e(n[3])}">Go there ↓</button>`:''}</div><div class="ll-v3-milestones">${m.map((x,i)=>`<div class="${x[2]?'is-done':(!m.slice(0,i).some(y=>!y[2])?'is-current':'')}"><i>${x[2]?'✓':String(i+1).padStart(2,'0')}</i><section><b>${e(x[0])}</b><span>${e(x[1])}</span></section>${i<m.length-1?'<em></em>':''}</div>`).join('')}</div><p class="ll-v3-milestone-note">Publication is optional. A LitLab certificate verifies contribution work; it does not certify school/IB CAS approval.</p></section>`}

function briefBox(a:W){if(a.applicant_type!=='student'||!a.brief)return '';const g=a.v3?.brief_agreement,ok=Boolean(g?.is_current),v=Number(g?.version||a.brief.version||1);return `<div class="ll-v3-brief-agreement ${ok?'is-accepted':'needs-acceptance'}" data-v3-brief-box><div><span>${ok?'✓ AGREED PROJECT BRIEF':'ACTION REQUIRED'}</span><b>Project brief v${v}</b><p>${ok?`You accepted this version${g?.accepted_at?` on ${date(g.accepted_at)}`:''}. If LitLab changes it, you will be asked to accept the new version.`:'Read the brief above and accept this exact version so everyone works from the same plan.'}</p></div>${!ok&&['accepted','reviewing'].includes(a.status)?`<button type="button" data-v3-accept-brief="${e(a.id)}">Accept project brief v${v}</button>`:''}</div>`}
function reflectionCard(a:W){if(a.applicant_type!=='student')return '';const rows=a.v3?.reflections||[],ro=['completed','declined'].includes(a.status);return `<article class="ll-workspace-card ll-v3-reflections" data-v3-reflections id="ll-v3-reflections"><div class="ll-card-title"><div><span>REFLECTION JOURNAL</span><h3>Record decisions, challenges and learning.</h3></div><em>${rows.length} ${rows.length===1?'entry':'entries'}</em></div><p class="ll-muted">Reflect when something meaningful changes—research, feedback, revision or final approval. It is not a daily diary.</p>${ro?'':`<form data-v3-reflection="${e(a.id)}" class="ll-v3-reflection-form"><div class="ll-v3-form-grid two"><label><span>Date</span><input name="reflection_date" type="date" value="${new Date().toISOString().slice(0,10)}" required/></label><label><span>Stage</span><select name="stage"><option>planning</option><option>research</option><option>drafting</option><option>feedback</option><option>revision</option><option>final</option><option>impact</option><option>other</option></select></label></div><label><span>What did you work on?</span><textarea name="worked_on" minlength="5" maxlength="3000" rows="3" required></textarea></label><div class="ll-v3-form-grid two"><label><span>Challenge <small>(optional)</small></span><textarea name="challenge" maxlength="3000" rows="3"></textarea></label><label><span>How did feedback change the work? <small>(optional)</small></span><textarea name="feedback_response" maxlength="3000" rows="3"></textarea></label></div><label><span>What did you learn?</span><textarea name="learned" minlength="5" maxlength="3000" rows="3" required></textarea></label><label><span>Next step <small>(optional)</small></span><textarea name="next_step" maxlength="3000" rows="2"></textarea></label><div class="ll-v3-form-actions"><button class="ll-v3-primary" type="submit">Save reflection</button><small data-v3-state></small></div></form>`}<div class="ll-v3-reflection-list">${rows.length?rows.map((r:Row)=>`<section><header><span>${e(lab(r.stage))}</span><b>${e(date(r.reflection_date))}</b></header><h4>${e(r.worked_on)}</h4>${r.challenge?`<p><b>Challenge:</b> ${e(r.challenge)}</p>`:''}${r.feedback_response?`<p><b>Feedback response:</b> ${e(r.feedback_response)}</p>`:''}<p><b>Learning:</b> ${e(r.learned)}</p>${r.next_step?`<p><b>Next:</b> ${e(r.next_step)}</p>`:''}${ro?'':`<button type="button" data-v3-delete-reflection="${e(r.id)}">Remove entry</button>`}</section>`).join(''):'<div class="ll-v3-empty">No reflection entries yet.</div>'}</div></article>`}
function evidenceCard(a:W){if(a.applicant_type!=='student')return '';const rows=a.v3?.evidence||[],ro=['completed','declined'].includes(a.status),docs=a.documents?.length||0,revs=a.revisions?.length||0,reviews=a.reviews?.length||0,acts=a.activities?.length||0;return `<article class="ll-workspace-card ll-v3-evidence" data-v3-evidence id="ll-v3-evidence"><div class="ll-card-title"><div><span>EVIDENCE VAULT</span><h3>Keep useful evidence without duplicating the workspace.</h3></div><em>${rows.length} added item${rows.length===1?'':'s'}</em></div><div class="ll-v3-auto-evidence"><div><strong>${docs}</strong><span>DOCX versions</span></div><div><strong>${revs}</strong><span>Revision records</span></div><div><strong>${reviews}</strong><span>Teacher reviews</span></div><div><strong>${acts}</strong><span>Activity entries</span></div></div><p class="ll-muted"><b>Those records are already evidence.</b> Add only supplementary items that are not already stored elsewhere.</p>${ro?'':`<form data-v3-evidence="${e(a.id)}" class="ll-v3-evidence-form"><div class="ll-v3-form-grid two"><label><span>Type</span><select name="evidence_type"><option value="research">Research / source</option><option value="publication_link">Publication link</option><option value="social_post">Social / awareness post</option><option value="awareness_poster">Awareness poster</option><option value="campaign_asset">Campaign asset</option><option value="analytics">Analytics / impact</option><option value="other">Other</option></select></label><label><span>Title</span><input name="title" minlength="2" maxlength="180" required/></label></div><label><span>Link <small>(optional)</small></span><input name="url" type="url" maxlength="2000" placeholder="https://…"/></label><label><span>Why this matters</span><textarea name="note" maxlength="3000" rows="3"></textarea></label><div class="ll-v3-form-actions"><button class="ll-v3-primary" type="submit">Add evidence</button><small data-v3-state></small></div></form>`}<div class="ll-v3-evidence-list">${rows.length?rows.map((x:Row)=>`<section><div><span>${e(lab(x.evidence_type))}</span><b>${e(x.title)}</b><small>${e(date(x.created_at))}</small></div>${x.note?`<p>${e(x.note)}</p>`:''}${x.url?`<a href="${e(x.url)}" target="_blank" rel="noopener noreferrer">Open evidence ↗</a>`:''}</section>`).join(''):'<div class="ll-v3-empty">No supplementary evidence added. That is fine if the core workspace already documents the work.</div>'}</div></article>`}
function historyCard(a:W){if(a.applicant_type!=='student')return '';const x:Row[]=[];(a.documents||[]).forEach(d=>x.push({t:d.created_at,k:'DOCX',h:`${d.version_label} — ${d.original_name}`,p:d.note||'Word submission saved.'}));(a.revisions||[]).forEach(r=>x.push({t:r.created_at,k:'Revision',h:r.title,p:r.contributor_response?`${r.details||''}${r.details?' • ':''}Response: ${r.contributor_response}`:r.details||'Revision requested.'}));(a.reviews||[]).forEach(r=>x.push({t:r.created_at,k:'Teacher review',h:r.recommendation==='approve'?'Academic approval':'Changes requested',p:r.summary}));(a.v3?.events||[]).filter((z:Row)=>['brief_accepted','published'].includes(z.event_type)).forEach((z:Row)=>x.push({t:z.created_at,k:'Milestone',h:z.event_type==='published'?'Contribution published':'Project brief accepted',p:z.event_type==='published'?'LitLab linked the final-approved resource to the showcase.':'The current project brief was accepted.'}));x.sort((a,b)=>Date.parse(b.t)-Date.parse(a.t));return `<article class="ll-workspace-card ll-v3-history" data-v3-history id="ll-v3-history"><div class="ll-card-title"><div><span>VERSION & REVIEW HISTORY</span><h3>See how the contribution changed over time.</h3></div><em>${x.length} recorded event${x.length===1?'':'s'}</em></div><p class="ll-muted">Generated from existing submissions, revisions, reviews and milestones—no duplicate records.</p><div class="ll-v3-history-list">${x.length?x.slice(0,30).map(z=>`<section><i></i><div><header><span>${e(z.k)}</span><small>${e(stamp(z.t))}</small></header><b>${e(z.h)}</b><p>${e(z.p)}</p></div></section>`).join(''):'<div class="ll-v3-empty">History builds automatically as work is submitted and reviewed.</div>'}</div></article>`}
function impactCard(a:W){const p=a.v3?.publication;if(!p?.active)return '';const i=a.v3?.impact||{},total=Number(i.helpful_yes||0)+Number(i.helpful_no||0),pct=total?Math.round(Number(i.helpful_yes||0)/total*100):null;return `<article class="ll-workspace-card ll-v3-impact" data-v3-impact id="ll-v3-impact"><div class="ll-card-title"><div><span>YOUR IMPACT</span><h3>${e(p.title)}</h3></div><em>Published ${e(date(p.published_at))}</em></div><div class="ll-v3-impact-stats"><div><strong>${Number(i.showcase_opens||0)}</strong><span>Showcase opens</span></div><div><strong>${Number(i.unique_viewers||0)}</strong><span>Unique showcase visitors</span></div><div><strong>${pct==null?'—':pct+'%'}</strong><span>Found useful</span></div><div><strong>${total}</strong><span>Usefulness responses</span></div></div><p class="ll-muted">These are LitLab showcase interactions, not total readership claims on another site.</p><a class="ll-v3-primary ll-v3-link" href="${e(p.public_url)}" target="_blank" rel="noopener noreferrer">Open published contribution ↗</a>${i.comments?.length?`<div class="ll-v3-impact-comments"><b>Recent anonymous feedback</b>${i.comments.map((c:Row)=>`<p><span>${c.helpful?'Useful':'Needs improvement'}</span>${e(c.comment)}</p>`).join('')}</div>`:''}</article>`}
function teacherChecks(){document.querySelectorAll<HTMLFormElement>('[data-contributor-workspace] form[data-teacher-review]').forEach(f=>{if(f.querySelector('[data-v3-teacher-checklist]'))return;const d=document.createElement('div');d.dataset.v3TeacherChecklist='true';d.className='ll-v3-teacher-checklist';d.innerHTML='<span>BEFORE YOU SUBMIT</span><label><input type="checkbox" required/>I reviewed the latest assigned DOCX, not an older version.</label><label><input type="checkbox" required/>My scores match the written feedback.</label><label><input type="checkbox" required/>I named specific strengths/issues and a concrete next step.</label><label><input type="checkbox" required/>I did not rewrite assessed work for the student.</label>';f.querySelector('button[type="submit"]')?.before(d)})}
function enhance(){if(route()!=='contribute')return;const root=document.querySelector<HTMLElement>('[data-contributor-workspace]'),a=app();if(!root||!a)return;root.querySelector('[data-v3-journey]')?.remove();root.querySelectorAll('[data-v3-standard],[data-v3-reflections],[data-v3-evidence],[data-v3-history],[data-v3-impact]').forEach(z=>z.remove());const h=root.querySelector<HTMLElement>(':scope > .ll-workspace-head');h?h.insertAdjacentHTML('afterend',journey(a)):root.insertAdjacentHTML('afterbegin',journey(a));const b=root.querySelector<HTMLElement>('.ll-workspace-brief');if(b){b.querySelector('[data-v3-brief-box]')?.remove();b.id='ll-v3-brief';b.insertAdjacentHTML('beforeend',briefBox(a))}const g=root.querySelector<HTMLElement>('.ll-workspace-grid');if(g){g.insertAdjacentHTML('afterbegin',standardCard(a));if(a.applicant_type==='student')g.insertAdjacentHTML('beforeend',reflectionCard(a)+evidenceCard(a)+historyCard(a)+impactCard(a))}teacherChecks()}
function schedule(){clearTimeout(enhanceTimer);enhanceTimer=window.setTimeout(enhance,80)}
function jump(k:string){const m:Row={standard:'#ll-v3-standard',brief:'#ll-v3-brief',revisions:'.ll-revision-list',documents:'.ll-workspace-docs',impact:'#ll-v3-impact',journey:'#ll-v3-journey',history:'[data-my-contributions]'},z=document.querySelector<HTMLElement>(m[k]||'');z?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>z?.querySelector<HTMLElement>('button,input,textarea,select,a')?.focus({preventScroll:true}),450)}

async function onboard(btn:HTMLButtonElement,role:string){const card=btn.closest<HTMLElement>('[data-v3-standard]'),state=card?.querySelector<HTMLElement>('[data-v3-state]'),checks=Array.from(card?.querySelectorAll<HTMLInputElement>('[data-v3-standard-check]')||[]);if(checks.some(x=>!x.checked)){if(state){state.textContent='Check each standard after reading it.';state.dataset.state='error'}return}btn.disabled=true;try{await rpc('complete_my_litlab_contributor_onboarding',{p_role:role,p_handbook_version:HV});refresh()}catch(err){if(state){state.textContent=err instanceof Error?err.message:'Could not save orientation.';state.dataset.state='error'}}finally{btn.disabled=false}}
async function acceptBrief(btn:HTMLButtonElement,id:string){btn.disabled=true;try{await rpc('accept_my_litlab_contributor_brief',{p_application_id:id});refresh()}catch(err){alert(err instanceof Error?err.message:'Could not accept project brief.')}finally{btn.disabled=false}}
async function saveReflection(f:HTMLFormElement,id:string){if(!f.checkValidity()){f.reportValidity();return}const d=new FormData(f),s=f.querySelector<HTMLElement>('[data-v3-state]');try{await rpc('add_my_litlab_contributor_reflection',{p_application_id:id,p_reflection_date:String(d.get('reflection_date')||''),p_stage:String(d.get('stage')||'other'),p_worked_on:String(d.get('worked_on')||''),p_challenge:String(d.get('challenge')||''),p_feedback_response:String(d.get('feedback_response')||''),p_learned:String(d.get('learned')||''),p_next_step:String(d.get('next_step')||'')});if(s){s.textContent='Reflection saved.';s.dataset.state='success'}f.reset();refresh()}catch(err){if(s){s.textContent=err instanceof Error?err.message:'Could not save reflection.';s.dataset.state='error'}}}
async function delReflection(id:string){if(!confirm('Remove this reflection entry?'))return;try{await rpc('delete_my_litlab_contributor_reflection',{p_reflection_id:id});refresh()}catch(err){alert(err instanceof Error?err.message:'Could not remove reflection.')}}
async function saveEvidence(f:HTMLFormElement,id:string){if(!f.checkValidity()){f.reportValidity();return}const d=new FormData(f),s=f.querySelector<HTMLElement>('[data-v3-state]');try{await rpc('add_my_litlab_contributor_evidence',{p_application_id:id,p_evidence_type:String(d.get('evidence_type')||'other'),p_title:String(d.get('title')||''),p_url:String(d.get('url')||'').trim()||null,p_note:String(d.get('note')||'')});if(s){s.textContent='Evidence added.';s.dataset.state='success'}f.reset();refresh()}catch(err){if(s){s.textContent=err instanceof Error?err.message:'Could not add evidence.';s.dataset.state='error'}}}

function publicMarkup(){return `<section class="ll-contrib-section ll-v3-public-tools" data-v3-public-tools><div class="ll-contrib-section-head"><span>Verify & explore</span><h2>Recognition you can check. Contributions you can use.</h2><p>Verify a LitLab certificate or browse final-approved resources linked through the contributor showcase.</p></div><div class="ll-v3-public-grid"><article class="ll-v3-verify"><span>CERTIFICATE VERIFICATION</span><h3>Check a LitLab certificate</h3><p>This verifies a LitLab contribution record only, not IB/CAS approval.</p><form data-v3-verify><label><span>Certificate code</span><input name="code" required maxlength="120" autocomplete="off"/></label><button type="submit">Verify certificate</button></form><div data-v3-verify-result></div></article><article class="ll-v3-showcase"><span>CONTRIBUTOR SHOWCASE</span><h3>Published student resources</h3><p>Only final-approved contributions explicitly linked by LitLab appear here.</p><div data-v3-showcase><div class="ll-v3-public-loading">Loading published contributions…</div></div></article></div></section>`}
function mountPublic(){if(route()!=='contribute')return;const page=document.querySelector<HTMLElement>('.ll-contrib-page');if(!page||page.querySelector('[data-v3-public-tools]'))return;const cert=page.querySelector<HTMLElement>('.ll-contrib-certificate'),apply=page.querySelector<HTMLElement>('#contribute-apply');cert?cert.insertAdjacentHTML('afterend',publicMarkup()):apply?.insertAdjacentHTML('beforebegin',publicMarkup());void loadShowcase()}
async function loadShowcase(){const h=document.querySelector<HTMLElement>('[data-v3-showcase]');if(!h)return;try{const rows=await rpc<Row[]>('get_public_litlab_contributions',{},false);h.innerHTML=rows?.length?rows.map(x=>{const total=Number(x.helpful_yes||0)+Number(x.helpful_no||0);return `<section class="ll-v3-showcase-card"><div><span>${e(lab(x.contribution_type))}</span><h4>${e(x.title)}</h4><p>${e(x.topic||'LitLab student contribution')}</p><small>By ${e(x.contributor_name)} • ${e(date(x.published_at))}${total?` • ${total} usefulness responses`:''}</small></div><button type="button" data-v3-open-public="${e(x.publication_id)}" data-public-url="${e(x.public_url)}">Open resource ↗</button><details><summary>Was this useful?</summary><form data-v3-feedback="${e(x.publication_id)}"><div><label><input type="radio" name="helpful" value="true" required/>Yes</label><label><input type="radio" name="helpful" value="false" required/>Needs improvement</label></div><textarea name="comment" maxlength="1000" rows="2" placeholder="Optional: what was useful or what could be clearer?"></textarea><button type="submit">Send feedback</button><small data-v3-state></small></form></details></section>`}).join(''):'<div class="ll-v3-empty">No public contributor resources have been linked yet.</div>'}catch{h.innerHTML='<div class="ll-v3-empty">The showcase could not load right now.</div>'}}
async function verify(f:HTMLFormElement){const r=f.parentElement?.querySelector<HTMLElement>('[data-v3-verify-result]'),code=String(new FormData(f).get('code')||'').trim();if(!code||!r)return;try{const x=await rpc<Row>('verify_litlab_contributor_certificate',{p_code:code},false);r.innerHTML=!x.valid?'<div class="ll-v3-verify-result invalid"><b>Not verified</b><p>No LitLab certificate matches that code.</p></div>':`<div class="ll-v3-verify-result valid"><span>✓ VALID LITLAB CERTIFICATE</span><h4>${e(x.contributor_name)}</h4><p><b>${e(x.contribution_title)}</b><br/>${e(x.contributor_role)} • ${e(lab(x.contribution_type))}</p><dl><div><dt>Code</dt><dd>${e(x.certificate_code)}</dd></div><div><dt>Completed</dt><dd>${e(date(x.completed_at))}</dd></div><div><dt>Issued</dt><dd>${e(date(x.issued_at))}</dd></div>${x.verified_minutes!=null?`<div><dt>Verified time</dt><dd>${(Number(x.verified_minutes)/60).toFixed(1)} h</dd></div>`:''}</dl><small>Issued by ${e(x.issuer_name)} — ${e(x.issuer_title)}. This is not IB/CAS approval.</small></div>`}catch(err){r.innerHTML=`<div class="ll-v3-verify-result invalid"><b>Verification unavailable</b><p>${e(err instanceof Error?err.message:'Try again.')}</p></div>`}}
async function feedback(f:HTMLFormElement,id:string){if(!f.checkValidity()){f.reportValidity();return}const d=new FormData(f),s=f.querySelector<HTMLElement>('[data-v3-state]');try{await rpc('submit_public_litlab_contribution_feedback',{p_publication_id:id,p_feedback_token:uid(FT),p_helpful:String(d.get('helpful'))==='true',p_comment:String(d.get('comment')||'')},false);if(s){s.textContent='Thanks — feedback saved.';s.dataset.state='success'}setTimeout(()=>void loadShowcase(),300)}catch(err){if(s){s.textContent=err instanceof Error?err.message:'Could not save feedback.';s.dataset.state='error'}}}
async function openPublic(b:HTMLButtonElement){const id=b.dataset.v3OpenPublic||'',url=b.dataset.publicUrl||'';if(!id||!url)return;window.open(url,'_blank','noopener,noreferrer');try{await rpc('record_public_litlab_contribution_open',{p_publication_id:id,p_visitor_token:uid(VT)},false)}catch{}}

function notifButton(){const menu=document.querySelector<HTMLElement>('.litlab-account-menu');if(!menu||!tok())return null;let b=menu.querySelector<HTMLButtonElement>('[data-v3-notifications]');if(!b){b=document.createElement('button');b.type='button';b.className='litlab-admin-menu-entry ll-v3-notification-entry';b.dataset.v3Notifications='true';b.addEventListener('click',x=>{x.stopPropagation();openNotices()});const out=menu.querySelector('.litlab-signout');out?menu.insertBefore(b,out):menu.appendChild(b)}const n=noticeRows.filter(x=>x.is_unread).length;b.classList.toggle('has-unread',n>0);b.innerHTML=`<span>${n?'●':'✦'}</span><div><b>Contributor updates</b><small>${n?`${n} unread update${n===1?'':'s'}`:'Briefs, assignments & publication'}</small></div><i>›</i>`;return b}
function closeNotices(){noticePanel?.remove();noticePanel=null}
function openNotices(){closeNotices();noticePanel=document.createElement('div');noticePanel.className='ll-v3-notification-overlay';noticePanel.innerHTML=`<section class="ll-v3-notification-panel" role="dialog" aria-modal="true"><header><div><span>LITLAB CONTRIBUTOR PROGRAM</span><h2>Updates</h2></div><button type="button" data-v3-close-notices>×</button></header><div class="ll-v3-notification-list">${noticeRows.length?noticeRows.map(x=>`<button type="button" data-v3-notice="${e(x.id)}" data-action="${e(x.action_hash||'#contribute')}" class="${x.is_unread?'is-unread':''}"><i>${x.is_unread?'●':'✓'}</i><div><b>${e(x.title)}</b><p>${e(x.body)}</p><small>${e(stamp(x.created_at))}</small></div></button>`).join(''):'<div class="ll-v3-empty">No contributor-program updates yet.</div>'}</div>${noticeRows.some(x=>x.is_unread)?'<button class="ll-v3-mark-all" type="button" data-v3-mark-all>Mark all as read</button>':''}</section>`;noticePanel.addEventListener('click',x=>{if(x.target===noticePanel)closeNotices()});document.body.appendChild(noticePanel);requestAnimationFrame(()=>noticePanel?.classList.add('is-open'))}
async function loadNotices(){if(!tok())return;try{noticeRows=await rpc<Row[]>('get_my_litlab_contributor_program_notifications',{p_limit:30});notifButton()}catch{}}
async function markNotice(id:string|null){try{await rpc('mark_my_litlab_contributor_program_notification_read',{p_notification_id:id});await loadNotices()}catch{}}
function pollNotices(){clearTimeout(noticeTimer);noticeTimer=window.setTimeout(async()=>{if(!document.hidden&&navigator.onLine)await loadNotices();pollNotices()},30000)}

document.addEventListener('click',x=>{const t=x.target instanceof Element?x.target:null;if(!t)return;const j=t.closest<HTMLButtonElement>('[data-v3-jump]');if(j){jump(j.dataset.v3Jump||'');return}const o=t.closest<HTMLButtonElement>('[data-v3-onboard]');if(o){void onboard(o,o.dataset.v3Onboard||'student');return}const b=t.closest<HTMLButtonElement>('[data-v3-accept-brief]');if(b){void acceptBrief(b,b.dataset.v3AcceptBrief||'');return}const d=t.closest<HTMLButtonElement>('[data-v3-delete-reflection]');if(d){void delReflection(d.dataset.v3DeleteReflection||'');return}const p=t.closest<HTMLButtonElement>('[data-v3-open-public]');if(p){void openPublic(p);return}if(t.closest('[data-v3-close-notices]')){closeNotices();return}const n=t.closest<HTMLButtonElement>('[data-v3-notice]');if(n){void markNotice(n.dataset.v3Notice||'');closeNotices();location.hash=(n.dataset.action||'#contribute').replace(/^#/,'');return}if(t.closest('[data-v3-mark-all]')){void markNotice(null);closeNotices();return}if(t.closest('.litlab-account-trigger'))setTimeout(()=>{notifButton();void loadNotices()},80)},true);
document.addEventListener('submit',x=>{const f=x.target instanceof HTMLFormElement?x.target:null;if(!f)return;const r=f.dataset.v3Reflection;if(r){x.preventDefault();x.stopPropagation();void saveReflection(f,r);return}const ev=f.dataset.v3Evidence;if(ev){x.preventDefault();x.stopPropagation();void saveEvidence(f,ev);return}if(f.matches('[data-v3-verify]')){x.preventDefault();void verify(f);return}const fb=f.dataset.v3Feedback;if(fb){x.preventDefault();void feedback(f,fb)}},true);
window.addEventListener('litlab:contributor-workspace-data',x=>{const d=(x as CustomEvent<Row>).detail||{};ws=Array.isArray(d.workspaces)?d.workspaces:ws;selected=d.selectedId||selected;schedule()});
window.addEventListener('litlab:contributor-workspace-updated',()=>setTimeout(schedule,220));
window.addEventListener('hashchange',()=>{closeNotices();setTimeout(()=>{mountPublic();schedule();void loadNotices()},100)});
window.addEventListener('focus',()=>{void loadNotices();if(route()==='contribute')schedule()});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){void loadNotices();if(route()==='contribute')schedule()}});
function start(){mountPublic();schedule();void loadNotices();pollNotices()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
export {};
