export type Status='verified'|'demo'|'coming';
export type Guide={slug:string;title:string;kicker:string;description:string;status:Status;minutes:number;sections:{title:string;body:string;tip?:string}[]};
export const guides:Guide[]=[
 {slug:'start',title:'Start Here',kicker:'Your first bearing',description:'A calm introduction to the language, habits and map of DP English.',status:'verified',minutes:8,sections:[
  {title:'You are not behind',body:'DP English can sound like a wall of unfamiliar terms at first. You do not need to learn them all today. Begin by noticing how a text creates meaning, then give what you notice a clear name.',tip:'Read like a curious detective: What choice did the creator make—and what does it do?'},
  {title:'The big picture',body:'Across the course, you will read closely, compare works, discuss ideas and explain how choices shape meaning. The formats may change, but the core movement stays familiar: notice, interpret, support, connect.'},
  {title:'A useful weekly rhythm',body:'Keep a small evidence bank. After reading, save one striking choice, one short quotation or detail, and one question. Ten focused minutes repeated often beats one giant catch-up session.'},
  {title:'Your next step',body:'Use the Compass below. Choose what feels most confusing—not what sounds most impressive. Each guide is designed to be explored in small pieces.'}
 ]},
 {slug:'paper-1',title:'Paper 1',kicker:'Guided analysis',description:'A ready-to-fill guide for reading, planning and analytical writing.',status:'demo',minutes:12,sections:[{title:'Guide under review',body:'This layout demonstrates how the final Paper 1 guide will work. Course-specific requirements will be added after research and review.',tip:'Demo prompt: identify one visible choice, then explain the effect it creates.'},{title:'The analysis loop',body:'Notice a choice. Name it precisely. Explain its effect. Connect that effect to the text’s larger purpose. This is a transferable practice model, not an official assessment formula.'}]},
 {slug:'paper-2',title:'Paper 2',kicker:'Connections between works',description:'A structured home for comparison planning and practice.',status:'coming',minutes:10,sections:[]},
 {slug:'io',title:'Individual Oral',kicker:'Ideas into a clear line',description:'A future guide for organizing and communicating an interpretation.',status:'coming',minutes:10,sections:[]},
 {slug:'ee',title:'Extended Essay',kicker:'A longer investigation',description:'A future workspace for questions, research and reflection.',status:'coming',minutes:10,sections:[]},
 {slug:'works',title:'Books & Works',kicker:'Your work library',description:'Flexible templates for building useful, connected work profiles.',status:'demo',minutes:6,sections:[{title:'Add your first work',body:'Each future profile can hold characters, themes, context, authorial choices, important moments, connections and personal study prompts.'}]}
];
export const glossary=[['Analysis','Explaining how choices create meaning—not simply identifying them.'],['Authorial choice','A deliberate decision in how a text is created or presented.'],['Context','Circumstances surrounding the creation, setting or reception of a text.'],['Evidence','A specific textual detail used to support an interpretation.'],['Global issue','A significant concern considered across contexts; verify current course guidance before using this term for assessment planning.'],['Motif','A recurring element that helps develop meaning.'],['Thesis','A focused, arguable statement that gives an analysis direction.'],['Tone','The attitude or feeling communicated through choices in a text.']];
export const tips=['Name the choice before you explain the effect.','A strong question is evidence of learning, not confusion.','Compare ideas and methods—not just plots.','Save small insights while they are fresh.'];
