import './essay-workspace.css';

const URL='https://qdqseajcukfdbfikjptu.supabase.co';
const KEY='sb_publishable_FNjxRB0rtl5TwnC8NtCDGg_RHEpSZLN';
const SESSION='litlabSupabaseSession';
type Kind='ee'|'hl';
type Sess={access_token:string;refresh_token:string};
type User={id:string};
type Para={heading:string;claim:string;purpose:string};
type Evidence={text:string;ref:string;analysis:string};
type Deadline={label:string;date:string;done:boolean};
type State={focus:string;thesis:string;words:number;paras:Para[];evidence:Evidence[];deadlines:Deadline[];checks:boolean[]};
type Config={kind:Kind;route:string;target:string;name:string;focus:string;max:number;min?:number;checks:string[];deadlines:string[]};

const configs:Config[]=[
 {kind:'ee',route:'ee',target:'#ee-plan',name:'Extended Essay',focus:'Research Question',max:4000,checks:['Research Question is focused and answerable within 4,000 words.','Every major section advances the Research Question.','Primary-text analysis dominates over summary.','Evidence and borrowed ideas are referenced consistently.','Evaluation appears throughout the argument.','Word count is within the 4,000-word maximum.','Supervisor feedback has been considered and acted on.','Bibliography/references are complete.','Final draft has been proofread.'],deadlines:['Research Question finalized','Full outline ready','First full draft','Supervisor feedback revision','Final submission']},
 {kind:'hl',route:'hl-essay',target:'#hl-structure',name:'HL Essay',focus:'Line of Inquiry',min:1200,max:1500,checks:['Line of Inquiry is focused and analytical.','Every paragraph advances the Line of Inquiry.','Each paragraph uses precise textual evidence.','Authorial choices are analyzed for effect and meaning.','Analysis dominates over description or summary.','References/citations are consistent.','Academic register is clear and controlled.','Draft is within 1,200–1,500 words.','Conclusion synthesizes the inquiry.'],deadlines:['Line of Inquiry finalized','Paragraph plan complete','Evidence bank ready','First full draft','Final submission']}
];
const esc=(v:string)=>v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));
const route=()=>location.hash.replace(/^#/,'').split('?')[0].split('#')[0].toLowerCase()||'home';
const sess=():Sess|null=>{try{const s=JSON.parse(localStorage.getItem(SESSION)||'null');return s?.access_token&&s?.refresh_token?s:null}catch{return null}};
const headers=(token:string,extra:Record<string,string>={})=>({apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...extra});
function blank(c:Config):State{return{focus:'',thesis:'',words:0,paras:Array.from({length:c.kind==='ee'?6:5},(_,i)=>({heading:i===0?'Introduction':i===(c.kind==='ee'?5:4)?'Conclusion':`Body ${i}`,claim:'',purpose:''})),evidence:Array.from({length:4},()=>({text:'',ref:'',analysis:''})),deadlines:c.deadlines.map(label=>({label,date:'',done:false})),checks:Array(c.checks.length).fill(false)}}
function norm(c:Config,r:Partial<State>):State{const b=blank(c);return{focus:String(r.focus||''),thesis:String(r.thesis||''),words:Math.max(0,Number(r.words)||0),paras:Array.isArray(r.paras)&&r.paras.length?r.paras.map((x,i)=>({heading:String(x.heading||`Paragraph ${i+1}`),claim:String(x.claim||''),purpose:String(x.purpose||'')})):b.paras,evidence:Array.isArray(r.evidence)&&r.evidence.length?r.evidence.map(x=>({text:String(x.text||''),ref:String(x.ref||''),analysis:String(x.analysis||'')})):b.evidence,deadlines:Array.isArray(r.deadlines)&&r.deadlines.length?r.deadlines.map((x,i)=>({label:String(x.label||c.deadlines[i]||'Deadline'),date:String(x.date||''),done:Boolean(x.done)})):b.deadlines,checks:Array.from({length:c.checks.length},(_,i)=>Boolean(r.checks?.[i]))}}
async function user(s:Sess){const r=await fetch(`${URL}/auth/v1/user`,{headers:headers(s.access_token)});return r.ok?await r.json() as User:null}
async function load(s:Sess,u:User,c:Config){const r=await fetch(`${URL}/rest/v1/litlab_essay_workspaces?select=data&user_id=eq.${encodeURIComponent(u.id)}&essay_type=eq.${c.kind}&limit=1`,{headers:headers(s.access_token)});if(!r.ok)throw Error();const rows=await r.json() as {data:Partial<State>}[];return norm(c,rows[0]?.data||{})}
async function save(s:Sess,u:User,c:Config,state:State){const r=await fetch(`${URL}/rest/v1/litlab_essay_workspaces?on_conflict=user_id,essay_type`,{method:'POST',headers:headers(s.access_token,{Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify({user_id:u.id,essay_type:c.kind,data:state})});if(!r.ok)throw Error()}
function signIn(n=0){if(document.querySelector('[data-auth-modal]'))return;const b=document.querySelector<HTMLButtonElement>('[data-auth-open]');if(b)b.click();else if(n<8)setTimeout(()=>signIn(n+1),100)}
function wordText(c:Config,n:number){if(c.kind==='ee')return n>4000?`${n.toLocaleString()} words • ${n-4000} over maximum`:`${n.toLocaleString()} / 4,000 words`;if(n<1200)return `${n.toLocaleString()} words • ${1200-n} to minimum`;if(n<=1500)return `${n.toLocaleString()} words • within range`;return `${n.toLocaleString()} words • ${n-1500} over range`}

function mount(c:Config){
 if(route()!==c.route)return;const target=document.querySelector<HTMLElement>(c.target);if(!target||target.querySelector(`[data-essay-workspace="${c.kind}"]`))return;
 const wrap=document.createElement('div');wrap.className='essay-ws';wrap.dataset.essayWorkspace=c.kind;wrap.innerHTML=`<div class="essay-ws-feature"><div><span>✦ SIGNED-IN WORKSPACE</span><h3>Build your ${c.name} Workspace.</h3><p>Keep your ${c.focus.toLowerCase()}, working thesis, paragraph plan, evidence, word count, checklist, and deadlines together while you use this guide.</p><div class="essay-ws-flow"><b>${c.kind==='ee'?'RQ':'LINE OF INQUIRY'}</b><i>→</i><b>THESIS</b><i>→</i><b>PLAN</b><i>→</i><b>EVIDENCE</b><i>→</i><strong>DRAFT</strong></div><small>Saved securely to your LitLab account • available across devices</small></div><button class="btn primary" type="button" data-ws-open>${sess()?'Open Essay Workspace →':'Sign in to build →'}</button></div><div class="essay-ws-shell" data-ws-shell hidden></div>`;target.append(wrap);
 const shell=wrap.querySelector<HTMLElement>('[data-ws-shell]')!,open=wrap.querySelector<HTMLButtonElement>('[data-ws-open]')!;let state=blank(c),active:Sess|null=null,u:User|null=null,timer=0;
 const status=(t:string)=>shell.querySelectorAll<HTMLElement>('[data-ws-status]').forEach(x=>x.textContent=t);
 const queue=()=>{if(!active||!u)return;status('Saving to your LitLab account…');clearTimeout(timer);timer=window.setTimeout(async()=>{try{await save(active!,u!,c,state);status('Synced to your LitLab account ✓')}catch{status('Could not sync • try reopening the workspace')}},600)};
 const progress=()=>{const meter=shell.querySelector<HTMLElement>('[data-ws-meter]'),words=shell.querySelector<HTMLElement>('[data-ws-word-label]'),checks=shell.querySelector<HTMLElement>('[data-ws-check-label]');if(meter){meter.style.width=`${Math.min(100,state.words/c.max*100)}%`;meter.classList.toggle('over',state.words>c.max);meter.classList.toggle('in-range',c.kind==='hl'&&state.words>=1200&&state.words<=1500)}if(words)words.textContent=wordText(c,state.words);if(checks)checks.textContent=`${state.checks.filter(Boolean).length}/${c.checks.length} complete`};
 const collect=()=>{shell.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-core]').forEach(x=>{if(x.dataset.core==='focus')state.focus=x.value;if(x.dataset.core==='thesis')state.thesis=x.value;if(x.dataset.core==='words')state.words=Math.max(0,Number(x.value)||0)});shell.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-para]').forEach(x=>{const i=Number(x.dataset.para),f=x.dataset.field as keyof Para;if(state.paras[i]&&f)state.paras[i][f]=x.value});shell.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-evidence]').forEach(x=>{const i=Number(x.dataset.evidence),f=x.dataset.field as keyof Evidence;if(state.evidence[i]&&f)state.evidence[i][f]=x.value});shell.querySelectorAll<HTMLInputElement>('[data-deadline]').forEach(x=>{const i=Number(x.dataset.deadline),f=x.dataset.field;if(!state.deadlines[i])return;if(f==='label')state.deadlines[i].label=x.value;if(f==='date')state.deadlines[i].date=x.value;if(f==='done')state.deadlines[i].done=x.checked});shell.querySelectorAll<HTMLInputElement>('[data-check]').forEach(x=>state.checks[Number(x.dataset.check)]=x.checked);progress();queue()};
 const render=()=>{const done=state.checks.filter(Boolean).length;shell.innerHTML=`<div class="essay-ws-top"><div><span>${c.kind==='ee'?'EXTENDED ESSAY':'HL ESSAY'} • WORKSPACE</span><h3>${c.name} Workspace</h3><p>Plan and track the essay without leaving the guide.</p></div><b data-ws-status>Synced to your LitLab account</b></div><div class="essay-ws-core"><label><span>${c.focus}</span><textarea data-core="focus" placeholder="Your current focused ${c.focus.toLowerCase()}…">${esc(state.focus)}</textarea></label><label><span>Working thesis</span><textarea data-core="thesis" placeholder="Your current answer/argument — expect it to evolve.">${esc(state.thesis)}</textarea></label></div>
 <section><div class="essay-ws-head"><div><em>01</em><div><b>Paragraph / section plan</b><p>Give every part of the essay a clear argumentative job.</p></div></div><button type="button" data-add-para>+ Add paragraph</button></div><div class="essay-ws-list">${state.paras.map((p,i)=>`<article><strong>${String(i+1).padStart(2,'0')}</strong><div><label><span>Heading</span><input data-para="${i}" data-field="heading" value="${esc(p.heading)}"></label><label><span>Claim / sub-argument</span><textarea data-para="${i}" data-field="claim" placeholder="What does this section argue?">${esc(p.claim)}</textarea></label><label><span>Purpose in the essay</span><textarea data-para="${i}" data-field="purpose" placeholder="How does it advance or complicate the inquiry?">${esc(p.purpose)}</textarea></label></div><button class="remove" data-remove-para="${i}" type="button">×</button></article>`).join('')}</div></section>
 <section><div class="essay-ws-head"><div><em>02</em><div><b>Evidence bank</b><p>Save the evidence and why it matters before drafting around it.</p></div></div><button type="button" data-add-evidence>+ Add evidence</button></div><div class="essay-ws-list evidence">${state.evidence.map((e,i)=>`<article><strong>${String(i+1).padStart(2,'0')}</strong><div><label><span>Evidence / quotation / source idea</span><textarea data-evidence="${i}" data-field="text">${esc(e.text)}</textarea></label><label><span>Page / citation / source</span><input data-evidence="${i}" data-field="ref" value="${esc(e.ref)}" placeholder="p. 84 / citation note"></label><label><span>Analysis / why it matters</span><textarea data-evidence="${i}" data-field="analysis">${esc(e.analysis)}</textarea></label></div><button class="remove" data-remove-evidence="${i}" type="button">×</button></article>`).join('')}</div></section>
 <section><div class="essay-ws-head"><div><em>03</em><div><b>Draft progress</b><p>Track the word count and the checkpoints still needing attention.</p></div></div></div><div class="essay-ws-progress"><article class="word"><span>WORD COUNT</span><label><input type="number" min="0" data-core="words" value="${state.words}"><small>${c.kind==='ee'?'4,000-word maximum':'1,200–1,500 words'}</small></label><div><i data-ws-meter style="width:${Math.min(100,state.words/c.max*100)}%"></i></div><b data-ws-word-label>${esc(wordText(c,state.words))}</b></article><article class="checks"><header><span>WORKSPACE CHECKLIST</span><b data-ws-check-label>${done}/${c.checks.length} complete</b></header>${c.checks.map((x,i)=>`<label><input type="checkbox" data-check="${i}" ${state.checks[i]?'checked':''}><i></i><span>${esc(x)}</span></label>`).join('')}</article></div></section>
 <section><div class="essay-ws-head"><div><em>04</em><div><b>Deadlines</b><p>Turn the essay into milestones instead of one final date.</p></div></div><button type="button" data-add-deadline>+ Add deadline</button></div><div class="essay-ws-deadlines">${state.deadlines.map((d,i)=>`<article class="${d.done?'done':''}"><label><input type="checkbox" data-deadline="${i}" data-field="done" ${d.done?'checked':''}><i></i></label><input data-deadline="${i}" data-field="label" value="${esc(d.label)}"><input type="date" data-deadline="${i}" data-field="date" value="${esc(d.date)}"><button class="remove" data-remove-deadline="${i}" type="button">×</button></article>`).join('')}</div></section><footer><span data-ws-status>Synced to your LitLab account</span><button type="button" data-ws-close>Close workspace</button><button type="button" data-ws-clear>Clear workspace</button></footer>`;wire();progress()};
 const wire=()=>{shell.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input,textarea').forEach(x=>x.addEventListener('input',collect));shell.querySelectorAll<HTMLInputElement>('input[type=checkbox]').forEach(x=>x.addEventListener('change',collect));shell.querySelector('[data-add-para]')?.addEventListener('click',()=>{state.paras.push({heading:`Paragraph ${state.paras.length+1}`,claim:'',purpose:''});render();queue()});shell.querySelectorAll<HTMLElement>('[data-remove-para]').forEach(b=>b.addEventListener('click',()=>{if(state.paras.length>1){state.paras.splice(Number(b.dataset.removePara),1);render();queue()}}));shell.querySelector('[data-add-evidence]')?.addEventListener('click',()=>{state.evidence.push({text:'',ref:'',analysis:''});render();queue()});shell.querySelectorAll<HTMLElement>('[data-remove-evidence]').forEach(b=>b.addEventListener('click',()=>{state.evidence.splice(Number(b.dataset.removeEvidence),1);render();queue()}));shell.querySelector('[data-add-deadline]')?.addEventListener('click',()=>{state.deadlines.push({label:'New deadline',date:'',done:false});render();queue()});shell.querySelectorAll<HTMLElement>('[data-remove-deadline]').forEach(b=>b.addEventListener('click',()=>{state.deadlines.splice(Number(b.dataset.removeDeadline),1);render();queue()}));shell.querySelector('[data-ws-close]')?.addEventListener('click',()=>{shell.hidden=true;open.textContent='Open Essay Workspace →'});shell.querySelector('[data-ws-clear]')?.addEventListener('click',()=>{if(confirm(`Clear your saved ${c.name} Workspace?`)){state=blank(c);render();queue()}})};
 open.addEventListener('click',async()=>{const s=sess();if(!s){signIn();return}open.disabled=true;open.textContent='Loading workspace…';try{const who=await user(s);if(!who){open.textContent='Sign in to build →';signIn();return}active=s;u=who;state=await load(s,who,c);render();shell.hidden=false;open.textContent='Workspace open ✓';shell.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}catch{open.textContent='Try opening again'}finally{open.disabled=false}});
 window.addEventListener('focus',()=>open.textContent=sess()?'Open Essay Workspace →':'Sign in to build →');
}
let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;configs.forEach(mount)})}window.addEventListener('hashchange',schedule);const root=document.getElementById('root');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();