import './evidence-bank.css';
import {bookProfiles} from './books-data';

const SUPABASE_URL='https://qdqseajcukfdbfikjptu.supabase.co';
const SUPABASE_KEY='sb_publishable_FNjxRB0rtl5TwnC8NtCDGg_RHEpSZLN';
const SESSION_KEY='litlabSupabaseSession';

type Session={access_token:string;refresh_token:string};
type User={id:string;email?:string};
type EvidenceRow={id:string;user_id:string;book_slug:string;book_title:string;quote_text:string;page_reference:string|null;effect_text:string|null;analysis_text:string|null;notes_text:string|null;created_at:string;updated_at:string};

const esc=(v:string)=>v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));
const route=()=>location.hash.slice(1).split('#')[0]||'home';
const session=():Session|null=>{try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');return s?.access_token&&s?.refresh_token?s:null}catch{return null}};
const headers=(token:string,extra:Record<string,string>={})=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...extra});

async function currentUser(s:Session){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(s.access_token)});if(!r.ok)return null;return await r.json() as User}
function requireSignIn(){document.querySelector<HTMLButtonElement>('[data-auth-open]')?.click()}

async function fetchRows(s:Session){const r=await fetch(`${SUPABASE_URL}/rest/v1/litlab_evidence_bank?select=*&order=updated_at.desc`,{headers:headers(s.access_token)});if(!r.ok)throw new Error('Could not load your evidence bank.');return await r.json() as EvidenceRow[]}
async function createRow(s:Session,user:User,data:Omit<EvidenceRow,'id'|'user_id'|'created_at'|'updated_at'>){const r=await fetch(`${SUPABASE_URL}/rest/v1/litlab_evidence_bank`,{method:'POST',headers:headers(s.access_token,{Prefer:'return=representation'}),body:JSON.stringify({...data,user_id:user.id})});if(!r.ok)throw new Error('Could not save this evidence.');return (await r.json() as EvidenceRow[])[0]}
async function updateRow(s:Session,id:string,data:Partial<EvidenceRow>){const r=await fetch(`${SUPABASE_URL}/rest/v1/litlab_evidence_bank?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:headers(s.access_token,{Prefer:'return=representation'}),body:JSON.stringify(data)});if(!r.ok)throw new Error('Could not update this evidence.');return (await r.json() as EvidenceRow[])[0]}
async function deleteRow(s:Session,id:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/litlab_evidence_bank?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:headers(s.access_token)});if(!r.ok)throw new Error('Could not delete this evidence.')}

function currentBook(){const title=document.querySelector<HTMLElement>('.books-profile-page h1')?.textContent?.trim();return bookProfiles.find(b=>b.title===title)||null}

function addLaunchers(){if(route()!=='books')return;const page=document.querySelector<HTMLElement>('.books-library-page,.books-profile-page');if(!page)return;
  if(page.classList.contains('books-library-page')){const head=page.querySelector('.books-library-head');if(head&&!page.querySelector('[data-evidence-open]')){const b=document.createElement('button');b.type='button';b.className='btn primary evidence-launch';b.dataset.evidenceOpen='true';b.innerHTML='Evidence Bank <span>→</span>';head.append(b)}}
  if(page.classList.contains('books-profile-page')){const actions=page.querySelector('.book-profile-actions');if(actions&&!page.querySelector('[data-evidence-open]')){const b=document.createElement('button');b.type='button';b.className='btn secondary evidence-launch';b.dataset.evidenceOpen='true';b.textContent='Evidence Bank';actions.append(b)}}
}

function field(label:string,name:string,value='',area=false,placeholder=''){return `<label class="evidence-field"><span>${label}</span>${area?`<textarea name="${name}" placeholder="${esc(placeholder)}">${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}" placeholder="${esc(placeholder)}"/>`}</label>`}

async function openBank(){const s=session();if(!s){requireSignIn();return}const user=await currentUser(s);if(!user){requireSignIn();return}
  document.querySelector('[data-evidence-modal]')?.remove();
  const modal=document.createElement('div');modal.className='evidence-modal';modal.dataset.evidenceModal='true';modal.innerHTML=`<div class="evidence-shell" role="dialog" aria-modal="true" aria-labelledby="evidence-title"><header><div><span>BOOKS • MY LITLAB</span><h2 id="evidence-title">Evidence Bank</h2><p>Save quotations and evidence to your LitLab account and reopen them on any device.</p></div><button type="button" data-evidence-close aria-label="Close">×</button></header><div class="evidence-toolbar"><label><span>Filter by book</span><select data-evidence-filter><option value="">All books</option>${bookProfiles.map(b=>`<option value="${esc(b.id)}">${esc(b.title)}</option>`).join('')}</select></label><button class="btn primary" type="button" data-evidence-add>+ Add evidence</button></div><div data-evidence-status class="evidence-status">Loading your evidence…</div><div data-evidence-list></div></div>`;
  document.body.append(modal);modal.addEventListener('pointerdown',e=>{if(e.target===modal)modal.remove()});modal.querySelector('[data-evidence-close]')?.addEventListener('click',()=>modal.remove());
  let rows:EvidenceRow[]=[];let filter='';const list=modal.querySelector<HTMLElement>('[data-evidence-list]')!;const status=modal.querySelector<HTMLElement>('[data-evidence-status]')!;
  const render=()=>{const shown=rows.filter(r=>!filter||r.book_slug===filter);status.textContent=rows.length?`${rows.length} saved evidence ${rows.length===1?'entry':'entries'} • synced to your account`:'No evidence saved yet.';list.innerHTML=shown.length?`<div class="evidence-table-wrap"><table class="evidence-table"><thead><tr><th>Book</th><th>Quote / evidence</th><th>Page</th><th>Effect</th><th>Analysis</th><th>Notes</th><th></th></tr></thead><tbody>${shown.map(r=>`<tr><td data-label="Book"><b>${esc(r.book_title)}</b></td><td data-label="Quote / evidence"><p>${esc(r.quote_text)}</p></td><td data-label="Page">${esc(r.page_reference||'—')}</td><td data-label="Effect"><p>${esc(r.effect_text||'—')}</p></td><td data-label="Analysis"><p>${esc(r.analysis_text||'—')}</p></td><td data-label="Notes"><p>${esc(r.notes_text||'—')}</p></td><td class="evidence-row-actions"><button data-evidence-edit="${r.id}" type="button">Edit</button><button data-evidence-delete="${r.id}" type="button">Delete</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="evidence-empty"><b>${rows.length?'No entries match this book.':'Start your evidence bank.'}</b><p>${rows.length?'Choose another book filter or add new evidence.':'Save a quotation or precise evidence point, then record its effect and your analysis.'}</p></div>`;wireRows()};
  const editor=(existing?:EvidenceRow)=>{const chosen=currentBook();const wrap=document.createElement('div');wrap.className='evidence-editor';wrap.innerHTML=`<form><div class="evidence-editor-head"><div><span>${existing?'EDIT ENTRY':'NEW ENTRY'}</span><h3>${existing?'Update your evidence':'Add evidence'}</h3></div><button type="button" data-editor-close>×</button></div><label class="evidence-field"><span>Book</span><select name="book">${bookProfiles.map(b=>`<option value="${esc(b.id)}" ${(existing?.book_slug===b.id||(!existing&&chosen?.id===b.id))?'selected':''}>${esc(b.title)}</option>`).join('')}</select></label>${field('Quote / evidence','quote',existing?.quote_text||'',true,'Paste a short quotation or describe the precise evidence point…')}${field('Page','page',existing?.page_reference||'',false,'e.g. 82, Ch. 6, panel 3')}${field('Effect','effect',existing?.effect_text||'',true,'What effect does this choice create?')}${field('Analysis','analysis',existing?.analysis_text||'',true,'How does the evidence create meaning?')}${field('Notes','notes',existing?.notes_text||'',true,'Themes, Paper 2 link, class notes, interpretation…')}<div class="evidence-editor-actions"><button type="button" class="btn secondary" data-editor-cancel>Cancel</button><button type="submit" class="btn primary">${existing?'Save changes':'Save evidence'}</button></div><div class="evidence-editor-error" data-editor-error></div></form>`;modal.querySelector('.evidence-shell')?.append(wrap);const close=()=>wrap.remove();wrap.querySelector('[data-editor-close]')?.addEventListener('click',close);wrap.querySelector('[data-editor-cancel]')?.addEventListener('click',close);wrap.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;const fd=new FormData(form);const book=bookProfiles.find(b=>b.id===String(fd.get('book')));const quote=String(fd.get('quote')||'').trim();const err=wrap.querySelector<HTMLElement>('[data-editor-error]')!;if(!book||!quote){err.textContent='Choose a book and add a quote or evidence point.';return}const payload={book_slug:book.id,book_title:book.title,quote_text:quote,page_reference:String(fd.get('page')||'').trim()||null,effect_text:String(fd.get('effect')||'').trim()||null,analysis_text:String(fd.get('analysis')||'').trim()||null,notes_text:String(fd.get('notes')||'').trim()||null};try{const saved=existing?await updateRow(s,existing.id,payload):await createRow(s,user,payload as any);rows=existing?rows.map(r=>r.id===saved.id?saved:r):[saved,...rows];render();close()}catch(error){err.textContent=error instanceof Error?error.message:'Could not save this evidence.'}})};
  const wireRows=()=>{list.querySelectorAll<HTMLButtonElement>('[data-evidence-edit]').forEach(b=>b.addEventListener('click',()=>{const row=rows.find(r=>r.id===b.dataset.evidenceEdit);if(row)editor(row)}));list.querySelectorAll<HTMLButtonElement>('[data-evidence-delete]').forEach(b=>b.addEventListener('click',async()=>{const row=rows.find(r=>r.id===b.dataset.evidenceDelete);if(!row||!confirm('Delete this evidence entry?'))return;try{await deleteRow(s,row.id);rows=rows.filter(r=>r.id!==row.id);render()}catch(error){status.textContent=error instanceof Error?error.message:'Could not delete this evidence.'}}))};
  modal.querySelector('[data-evidence-add]')?.addEventListener('click',()=>editor());modal.querySelector<HTMLSelectElement>('[data-evidence-filter]')?.addEventListener('change',e=>{filter=(e.currentTarget as HTMLSelectElement).value;render()});
  try{rows=await fetchRows(s);render()}catch(error){status.textContent=error instanceof Error?error.message:'Could not load your evidence bank.'}
}

document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target.closest('[data-evidence-open]'):null;if(t){e.preventDefault();void openBank()}});
const observer=new MutationObserver(()=>addLaunchers());observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>requestAnimationFrame(addLaunchers));requestAnimationFrame(addLaunchers);
