import {siteDocs,type SiteDoc} from './tutor-site-knowledge';
import {hlChecklist,hlConcepts,hlCriteria,hlMistakes,hlNarrowingExamples,hlPractice} from './hl-essay-data';

if(!siteDocs.some(doc=>doc.id.startsWith('hl-essay-'))){
  const add=(id:string,title:string,body:string,keywords:string[],priority=2)=>{
    const doc:SiteDoc={id:`hl-essay-${id}`,title,body,keywords:[title,'HL Essay','HLE',...keywords],route:'hl-essay',category:'HL Essay',action:{label:'Open HL Essay guide',route:'hl-essay'},priority};
    siteDocs.push(doc);
  };

  add('overview','HL Essay overview','The HL Essay is an additional formal coursework component for HL students only. It is a 1,200–1,500 word essay built around a student-developed line of inquiry connected to one work or body of work studied during the course. It is worth 20 marks across four criteria of 5 marks each and has no fixed prompt. Confirm the exact current criteria wording, weighting, and school procedures with your teacher or current official guide.',['1200','1500','word count','20 marks','hl only','coursework','no fixed prompt','format'],4);
  add('work','Choosing an HL Essay work','Choose one work or body of work already studied in class that can sustain several distinct analytical points. In Language and Literature, the material can be literary or non-literary if it was genuinely studied in class, and a body of work can be appropriate when the inquiry remains focused. A work already used for the Individual Oral should not be reused for the HL Essay; confirm the current assessment-reuse rule with your teacher or current course guide before finalizing a choice.',['choose work','body of work','io reuse','individual oral','non literary','eligibility'],3);
  add('inquiry','HL Essay line of inquiry',`A line of inquiry is a focused analytical question or angle connected to the chosen work. It should naturally lead toward analysis of how the work is constructed, not just what it is about. Useful starting concepts are ${hlConcepts.join(', ')}. Narrow broad themes into specific patterns, tensions, authorial choices, or contexts that can be explored deeply within the word limit.`,['line of inquiry','loi','question','narrow topic','concepts','identity','perspective','representation'],4);
  hlNarrowingExamples.forEach((item,index)=>add(`narrow-${index+1}`,`${item.work} — narrowing an HL Essay inquiry`,`Too broad: ${item.broad} Narrower: ${item.narrower} Focused: ${item.focused} Course-concept starting point: ${item.concept}.`,[item.work,item.concept,'narrowing example','focused inquiry'],3));
  add('research','HL Essay research and preparation','Close, repeated reading of the primary work is the foundation. Build an evidence bank of moments and quotations that directly answer the line of inquiry. Secondary sources are optional and should be used sparingly when they genuinely sharpen your own close analysis rather than replacing it.',['research','secondary sources','primary text','evidence bank','quotes','preparation'],3);
  add('structure','HL Essay structure','Use an efficient introduction that states the line of inquiry and direction, body paragraphs that each develop a distinct sub-point through specific evidence and sustained analysis, and a conclusion that synthesizes what the analysis has shown rather than repeating the introduction. At 1,200–1,500 words, every paragraph should clearly advance the inquiry.',['introduction','body paragraphs','conclusion','organization','organisation','development'],3);
  add('analysis','HL Essay analysis vs description','Analysis should dominate. For each paragraph, ask whether it explains an authorial choice, its effect and meaning, and how that advances the line of inquiry, or whether it mainly reports what happens. Plot summary uses scarce word count without doing the analytical work required by the essay.',['analysis','description','summary','authorial choice','effect','meaning','criterion b'],4);
  add('sustain','Sustaining the HL Essay line of inquiry','Return explicitly to the line of inquiry throughout the essay. Each paragraph should develop the argument rather than repeat the previous point. A tightly focused inquiry explored in depth is stronger than trying to cover too much ground thinly.',['sustain inquiry','focus','development','paragraph progression'],3);
  add('language','HL Essay register and language','Use a formal academic register and precise vocabulary. Clarity matters more than inflated wording. Proofread specifically for accuracy, sentence control, formality, and consistency because language is assessed directly under Criterion D.',['criterion d','register','formal language','academic language','proofread'],3);
  add('referencing','HL Essay referencing','Cite the primary work and any secondary material consistently using the citation style required by your school. Keep quotations short and purposeful so the word count is used for analysis rather than long copied passages.',['citations','referencing','bibliography','quotation','quotes'],3);
  add('teacher','Teacher role in the HL Essay','The teacher acts as an adviser who can guide the line of inquiry and general direction while the student remains substantially independent. Unlike the Extended Essay, there is no equivalent formal multi-session reflection process or reflection form. Use early check-ins to test whether the inquiry is viable and focused.',['teacher','supervision','adviser','feedback','reflection'],3);
  add('criteria','HL Essay assessment criteria',hlCriteria.map(item=>`${item.name}: ${item.marks} marks. ${item.focus}`).join(' '),['criteria','criterion a','criterion b','criterion c','criterion d','20 marks'],4);
  hlMistakes.forEach((item,index)=>add(`mistake-${index+1}`,`HL Essay mistake: ${item.title}`,`Why it hurts: ${item.why} Fix: ${item.fix} Example: ${item.example}`,[item.title,'common mistakes','avoid'],2));
  add('checklist','HL Essay checklist',hlChecklist.join(' '),['checklist','before submission','final check','proofread'],3);
  hlPractice.forEach((item,index)=>add(`practice-${index+1}`,`${item.work} — HL Essay inquiry practice`,`${item.inquiry} Course concept: ${item.concept}.`,[item.work,item.concept,'practice inquiry','example line of inquiry'],2));
  add('uncertainties','HL Essay details to confirm','Confirm the exact current wording of the four criteria descriptors, the precise current grade weighting, any school-specific draft/deadline/check-in process, and the current restriction on reusing works across assessment components with your teacher or current official guide. Do not invent uncertain requirements.',['confirm with teacher','weighting','criteria wording','school process','uncertain','official guide'],5);
}
