import './io-guide.css';
import{analysisDrills,chainExamples,choiceDrills,connectionDrills,continuations,deliveryTips,evaluationExamples,globalIssues,miniOrals,mistakes,transitionGroups}from'./io-data';

const route=()=>location.hash.slice(1).split('#')[0]||'home';
const sections=[
 ['io-overview','Overview'],['io-issue','Global issue'],['io-material','Extracts'],['io-analysis','Close analysis'],['io-wider','Wider work'],['io-connect','Connect issue'],['io-structure','Structure'],['io-transitions','Transitions'],['io-evaluation','Evaluation'],['io-delivery','Delivery'],['io-practice','Practice'],['io-mistakes','Mistakes']
] as const;

function esc(value:string){return value.replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]||ch))}
function list(items:string[]){return `<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}
function storedDone(){try{return JSON.parse(localStorage.getItem('litlabDone')||'[]') as string[]}catch{return[]}}
function markDone(){const d=storedDone();if(!d.includes('io'))d.push('io');localStorage.setItem('litlabDone',JSON.stringify(d))}

function quickReference(){return `<div class="io-format-card">
 <div class="io-format-head"><div><span>IO • QUICK REFERENCE</span><b>What the assessed session looks like</b></div><small>Language & Literature</small></div>
 <div class="io-format-grid">
  <div><span>FULL SESSION</span><strong>15 min</strong><p>10-minute uninterrupted oral + 5-minute teacher discussion.</p></div>
  <div><span>MATERIAL</span><strong>2 texts</strong><p>One literary work + one non-literary text/body of work connected by one global issue.</p></div>
  <div><span>SL WEIGHTING</span><strong>30%</strong><p>Working course reference from the supplied material.</p></div>
  <div><span>HL WEIGHTING</span><strong>20%</strong><p>Working course reference from the supplied material.</p></div>
 </div>
 <p class="io-format-note">The session is recorded and may be externally moderated. Confirm exact current criteria wording, note rules, and school procedures with your teacher/current course guide.</p>
 </div>`}

function template(){return `<section class="page io-guide-page" aria-labelledby="io-title">
 <div class="io-breadcrumb"><button type="button" data-go="home">Home</button><span>›</span><strong>Individual Oral</strong></div>
 <header class="io-hero">
  <div class="io-hero-copy"><span class="io-eyebrow">✦ INDIVIDUAL ORAL • LITLAB STUDY GUIDE</span><h1 id="io-title">IO</h1><h2>Turn close analysis into a spoken argument.</h2><p>Use one precise global issue to connect a literary work and a non-literary text. The goal is not to give a presentation about the issue itself — it is to explain <b>how each text constructs and represents it</b>.</p><div class="io-hero-actions"><button class="btn primary" type="button" data-scroll="io-issue">Start with the global issue →</button><button class="btn secondary" type="button" data-scroll="io-practice">Open Practice Lab</button></div></div>
  <div class="io-hero-model" aria-hidden="true"><div><span>LITERARY</span><i>↔</i><span>NON-LITERARY</span></div><b>AUTHORIAL CHOICE</b><em>→</em><b>EFFECT + MEANING</b><em>→</em><strong>GLOBAL ISSUE</strong><em>→</em><strong>WIDER SIGNIFICANCE</strong></div>
 </header>
 <nav class="io-nav" aria-label="IO guide sections"><span>ON THIS GUIDE</span>${sections.map(([id,label],i)=>`<button type="button" data-scroll="${id}" class="${i===0?'current':''}">${label}</button>`).join('')}</nav>

 <section id="io-overview" class="io-section" data-io-section><div class="io-section-head"><span>01 • OVERVIEW</span><h2>The global issue is the thread. The texts are the evidence.</h2><p>The oral asks you to sustain a coherent analysis of how content and form present one global issue across two different kinds of material.</p></div>${quickReference()}
 <div class="io-overview-grid"><article><span>WHAT YOU SHOW</span><h3>Close analysis.</h3><p>Move from observation to authorial choice, effect, meaning, evaluation, and a clear connection to the global issue.</p></article><article><span>WHAT YOU AVOID</span><h3>A speech about the issue.</h3><p>Do not spend ten minutes explaining climate change, inequality, migration, or another issue in general. Analyze the texts’ construction of it.</p></article><article><span>HOW TO PREPARE</span><h3>Know ideas, not a script.</h3><p>Prepare the argument, evidence, structure, and connections well enough to speak flexibly rather than memorizing every sentence.</p></article></div>
 <div class="io-core-chain"><span>OBSERVATION</span><i>→</i><span>CHOICE</span><i>→</i><span>EFFECT</span><i>→</i><span>MEANING</span><i>→</i><span>EVALUATION</span><i>→</i><strong>GLOBAL ISSUE</strong></div></section>

 <section id="io-issue" class="io-section" data-io-section><div class="io-section-head"><span>02 • GLOBAL ISSUE</span><h2>A strong global issue is wide in significance but narrow in wording.</h2><p>It should matter across cultures or borders while still being concrete enough to trace through specific moments in both texts.</p></div>
 <div class="io-issue-test"><article><span>01</span><h3>Global significance</h3><p>Does the issue matter beyond one local event or one character?</p></article><article><span>02</span><h3>Local reality</h3><p>Can you show how people actually experience the issue in concrete, human terms?</p></article><article><span>03</span><h3>Textual fit</h3><p>Do both chosen materials engage with the issue substantially rather than forcing a weak connection?</p></article><article><span>04</span><h3>Analytical precision</h3><p>Can you trace the issue through specific choices, not only through subject matter?</p></article></div>
 <div class="io-issue-table"><div class="io-table-title"><div><span>TOO BROAD → FOCUSED</span><b>Ten global-issue upgrades</b></div></div><div class="io-table-wrap"><table><thead><tr><th>Too broad</th><th>More focused</th><th>Why it improves</th></tr></thead><tbody>${globalIssues.map(x=>`<tr><td data-label="Too broad" class="io-weak">${esc(x.weak)}</td><td data-label="More focused"><b>${esc(x.improved)}</b></td><td data-label="Why it improves">${esc(x.why)}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="io-warning"><b>Fast test:</b><p>If you can discuss the issue much more easily than you can analyze the texts, the issue is probably still too broad.</p></div></section>

 <section id="io-material" class="io-section" data-io-section><div class="io-section-head"><span>03 • CHOOSING MATERIAL / EXTRACTS</span><h2>Choose an extract for analytical density, not plot importance.</h2><p>The best extract contains enough technique and meaning to sustain several minutes of close analysis and naturally opens into the wider work.</p></div>
 <div class="io-material-grid"><article><span>RICH IN CHOICES</span><h3>Can you actually analyze it?</h3>${list(['Look for language, structure, perspective, imagery, rhetoric, composition, layout, or other visible choices.','Prefer passages where several choices work together rather than one isolated technique.','Avoid extracts that are mostly plot mechanics or neutral description.'])}</article><article><span>STRONG ISSUE FIT</span><h3>Is the issue constructed here?</h3>${list(['The issue should be clearly present without forcing interpretation.','You should be able to connect individual details to the issue repeatedly.','If one chosen text only touches the issue lightly, rethink the pairing.'])}</article><article><span>WIDER-WORK POTENTIAL</span><h3>Can you zoom out?</h3>${list(['Choose a passage that connects to a recurring image, relationship, structural pattern, or later moment.','Plan at least one precise wider-work reference for each material.','Avoid vague claims that the theme “continues throughout.”'])}</article></div>
 <div class="io-extract-note"><strong>Extract size</strong><p>The supplied guidance describes a roughly 40-line guideline, or a teacher-guided equivalent for formats such as advertisements. Treat the exact selection rules as something to confirm with your teacher.</p></div></section>

 <section id="io-analysis" class="io-section" data-io-section><div class="io-section-head"><span>04 • CLOSE ANALYSIS</span><h2>Do the Paper 1 thinking — aloud, faster, and tied to the global issue.</h2><p>Do not narrate what happens. Explain how a choice produces an effect, what that effect means, and why it matters to the issue.</p></div>
 <div class="io-close-grid"><article><span>ORIGINAL LITLAB • LITERARY</span><blockquote>“She counted the steps to the door the way she used to count the tide going out: slowly, and without much hope of it staying.”</blockquote><div class="io-avoid"><small>SUMMARY TO AVOID</small><p>A woman walks toward a door and thinks about the tide.</p></div><div class="io-aim"><small>CLOSE ANALYSIS</small><p>The tide simile turns a simple departure into a pattern of loss. Because a receding tide normally returns, the phrase about having little hope of it “staying” unsettles that cycle and makes the loss feel emotionally final. A wider issue such as displacement becomes embodied in one small action.</p></div></article>
 <article><span>ORIGINAL LITLAB • NON-LITERARY</span><blockquote>“Relocation assistance available. We’re here to help you move forward.”</blockquote><div class="io-avoid"><small>SUMMARY TO AVOID</small><p>The advertisement says the company will help people move.</p></div><div class="io-aim"><small>CLOSE ANALYSIS</small><p>“Move forward” reframes forced displacement as positive progress. The reassuring institutional register removes specific human cost, so the language manages perception and softens the reality of losing a home.</p></div></article></div>
 <div class="io-analysis-reminder"><b>Spoken analysis still needs evidence.</b><p>Use short precise references and immediately explain their function. Do not stack quotations or terminology without interpretation.</p></div></section>

 <section id="io-wider" class="io-section" data-io-section><div class="io-section-head"><span>05 • WIDER WORK</span><h2>The extract is a starting point, not the whole oral.</h2><p>After close analysis, show that the same issue develops elsewhere in the work or body of work.</p></div>
 <div class="io-zoom"><div><span>LOCAL DETAIL</span><b>Analyze one precise choice in the extract.</b></div><i>→</i><div><span>WIDER MOMENT</span><b>Name another scene, pattern, image, or structural choice.</b></div><i>→</i><div><span>DEVELOPMENT</span><b>Explain whether it reinforces, complicates, or contrasts with the extract.</b></div><i>→</i><div><span>ISSUE</span><b>Return to what this reveals about the global issue.</b></div></div>
 <div class="io-wording-pair"><article><small>VAGUE</small><p>“This theme continues throughout the book.”</p></article><span>→</span><article><small>SPECIFIC</small><p>“This same pattern returns later when the protagonist is excluded from the town meeting, turning the extract’s personal isolation into a wider structural pattern.”</p></article></div></section>

 <section id="io-connect" class="io-section" data-io-section><div class="io-section-head"><span>06 • CONNECTING TO THE GLOBAL ISSUE</span><h2>Make every analytical point travel the full chain.</h2><p>The local choice is only the beginning. Strong IO analysis reaches wider significance instead of stopping at “this creates tension.”</p></div>
 <div class="io-connect-chain"><span>AUTHORIAL CHOICE</span><i>→</i><span>EFFECT</span><i>→</i><span>MEANING</span><i>→</i><strong>GLOBAL ISSUE</strong><i>→</i><strong>WIDER SIGNIFICANCE</strong></div>
 <div class="io-chain-lab"><div class="io-chain-tabs">${chainExamples.map((_,i)=>`<button type="button" data-chain="${i}" class="${i===0?'active':''}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div><article class="io-chain-card"><div><small>CHOICE</small><p>${esc(chainExamples[0].choice)}</p></div><div><small>EFFECT</small><p>${esc(chainExamples[0].effect)}</p></div><div><small>MEANING</small><p>${esc(chainExamples[0].meaning)}</p></div><div><small>GLOBAL ISSUE</small><p>${esc(chainExamples[0].issue)}</p></div><div><small>WIDER SIGNIFICANCE</small><p>${esc(chainExamples[0].significance)}</p></div></article></div></section>

 <section id="io-structure" class="io-section" data-io-section><div class="io-section-head"><span>07 • IO STRUCTURE</span><h2>Use timing as a practice framework, not a memorized script.</h2><p>The supplied strategy uses four jobs: frame the issue, analyze the literary work, analyze the non-literary text, then synthesize.</p></div>
 <div class="io-structure-grid"><article><span>~1 MIN</span><strong>Opening</strong><p>State the global issue clearly, identify both materials, and establish the analytical frame.</p></article><article><span>~4 MIN</span><strong>Literary analysis</strong><p>Close analysis of the extract → explicit issue connection → precise wider-work development.</p></article><article><span>~4 MIN</span><strong>Non-literary analysis</strong><p>Apply the same rigor to the non-literary material and begin making the relationship between the texts visible.</p></article><article><span>~1 MIN</span><strong>Closing</strong><p>Draw the representations together and finish with what the comparison reveals about the issue’s wider significance.</p></article></div>
 <p class="io-framework-note"><b>Practice framework:</b> the exact timing can shift. The purpose is to complete all four analytical jobs rather than follow a rigid sentence-by-sentence formula.</p>
 <div class="io-timer-card"><div class="io-timer-top"><div><span>IO PRACTICE TIMER</span><h3 data-timer-label>Full oral practice</h3></div><div class="io-timer-display"><b data-timer>10:00</b><small data-timer-state>ready</small></div></div><div class="io-presets"><button type="button" data-preset="60" data-label="1-minute analysis drill">1:00 Analysis</button><button type="button" data-preset="120" data-label="2-minute mini oral">2:00 Mini oral</button><button type="button" data-preset="600" data-label="Full oral practice" class="active">10:00 Full oral</button><button type="button" data-preset="300" data-label="Q&A practice">5:00 Q&A</button></div><div class="io-timer-actions"><button type="button" class="btn primary" data-timer-toggle>Start</button><button type="button" class="btn secondary" data-timer-reset>Reset</button></div></div></section>

 <section id="io-transitions" class="io-section" data-io-section><div class="io-section-head"><span>08 • TRANSITIONS</span><h2>Make the oral sound connected, not memorized.</h2><p>Transitions should show the logic of your argument. Vary them rather than repeating one phrase before every point.</p></div>
 <div class="io-transition-grid">${Object.entries(transitionGroups).map(([label,items])=>`<article><span>${esc(label.toUpperCase())}</span>${items.map(x=>`<p>“${esc(x)}”</p>`).join('')}</article>`).join('')}</div></section>

 <section id="io-evaluation" class="io-section" data-io-section><div class="io-section-head"><span>09 • EVALUATION</span><h2>Judge the choice while you analyze it.</h2><p>Evaluation should sound conversational and justified, not like the word “effective” was added at the end of a sentence.</p></div>
 <div class="io-evaluation-grid">${evaluationExamples.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><p>“${esc(x)}”</p></article>`).join('')}</div>
 <div class="io-eval-formula"><span>EFFECT</span><i>+</i><span>WHY IT WORKS HERE</span><i>+</i><span>LIMIT / COMPARISON WHEN USEFUL</span><i>=</i><strong>EVALUATION</strong></div></section>

 <section id="io-delivery" class="io-section" data-io-section><div class="io-section-head"><span>10 • DELIVERY</span><h2>Sound prepared, not recited.</h2><p>Strong delivery comes from knowing the argument well enough to phrase it naturally in the moment.</p></div><div class="io-delivery-grid">${deliveryTips.map(([title,text],i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h3>${esc(title)}</h3><p>${esc(text)}</p></div></article>`).join('')}</div></section>

 <section id="io-practice" class="io-section" data-io-section><div class="io-section-head"><span>11 • IO PRACTICE LAB</span><h2>Practice the thinking before you practice the performance.</h2><p>These are original LitLab exercises. Try the prompt aloud before revealing the model reasoning.</p></div>
 <div class="io-practice-lab"><div class="io-practice-tabs"><button type="button" data-practice-mode="analysis" class="active">1-min Analysis <span>10</span></button><button type="button" data-practice-mode="choice">Authorial Choice <span>10</span></button><button type="button" data-practice-mode="connection">Global Issue <span>10</span></button><button type="button" data-practice-mode="mini">2-min Mini Oral <span>5</span></button><button type="button" data-practice-mode="continue">Say Next <span>5</span></button></div>
 <article class="io-practice-card"><div class="io-practice-card-head"><div><span data-practice-kicker>1-MINUTE ANALYSIS</span><strong data-practice-count>1 / 10</strong></div><button type="button" data-practice-timer>Set practice timer</button></div><h3 data-practice-prompt>${esc(analysisDrills[0].prompt)}</h3><div class="io-practice-model" data-practice-model hidden><span>MODEL REASONING</span><p>${esc(analysisDrills[0].model)}</p></div><div class="io-practice-actions"><button type="button" class="btn secondary" data-practice-prev disabled>← Previous</button><button type="button" class="btn primary" data-practice-reveal>Reveal model</button><button type="button" class="btn secondary" data-practice-next>Next →</button></div></article></div>
 <div class="io-practice-note"><b>Practice rule:</b><p>Say your answer first. The model is a reasoning pattern to compare against, not a script to memorize.</p></div></section>

 <section id="io-mistakes" class="io-section" data-io-section><div class="io-section-head"><span>12 • COMMON IO MISTAKES</span><h2>Most weak orals fail in predictable ways.</h2><p>Open a mistake to see why it hurts, the fix, and a concrete example.</p></div><div class="io-mistake-grid">${mistakes.map((x,i)=>`<details ${i===0?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span><b>${esc(x.title)}</b><em>Open →</em></summary><div class="io-mistake-body"><article><small>WHY IT HURTS</small><p>${esc(x.why)}</p></article><article><small>FIX</small><p>${esc(x.fix)}</p></article><article><small>EXAMPLE</small><p>${esc(x.example)}</p></article></div></details>`).join('')}</div>
 <div class="io-completion"><div><span>WHEN YOU FEEL READY</span><h3 data-complete-title>${storedDone().includes('io')?'IO guide reviewed.':'Finished reviewing the IO guide?'}</h3><p>Progress means reviewed, not mastered. Keep using the practice lab and timer as your oral develops.</p></div><button type="button" class="btn primary" data-complete>${storedDone().includes('io')?'Reviewed ✓':'Mark as reviewed'}</button></div></section>
 </section>`}

function bind(page:HTMLElement){
 page.addEventListener('click',e=>{const target=e.target as HTMLElement;const go=target.closest<HTMLElement>('[data-go]');if(go){location.hash=go.dataset.go||'home';return}const scroll=target.closest<HTMLElement>('[data-scroll]');if(scroll){document.getElementById(scroll.dataset.scroll||'')?.scrollIntoView({behavior:'smooth',block:'start'});return}});
 const navButtons=[...page.querySelectorAll<HTMLButtonElement>('.io-nav [data-scroll]')];
 const observed=[...page.querySelectorAll<HTMLElement>('[data-io-section]')];
 if('IntersectionObserver'in window){const obs=new IntersectionObserver(entries=>{const visible=entries.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;navButtons.forEach(b=>b.classList.toggle('current',b.dataset.scroll===visible.target.id))},{rootMargin:'-25% 0px -62% 0px',threshold:[0,.1,.25]});observed.forEach(x=>obs.observe(x))}

 const chainCard=page.querySelector<HTMLElement>('.io-chain-card');page.querySelectorAll<HTMLButtonElement>('[data-chain]').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.chain||0),x=chainExamples[i];page.querySelectorAll('[data-chain]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');if(chainCard)chainCard.innerHTML=`<div><small>CHOICE</small><p>${esc(x.choice)}</p></div><div><small>EFFECT</small><p>${esc(x.effect)}</p></div><div><small>MEANING</small><p>${esc(x.meaning)}</p></div><div><small>GLOBAL ISSUE</small><p>${esc(x.issue)}</p></div><div><small>WIDER SIGNIFICANCE</small><p>${esc(x.significance)}</p></div>`}));

 let preset=600,remaining=600,running=false,timerId:number|undefined;const timer=page.querySelector<HTMLElement>('[data-timer]')!,state=page.querySelector<HTMLElement>('[data-timer-state]')!,label=page.querySelector<HTMLElement>('[data-timer-label]')!,toggle=page.querySelector<HTMLButtonElement>('[data-timer-toggle]')!;
 const paint=()=>{timer.textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;state.textContent=running?'speaking':remaining===0?'time':'ready';toggle.textContent=running?'Pause':remaining<preset&&remaining>0?'Resume':'Start'};
 const stop=()=>{running=false;if(timerId!==undefined)window.clearInterval(timerId);timerId=undefined;paint()};
 const setPreset=(seconds:number,name:string)=>{stop();preset=remaining=seconds;label.textContent=name;page.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',(x as HTMLElement).dataset.preset===String(seconds)));paint()};
 page.querySelectorAll<HTMLButtonElement>('[data-preset]').forEach(b=>b.addEventListener('click',()=>setPreset(Number(b.dataset.preset),b.dataset.label||'Practice')));
 toggle.addEventListener('click',()=>{if(remaining===0)remaining=preset;running=!running;if(running){timerId=window.setInterval(()=>{remaining=Math.max(0,remaining-1);if(remaining===0)stop();else paint()},1000)}else stop();paint()});
 page.querySelector<HTMLButtonElement>('[data-timer-reset]')?.addEventListener('click',()=>setPreset(preset,label.textContent||'Practice'));

 type PracticeMode='analysis'|'choice'|'connection'|'mini'|'continue';let mode:PracticeMode='analysis',index=0,revealed=false;
 const prompt=page.querySelector<HTMLElement>('[data-practice-prompt]')!,model=page.querySelector<HTMLElement>('[data-practice-model]')!,count=page.querySelector<HTMLElement>('[data-practice-count]')!,kicker=page.querySelector<HTMLElement>('[data-practice-kicker]')!,prev=page.querySelector<HTMLButtonElement>('[data-practice-prev]')!,next=page.querySelector<HTMLButtonElement>('[data-practice-next]')!,reveal=page.querySelector<HTMLButtonElement>('[data-practice-reveal]')!;
 const getItems=()=>mode==='analysis'?analysisDrills:mode==='choice'?choiceDrills:mode==='connection'?connectionDrills:mode==='mini'?miniOrals:continuations;
 const modeName=()=>mode==='analysis'?'1-MINUTE ANALYSIS':mode==='choice'?'AUTHORIAL CHOICE':mode==='connection'?'GLOBAL-ISSUE CONNECTION':mode==='mini'?'2-MINUTE MINI ORAL':'WHAT WOULD YOU SAY NEXT?';
 const practiceText=(item:any)=>mode==='mini'?`${item.issue}\n\n${item.texts}`:item.prompt;
 const modelText=(item:any)=>mode==='mini'?item.shape:item.model;
 const renderPractice=()=>{const items=getItems() as any[],item=items[index];prompt.textContent=practiceText(item);model.querySelector('p')!.textContent=modelText(item);model.hidden=!revealed;reveal.textContent=revealed?'Hide model':'Reveal model';count.textContent=`${index+1} / ${items.length}`;kicker.textContent=modeName();prev.disabled=index===0;next.disabled=index===items.length-1};
 page.querySelectorAll<HTMLButtonElement>('[data-practice-mode]').forEach(b=>b.addEventListener('click',()=>{mode=(b.dataset.practiceMode||'analysis') as PracticeMode;index=0;revealed=false;page.querySelectorAll('[data-practice-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPractice()}));
 prev.addEventListener('click',()=>{if(index>0){index--;revealed=false;renderPractice()}});next.addEventListener('click',()=>{if(index<getItems().length-1){index++;revealed=false;renderPractice()}});reveal.addEventListener('click',()=>{revealed=!revealed;renderPractice()});
 page.querySelector<HTMLButtonElement>('[data-practice-timer]')?.addEventListener('click',()=>{const seconds=mode==='mini'?120:60;setPreset(seconds,mode==='mini'?'2-minute mini oral':modeName().toLowerCase());document.getElementById('io-structure')?.scrollIntoView({behavior:'smooth',block:'center'})});
 page.querySelector<HTMLButtonElement>('[data-complete]')?.addEventListener('click',e=>{markDone();const b=e.currentTarget as HTMLButtonElement;b.textContent='Reviewed ✓';const h=page.querySelector<HTMLElement>('[data-complete-title]');if(h)h.textContent='IO guide reviewed.'});
 renderPractice();paint();
}

let mounting=false;
function mount(){if(route()!=='io')return;const main=document.querySelector<HTMLElement>('main#main');if(!main||mounting)return;mounting=true;main.classList.add('io-guide-main');let page=main.querySelector<HTMLElement>('.io-guide-page');if(!page){main.insertAdjacentHTML('beforeend',template());page=main.querySelector<HTMLElement>('.io-guide-page')!;bind(page)}mounting=false}
function unmount(){const main=document.querySelector<HTMLElement>('main#main');main?.classList.remove('io-guide-main');main?.querySelector('.io-guide-page')?.remove()}
function sync(){setTimeout(()=>{if(route()==='io')mount();else unmount()},90)}
const root=document.getElementById('root');if(root)new MutationObserver(()=>{if(route()==='io'&&!document.querySelector('.io-guide-page'))mount()}).observe(root,{childList:true,subtree:true});
window.addEventListener('hashchange',sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync();
