import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,Atom,BookOpen,Check,ChevronDown,ChevronRight,CircleHelp,Clock,ExternalLink,FileText,FlaskConical,Home as HomeIcon,Instagram,LibraryBig,Menu,Mic2,Moon,Pause,Play,RefreshCw,Search,SearchCheck,Sparkles,Sun,Target,TriangleAlert,X,Zap}from'lucide-react';
import{compass,faqs,glossary,homeCards,nav,officialSources,searchItems,tips}from'./content';
import'./styles.css';

type Go=(to:string)=>void;
const INSTAGRAM='https://www.instagram.com/rhhs.ibdp.27/';
const stored=(key:string,fallback:string[]=[]):string[]=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(v)?v:fallback}catch{return fallback}};
const iconMap:{[k:string]:React.ComponentType<{size?:number}>}={FlaskConical,FileText,Mic2,LibraryBig,SearchCheck};

function Logo(){return <span className="logo"><svg viewBox="0 0 48 48" aria-hidden="true"><path className="logo-page" d="M9 11h12c4 0 7 2 9 5v22c-2-3-5-5-9-5H9z"/><path className="logo-page" d="M39 11H27c-4 0-7 2-9 5v22c2-3 5-5 9-5h12z"/><path className="logo-flask" d="M21 8h6M23 8v8l-7 12c-2 4 0 8 5 8h6c5 0 7-4 5-8l-7-12V8"/><path className="logo-spark" d="m35 6 1.2 3.8L40 11l-3.8 1.2L35 16l-1.2-3.8L30 11l3.8-1.2z"/></svg><span>Lit<span>Lab</span></span></span>}

function App(){
 const parse=()=>location.hash.slice(1).split('#')[0]||'home';
 const [page,setPage]=useState(parse),[dark,setDark]=useState(localStorage.litlabTheme==='dark'),[menu,setMenu]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(''),[done,setDone]=useState<string[]>(()=>stored('litlabDone'));
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.litlabTheme=dark?'dark':'light'},[dark]);
 useEffect(()=>{const fn=()=>{setPage(parse());setMenu(false);requestAnimationFrame(()=>scrollTo({top:0,behavior:'smooth'}))};addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)}if(e.key==='Escape'){setSearchOpen(false);setMenu(false)}};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[]);
 const go:Go=(to)=>{const [p,anchor]=to.split('#');if(parse()!==p) location.hash=p;else setPage(p);setMenu(false);setSearchOpen(false);setTimeout(()=>{if(anchor)document.getElementById(anchor)?.scrollIntoView({behavior:'smooth',block:'start'});else scrollTo({top:0,behavior:'smooth'})},80)};
 const mark=(id:string)=>setDone(v=>{const n=v.includes(id)?v:[...v,id];localStorage.litlabDone=JSON.stringify(n);return n});
 const results=useMemo(()=>{const q=query.trim().toLowerCase();return q?searchItems.filter(x=>(x.title+' '+x.preview+' '+x.category).toLowerCase().includes(q)).slice(0,10):[]},[query]);
 return <div className="app-shell">
  <a className="skip" href="#main">Skip to content</a>
  <header className="topbar"><button className="brand-btn" onClick={()=>go('home')} aria-label="LitLab home"><Logo/></button><nav aria-label="Primary navigation">{nav.map(([slug,label])=><button key={slug} className={page===slug?'active':''} onClick={()=>go(slug)}>{label}</button>)}</nav><div className="top-actions"><button className="search-trigger" onClick={()=>setSearchOpen(true)}><Search size={17}/><span>Search</span><kbd>⌘K</kbd></button><button className="icon-btn" onClick={()=>setDark(v=>!v)} aria-label="Toggle theme">{dark?<Sun/>:<Moon/>}</button><button className="icon-btn mobile-only" onClick={()=>setMenu(v=>!v)} aria-expanded={menu} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></header>
  {menu&&<div className="mobile-menu">{nav.map(([slug,label])=><button key={slug} onClick={()=>go(slug)}>{label}<ChevronRight/></button>)}<button onClick={()=>setSearchOpen(true)}>Search<Search/></button></div>}
  {searchOpen&&<SearchModal query={query} setQuery={setQuery} results={results} close={()=>setSearchOpen(false)} go={go}/>} 
  <main id="main">{page==='home'?<Home go={go} done={done}/>:page==='start'?<StartHere go={go} done={done} mark={mark}/>:page==='papers'?<Papers go={go}/>:page==='paper-1'?<PaperPage kind="Paper 1" go={go} done={done} mark={mark}/>:page==='paper-2'?<PaperPage kind="Paper 2" go={go} done={done} mark={mark}/>:page==='io'?<IOPage go={go} done={done} mark={mark}/>:page==='books'?<BooksPage go={go} done={done} mark={mark}/>:page==='ee'?<EEPage go={go} done={done} mark={mark}/>:page==='glossary'?<GlossaryPage/>:<AboutPage/>}</main>
  <Footer go={go}/>
 </div>
}

function SearchModal({query,setQuery,results,close,go}:{query:string;setQuery:(v:string)=>void;results:typeof searchItems;close:()=>void;go:Go}){return <div className="modal" role="dialog" aria-modal="true" aria-label="Search LitLab" onMouseDown={close}><div className="search-modal" onMouseDown={e=>e.stopPropagation()}><div className="search-row"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search analysis, IO, Paper 1, thesis…" aria-label="Search LitLab"/><button className="icon-btn" onClick={close} aria-label="Close search"><X/></button></div><div className="search-results">{!query?<><span className="mini-label">Quick access</span>{searchItems.slice(0,6).map(r=><button key={r.title} onClick={()=>go(r.to)}><span><b>{r.title}</b><small>{r.category}</small></span><ChevronRight/></button>)}</>:results.length?results.map(r=><button key={r.title+r.category} onClick={()=>go(r.to)}><span><b>{r.title}</b><small>{r.preview}</small></span><ChevronRight/></button>):<div className="no-results"><Search/><b>No match yet.</b><span>Try a broader word such as “analysis”, “IO” or “thesis”.</span></div>}</div></div></div>}

function Home({go,done}:{go:Go;done:string[]}){const[tipIndex,setTipIndex]=useState(0);return <>
 <section className="hero home-hero"><div className="hero-grid"></div><div className="hero-glow one"></div><div className="hero-glow two"></div><div className="hero-copy reveal"><span className="eyebrow"><Sparkles/> Student-made DP English guide</span><h1>English can feel complicated.<br/><em>LitLab makes it clearer.</em></h1><p>Explore the key parts of DP English, understand how they connect, discover useful strategies and find the section you need without digging through pages of notes.</p><div className="button-row"><button className="btn primary" onClick={()=>document.getElementById('compass')?.scrollIntoView({behavior:'smooth'})}>Start exploring <ArrowRight/></button><button className="btn secondary" onClick={()=>go('start')}>I'm new — Start Here</button></div><p className="creator-line">Created by <b>Rayan Sayed Ahmad</b> & <b>Elena Bizri</b></p></div><HeroLabArt/></section>
 <section id="compass" className="section compass-section"><SectionHead eyebrow="LitLab Compass" title="Where are you trying to go?" text="Choose a direction. Nothing is locked, and you can jump straight to what you need."/><Compass go={go}/></section>
 <section className="section"><div className="quick-strip"><span>Quick access</span>{[['What is Paper 1?','paper-1'],['Paper 1 vs Paper 2','papers'],['What is the IO?','io'],['Analysis vs Summary','start#analysis'],['Authorial Choices','start#choices'],['What is an EE?','ee']].map(([l,to])=><button key={l} onClick={()=>go(to)}>{l}<ArrowRight/></button>)}</div></section>
 <section className="section"><SectionHead eyebrow="Explore the guide" title="Five places. One clear map." text="Start with the overview, or go directly to the part of DP English you are working on."/><div className="feature-grid">{homeCards.map(c=>{const I=iconMap[c.icon]||BookOpen;return <button className="feature-card tilt" key={c.slug} onClick={()=>go(c.slug)}><span className="feature-no">{c.n}</span><span className="feature-icon"><I size={27}/></span><h3>{c.title}</h3><p>{c.desc}</p><span className="card-link">Explore <ArrowRight/></span></button>})}</div></section>
 <section className="section flow-section"><SectionHead eyebrow="How LitLab helps" title="Find → understand → practise → move forward."/><div className="flow-line">{[['01','Find','Choose what you are working on.'],['02','Understand','Use concise explanations and examples.'],['03','Practise','Try mini checks and interactive tools.'],['04','Move forward','Mark a guide ready and continue.']].map((x,i)=><div className="flow-step" key={x[0]}><span>{x[0]}</span><div className="flow-dot">{i<3?<ArrowRight/>:<Check/>}</div><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
 <section className="section faq-section"><SectionHead eyebrow="Most asked questions" title="You're probably not the only one wondering." text="Short answers for the questions students ask first."/><FAQList go={go}/></section>
 <section className="section split-section"><div className="tip-lab"><span className="eyebrow"><Zap/> LitLab tip</span><h2>{tips[tipIndex].title}</h2><p>{tips[tipIndex].text}</p><button className="btn secondary" onClick={()=>setTipIndex(i=>(i+1)%tips.length)}>Another tip <RefreshCw/></button></div><ProgressPanel done={done}/></section>
 <section className="section makers"><div><span className="eyebrow">Built by students, for students</span><h2>Made to be useful before it tries to be impressive.</h2><p>LitLab was created by Rayan Sayed Ahmad and Elena Bizri as a student project designed to make the first steps into DP English clearer and more approachable.</p><div className="button-row"><button className="btn primary" onClick={()=>go('about')}>About the project <ArrowRight/></button><a className="btn insta" href={INSTAGRAM} target="_blank" rel="noopener noreferrer"><Instagram/> View our Instagram <ExternalLink/></a></div></div><div className="maker-orbit"><div className="orbit-ring r1"></div><div className="orbit-ring r2"></div><div className="maker-core"><Logo/></div><span className="orbit-label l1">CAS</span><span className="orbit-label l2">DP1</span><span className="orbit-label l3">ENGLISH</span></div></section>
 </>}

function HeroLabArt(){return <div className="hero-art" aria-hidden="true"><div className="paper p1"><span>ANALYSE</span><i></i><i></i><i></i></div><div className="paper p2"><span>CONNECT</span><i></i><i></i></div><div className="lab-orb"><Atom/></div><div className="floating-tag t1">P1</div><div className="floating-tag t2">IO</div><div className="floating-tag t3">EE</div><div className="floating-tag t4">BOOKS</div></div>}

function Compass({go}:{go:Go}){const[active,setActive]=useState('');const desc=compass.find(x=>x.slug===active);return <div className="compass-wrap"><svg className="compass-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{compass.map((n,i)=><line key={i} x1="50" y1="50" x2={n.x} y2={n.y} className={active===n.slug?'active':''}/>) }<circle cx="50" cy="50" r="31"/><circle cx="50" cy="50" r="20"/></svg><div className="compass-center"><Logo/><small>DP ENGLISH</small><p>{desc?desc.sub:'Choose a direction'}</p></div>{compass.map((n,i)=><button key={n.label} className={'compass-node n'+i+(active===n.slug?' active':'')} style={{left:`${n.x}%`,top:`${n.y}%`}} onMouseEnter={()=>setActive(n.slug)} onMouseLeave={()=>setActive('')} onFocus={()=>setActive(n.slug)} onBlur={()=>setActive('')} onClick={()=>go(n.slug)}><b>{n.label}</b><span>{n.sub}</span></button>)}</div>}

function FAQList({go}:{go:Go}){const[open,setOpen]=useState(0);return <div className="faq-list">{faqs.map((f,i)=>{const to=f.to;return <div className={'faq '+(open===i?'open':'')} key={f.q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{f.q}</span><ChevronDown/></button>{open===i&&<div className="faq-answer"><p>{f.a}</p>{to&&<button onClick={()=>go(to)}>Go deeper <ArrowRight/></button>}</div>}</div>})}</div>}

function ProgressPanel({done}:{done:string[]}){const rows=[['Start Here',['start']],['Papers',['paper-1','paper-2']],['IO',['io']],['Books',['books']],['EE',['ee']]] as [string,string[]][];return <div className="progress-panel"><span className="eyebrow"><Target/> Your LitLab journey</span><h2>Progress means “reviewed”, not “mastered”.</h2>{rows.map(([label,ids])=>{const count=ids.filter(i=>done.includes(i)).length,pct=Math.round(count/ids.length*100);return <div className="progress-row" key={label}><div><b>{label}</b><span>{pct}%</span></div><div className="bar"><i style={{width:`${pct}%`}}/></div></div>})}</div>}

function StartHere({go,done,mark}:{go:Go;done:string[];mark:(id:string)=>void}){const[analysis,setAnalysis]=useState(0),[ladder,setLadder]=useState(0),[checks,setChecks]=useState<string[]>(()=>stored('litlabStartChecklist'));const toggle=(x:string)=>setChecks(v=>{const n=v.includes(x)?v.filter(i=>i!==x):[...v,x];localStorage.litlabStartChecklist=JSON.stringify(n);return n});return <article className="learning-page"><PageHero eyebrow="Start Here" title="Understand the map before you worry about mastering it." text="A knowledge-rich introduction to DP English: what the subject asks you to notice, how analysis works, and the habits that make later assessments easier." icon={<FlaskConical/>}/><StickyTOC items={[['overview','Big picture'],['analysis','Analysis'],['choices','Authorial choices'],['ladder','Analysis ladder'],['thesis','Thesis'],['paragraph','Paragraphs'],['vocabulary','Vocabulary'],['tips','Tips'],['mistakes','Mistakes'],['notes','Book notes'],['setup','Setup']]}/>
 <ContentSection id="overview" n="01" title="What is DP English really asking you to do?"><p>Across DP Studies in Language and Literature, students develop close reading, interpretation, critical thinking and the ability to explain ideas clearly. The exact texts and assessment format depend on whether you take Language A: Literature or Language A: Language & Literature, but the underlying habit is similar: move from <b>what you notice</b> to <b>what it means and why it matters</b>.</p><div className="depth-steps">{['What happens?','How is it presented?','Why this choice?','What meaning does it create?'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div><Callout type="official" title="Course differences matter">LitLab stays broad where the two Language A courses differ. Use your teacher and current IB documentation for course-specific assessment instructions.</Callout></ContentSection>
 <ContentSection id="analysis" n="02" title="The skill that changes everything: analysis"><p>Summary reports content. Analysis explains how a creator's choices shape meaning. Click through the same idea as it becomes more analytical.</p><div className="analysis-demo"><div className="analysis-stage"><span>Level {analysis+1}</span><h3>{['Observation','Identification','Analysis','Deeper interpretation'][analysis]}</h3><p>{['The room is described as dark.','The writer uses dark imagery.','The repeated darkness creates an oppressive atmosphere, reflecting the character’s growing isolation.','By making darkness recur around moments of decision, the writer turns the setting into a pattern that mirrors the character’s shrinking sense of freedom.'][analysis]}</p></div><div className="analysis-controls">{['Observe','Name','Explain','Connect'].map((x,i)=><button className={analysis===i?'active':''} onClick={()=>setAnalysis(i)} key={x}>{x}</button>)}</div></div><div className="weak-strong"><div><span>SUMMARY</span><p>“The character enters the room and feels uncomfortable.”</p></div><ArrowRight/><div><span>ANALYSIS</span><p>“The enclosed setting and repeated references to darkness make the space feel oppressive, externalising the character’s discomfort.”</p></div></div></ContentSection>
 <ContentSection id="choices" n="03" title="What is an authorial choice?"><p>An authorial choice is a decision about <em>how</em> something is communicated. Naming the choice gives you precision; explaining its effect gives you analysis.</p><div className="choice-grid">{[
 ['Language',['Diction','Imagery','Repetition','Figurative language','Tone','Sound'],'What associations or emphasis does this language create?'],
 ['Structure',['Order','Pacing','Juxtaposition','Beginnings/endings','Paragraphing','Shifts'],'Why is the information arranged this way?'],
 ['Narrative',['Characterisation','Perspective','Voice','Dialogue','Focalisation'],'Whose viewpoint shapes what we understand?'],
 ['Visual / multimodal',['Composition','Framing','Typography','Colour','Layout','Image placement'],'How does visual arrangement guide attention or meaning?']
 ].map(([title,items,q])=><div className="choice-card" key={title as string}><span>{title}</span><div>{(items as string[]).map(x=><b key={x}>{x}</b>)}</div><p>Ask yourself: {q}</p></div>)}</div><Callout type="tip" title="Don't collect techniques like Pokémon">Knowing fifty technique names matters less than being able to explain exactly what one well-chosen detail does.</Callout></ContentSection>
 <ContentSection id="ladder" n="04" title="The LitLab Analysis Ladder"><p>Use this when you are stuck. Click a rung and answer its question before climbing higher.</p><div className="ladder"><div className="ladder-buttons">{[['NOTICE','What stands out?'],['NAME','What choice is being made?'],['EFFECT','What does the choice do?'],['MEANING','What might it suggest?'],['PURPOSE','Why might the creator want this?'],['CONNECTION','How does it support the wider idea?']].map((x,i)=><button className={ladder===i?'active':''} onClick={()=>setLadder(i)} key={x[0]}><span>{i+1}</span><b>{x[0]}</b></button>)}</div><div className="ladder-screen"><span>Rung {ladder+1}</span><h3>{[['NOTICE','What stands out?'],['NAME','What choice is being made?'],['EFFECT','What does the choice do?'],['MEANING','What might it suggest?'],['PURPOSE','Why might the creator want this?'],['CONNECTION','How does it support the wider idea?']][ladder][0]}</h3><p>{[['NOTICE','What stands out?'],['NAME','What choice is being made?'],['EFFECT','What does the choice do?'],['MEANING','What might it suggest?'],['PURPOSE','Why might the creator want this?'],['CONNECTION','How does it support the wider idea?']][ladder][1]}</p></div></div><div className="question-cloud">{['Why this word?','Why this image?','Why here?','What changes?','Who is the audience?','What response might this create?','What does this reveal?','What larger idea does this connect to?'].map(x=><span key={x}>{x}</span>)}</div></ContentSection>
 <ContentSection id="thesis" n="05" title="Thesis basics"><p>A thesis should give your response a direction. It is stronger when it makes an arguable claim rather than announcing that techniques exist.</p><div className="compare-box"><div><span>WEAK</span><p>“This text uses many techniques to show power.”</p></div><div><span>BETTER</span><p>“The text presents power as unstable by contrasting public confidence with moments of private uncertainty.”</p></div></div><Callout type="tip" title="LitLab test">If your thesis could describe almost any text, it is probably too vague. Make the claim specific enough that you must prove it.</Callout></ContentSection>
 <ContentSection id="paragraph" n="06" title="Build an analytical paragraph, not a formula"><p>Teachers may use different paragraph structures. The useful thinking underneath them is usually some version of this chain:</p><div className="paragraph-chain">{['Claim','Evidence / reference','Authorial choice','Effect','Interpretation','Connection'].map((x,i)=><React.Fragment key={x}><div><span>{i+1}</span>{x}</div>{i<5&&<ArrowRight/>}</React.Fragment>)}</div><p className="muted">Use this as a thinking tool rather than a rigid sentence recipe. Your teacher's instructions take priority for assessed work.</p></ContentSection>
 <ContentSection id="vocabulary" n="07" title="Essential vocabulary"><p>You do not need to memorise a dictionary. Learn terms by using them in analysis.</p><MiniGlossary go={go}/></ContentSection>
 <ContentSection id="tips" n="08" title="Things we wish someone told us earlier"><div className="tips-grid">{tips.concat([{title:'Ask questions while reading',text:'“What changed?” and “why now?” often reveal more than simply recording what happened.'},{title:'Accuracy beats decoration',text:'Use terminology you understand. A precise simple explanation is stronger than an impressive word used incorrectly.'}]).map((t,i)=><div className="tip-card" key={t.title}><span>{String(i+1).padStart(2,'0')}</span><h3>{t.title}</h3><p>{t.text}</p></div>)}</div></ContentSection>
 <ContentSection id="mistakes" n="09" title="Common beginner mistakes"><div className="mistake-list">{[
 ['Retelling the text','You explain what happens but not how meaning is created.'],['Technique spotting','You list devices without explaining effect or significance.'],['Vague effects','You repeatedly write “this makes the reader want to read more” without specifying what response is created.'],['Ignoring the bigger idea','Your comments never reconnect to purpose, representation, theme or argument.'],['Forcing terminology','You use advanced terms even when a simpler accurate description would be clearer.'],['Writing before thinking','You start paragraphs before deciding what the paragraph is trying to prove.']
 ].map(x=><div key={x[0]}><TriangleAlert/><div><b>{x[0]}</b><p>{x[1]}</p></div></div>)}</div></ContentSection>
 <ContentSection id="notes" n="10" title="A book-note system future you can actually use"><p>Do not wait until assessment season to rebuild your understanding of a book. Track useful moments as you study.</p><div className="note-table"><div className="table-head"><b>Moment</b><b>Theme</b><b>Choice</b><b>Effect</b><b>Connection</b></div><div><span>Scene / chapter</span><span>Power</span><span>Contrast</span><span>What changes?</span><span>Paper 2 / IO idea</span></div><div><span>Important moment</span><span>Identity</span><span>Imagery</span><span>What does it suggest?</span><span>Other work / theme</span></div></div><button className="btn secondary" onClick={()=>go('books')}>Open Books <ArrowRight/></button></ContentSection>
 <ContentSection id="setup" n="11" title="Your DP English setup"><Checklist checks={checks} toggle={toggle}/><CompletionAction id="start" isDone={done.includes('start')} mark={mark} nextLabel="Continue to Papers" next="papers" go={go}/></ContentSection>
 </article>}

function StickyTOC({items}:{items:[string,string][]}){return <div className="toc"><span>On this guide</span>{items.map(([id,l])=><a key={id} href={'#'+id}>{l}</a>)}</div>}
function ContentSection({id,n,title,children}:{id:string;n:string;title:string;children:React.ReactNode}){return <section className="content-section" id={id}><div className="section-number">{n}</div><div className="section-body"><h2>{title}</h2>{children}</div></section>}
function Callout({type,title,children}:{type:'tip'|'official'|'warning';title:string;children:React.ReactNode}){return <div className={'callout '+type}>{type==='tip'?<Sparkles/>:type==='official'?<CircleHelp/>:<TriangleAlert/>}<div><b>{title}</b><p>{children}</p></div></div>}
function MiniGlossary({go}:{go:Go}){const[q,setQ]=useState('');const list=glossary.filter(g=>(g.term+g.definition).toLowerCase().includes(q.toLowerCase())).slice(0,10);return <><div className="inline-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a term…"/></div><div className="mini-glossary">{list.map(g=><details key={g.term}><summary>{g.term}<ChevronDown/></summary><p>{g.definition}</p>{g.example&&<small>Example: {g.example}</small>}</details>)}</div><button className="text-btn" onClick={()=>go('glossary')}>View full glossary <ArrowRight/></button></>}
function Checklist({checks,toggle}:{checks:string[];toggle:(x:string)=>void}){const items=['I understand the basic structure of this guide','I know the high-level difference between Paper 1 and Paper 2','I know what IO stands for','I understand the difference between summary and analysis','I know what an authorial choice is','I created a place for my book notes','I know where to find the glossary','I know course details can differ between Language A courses'];return <div className="checklist"><div className="check-progress"><b>{checks.length} / {items.length} ready</b><div className="bar"><i style={{width:`${checks.length/items.length*100}%`}}/></div></div>{items.map(x=><button className={checks.includes(x)?'checked':''} onClick={()=>toggle(x)} key={x}><span>{checks.includes(x)?<Check/>:null}</span>{x}</button>)}</div>}
function CompletionAction({id,isDone,mark,nextLabel,next,go}:{id:string;isDone:boolean;mark:(id:string)=>void;nextLabel:string;next:string;go:Go}){return <div className={'completion '+(isDone?'ready':'')}><div className="completion-icon">{isDone?<Check/>:<Target/>}</div><div><span>{isDone?'GUIDE REVIEWED':'WHEN YOU FEEL READY'}</span><h3>{isDone?'You marked this guide as ready.':'Finished this guide?'}</h3><p>{isDone?'Progress here means reviewed — not perfect. You can revisit this any time.':'Mark it complete when you have reviewed the material. Nothing is locked.'}</p></div><div className="completion-actions">{!isDone&&<button className="btn primary" onClick={()=>mark(id)}>Mark as complete <Check/></button>}{isDone&&<button className="btn primary" onClick={()=>go(next)}>{nextLabel} <ArrowRight/></button>}<button className="btn secondary" onClick={()=>go('home')}>Open Compass</button></div></div>}

function Papers({go}:{go:Go}){return <section className="page"><PageHero eyebrow="Papers" title="Which paper are you working on?" text="One Papers section, two different jobs. Choose the path you need." icon={<FileText/>}/><div className="paper-split"><button className="paper-choice p1" onClick={()=>go('paper-1')}><div className="paper-visual"><Search/><span className="annot a1">tone?</span><span className="annot a2">why here?</span><span className="line l1"></span><span className="line l2"></span></div><span>01</span><h2>Paper 1</h2><p>Think: analyse what is in front of you. Build meaning from unseen material and the choices you can actually see.</p><b>Explore Paper 1 <ArrowRight/></b></button><button className="paper-choice p2" onClick={()=>go('paper-2')}><div className="paper-visual compare"><BookOpen/><BookOpen/><span className="bridge">↔</span></div><span>02</span><h2>Paper 2</h2><p>Think: bring studied works together. Build a comparative literary argument rather than two separate mini essays.</p><b>Explore Paper 2 <ArrowRight/></b></button></div><Callout type="official" title="Course-specific details">The exact Paper 1 unseen material differs between Language A: Literature and Language A: Language & Literature. LitLab will keep those differences clearly labelled when the detailed Paper content is added.</Callout></section>}

function PaperPage({kind,go,done,mark}:{kind:'Paper 1'|'Paper 2';go:Go;done:string[];mark:(id:string)=>void}){const is1=kind==='Paper 1',id=is1?'paper-1':'paper-2';const topics=is1?['Overview','Reading strategically','Annotation','Audience & purpose','Tone','Structure','Authorial choices','Building a thesis','Analytical paragraphs','Planning','Time management','Common mistakes','Practice']:['Overview','Knowing your works','Comparison','Themes','Characters','Structure','Authorial choices','Building a thesis','Comparative paragraphs','Choosing evidence','Planning','Time management','Common mistakes','Practice'];return <section className="page"><div className="breadcrumb"><button onClick={()=>go('papers')}>Papers</button><ChevronRight/>{kind}</div><PageHero eyebrow={kind} title={is1?'Analyse what is in front of you.':'Build a comparative argument.'} text={is1?'The structure is ready for the detailed guide your content team will add. LitLab already gives you the learning map without inventing unverified requirements.':'The comparison workspace is ready for your researched content, examples and practice questions.'} icon={is1?<Search/>:<BookOpen/>}/><div className="switch-row"><button className="btn secondary" onClick={()=>go(is1?'paper-2':'paper-1')}>Switch to {is1?'Paper 2':'Paper 1'} <ArrowRight/></button></div><div className="topic-map">{topics.map((t,i)=><div key={t}><span>{String(i+1).padStart(2,'0')}</span><b>{t}</b><small>{i<3?'Structure ready':'Content to be added after research'}</small></div>)}</div><Callout type="tip" title="Student strategy">{is1?'When you practise, force yourself to answer two questions after spotting a feature: “what effect?” and “why does that matter?”':'When comparing, avoid finishing all of Work A before mentioning Work B. Build the relationship between the works into the argument itself.'}</Callout><CompletionAction id={id} isDone={done.includes(id)} mark={mark} nextLabel={is1?'Continue to Paper 2':'Continue to IO'} next={is1?'paper-2':'io'} go={go}/></section>}

function IOPage({go,done,mark}:{go:Go;done:string[];mark:(id:string)=>void}){return <section className="page"><PageHero eyebrow="Individual Oral" title="Turn analysis into a clear spoken line of thought." text="The detailed IO content will be added after research. The practice system and learning structure are already working." icon={<Mic2/>}/><div className="io-layout"><div><h2>Guide structure</h2><div className="topic-map compact">{['IO overview','Global issues','Choosing material','Extracts','Whole-work / body-of-work connections','Analysis','Structure','Delivery','Practice','Common mistakes','Checklist'].map((t,i)=><div key={t}><span>{String(i+1).padStart(2,'0')}</span><b>{t}</b></div>)}</div></div><IOTimer/></div><Callout type="official" title="Important distinction">The exact material used in the Individual Oral differs between Language A: Literature and Language A: Language & Literature. Do not treat one course’s pairing as universal.</Callout><CompletionAction id="io" isDone={done.includes('io')} mark={mark} nextLabel="Continue to Books" next="books" go={go}/></section>}
function IOTimer(){const[seconds,setSeconds]=useState(600),[running,setRunning]=useState(false),[checkpoints,setCheckpoints]=useState(true);const ref=useRef<number|undefined>(undefined);useEffect(()=>{if(running)ref.current=window.setInterval(()=>setSeconds(s=>s>0?s-1:0),1000);return()=>clearInterval(ref.current)},[running]);useEffect(()=>{if(seconds===0)setRunning(false)},[seconds]);const m=Math.floor(seconds/60),s=seconds%60,pct=(600-seconds)/600*100;return <div className="timer-card"><span className="eyebrow"><Clock/> IO Practice Mode</span><div className="timer-ring" style={{'--pct':pct+'%'} as React.CSSProperties}><div><b>{m}:{String(s).padStart(2,'0')}</b><span>{running?'practising':'ready'}</span></div></div><div className="timer-actions"><button className="btn primary" onClick={()=>setRunning(v=>!v)}>{running?<><Pause/> Pause</>:<><Play/> {seconds<600?'Resume':'Start'}</>}</button><button className="btn secondary" onClick={()=>{setRunning(false);setSeconds(600)}}><RefreshCw/> Reset</button></div><label className="toggle"><input type="checkbox" checked={checkpoints} onChange={e=>setCheckpoints(e.target.checked)}/><span></span>Show suggested practice checkpoints</label>{checkpoints&&<div className="checkpoint-list"><b>Suggested practice structure</b><p>Use your teacher's required structure for assessment. These checkpoints are only a flexible rehearsal aid, not an official formula.</p><div><span>Opening</span><i></i><span>Development</span><i></i><span>Connection</span></div></div>}</div>}

function BooksPage({go,done,mark}:{go:Go;done:string[];mark:(id:string)=>void}){const[selected,setSelected]=useState(0);const slots=[['Book 01','Add your first book','Themes • characters • choices'],['Book 02','Your next class text','Context • moments • connections'],['Book 03','Comparison candidate','Paper 2 • themes • methods'],['Book 04','Future book slot','IO links • questions • notes']];return <section className="page"><PageHero eyebrow="Books" title="Build a library you can actually revise from." text="Your friend can add the final book content later. The library already has the structure for useful study profiles without using copyrighted commercial covers." icon={<LibraryBig/>}/><div className="book-toolbar"><div className="inline-search"><Search/><input placeholder="Search books (content coming soon)" disabled/></div><span>Custom LitLab covers • no commercial cover art</span></div><div className="book-grid">{slots.map((b,i)=><button key={b[0]} className={'book-card book'+i+(selected===i?' selected':'')} onClick={()=>setSelected(i)}><div className="book-cover"><span>{b[0]}</span><div className="cover-mark">LL</div><i></i><i></i><i></i></div><h3>{b[1]}</h3><p>{b[2]}</p><b>Open template <ArrowRight/></b></button>)}</div><div className="book-template"><div><span className="eyebrow">Book profile template</span><h2>{slots[selected][1]}</h2><p>When the actual title is added, this profile will organise everything a student needs to revisit quickly.</p></div><div className="profile-grid">{['Quick overview','Characters','Themes','Symbols / motifs','Context','Authorial choices','Important moments','Paper 2 connections','IO connections','Think deeper','Student note prompts'].map(x=><div key={x}><Check/><span>{x}</span></div>)}</div></div><CompletionAction id="books" isDone={done.includes('books')} mark={mark} nextLabel="Continue to Extended Essay" next="ee" go={go}/></section>}

function EEPage({go,done,mark}:{go:Go;done:string[];mark:(id:string)=>void}){const[stage,setStage]=useState(0);const stages=[['TOO BROAD','How is identity shown in literature?','The topic is enormous: too many texts, methods and possible directions.'],['NARROWER','How is identity presented in one selected novel?','Now the work is limited, but the question may still invite description rather than a focused argument.'],['FOCUSED','How does a recurring narrative choice shape the presentation of identity in the selected novel?','The question now identifies a method and a specific conceptual focus.'],['ANALYTICAL','Refine further using your actual text, evidence, subject guidance and supervisor feedback.','A real research question should grow from genuine reading and research — not from copying a generated sentence.']];return <section className="page"><PageHero eyebrow="Extended Essay" title="Turn curiosity into a question worth investigating." text="The EE is a DP core research project. This page is ready for your friend’s English-specific research while already teaching the most important starting habit: narrowing scope." icon={<SearchCheck/>}/><div className="ee-overview"><div><h2>What belongs here later</h2><div className="topic-map compact">{['What is the EE?','Is English right for me?','Area of interest','Topic','Research question','Narrowing scope','Research','Sources','Planning','Analysis vs summary','Argument','Referencing','Supervisor work','Common mistakes','Checklist'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b></div>)}</div></div><div className="official-card"><CircleHelp/><h3>Verified DP core point</h3><p>The Extended Essay is an independent research project within the Diploma Programme core. Current IB information describes it as culminating in a 4,000-word paper.</p><a href="https://ibo.org/programmes/diploma-programme/curriculum/dp-core/extended-essay/" target="_blank" rel="noopener noreferrer">Official IB page <ExternalLink/></a></div></div><div className="rq-lab"><span className="eyebrow"><FlaskConical/> Research Question Lab</span><h2>Make the scope smaller and the thinking sharper.</h2><div className="rq-stages">{stages.map((x,i)=><button className={stage===i?'active':''} onClick={()=>setStage(i)} key={x[0]}><span>{i+1}</span>{x[0]}</button>)}</div><div className="rq-screen"><span>{stages[stage][0]}</span><h3>{stages[stage][1]}</h3><p>{stages[stage][2]}</p><div className="lab-meter"><i style={{width:`${25*(stage+1)}%`}}/></div></div><Callout type="tip" title="Use the lab to learn the process">Do not treat demo questions as ready-to-submit research questions. Your real question should come from your own reading, research and supervisor guidance.</Callout></div><CompletionAction id="ee" isDone={done.includes('ee')} mark={mark} nextLabel="Return Home" next="home" go={go}/></section>}

function GlossaryPage(){const[q,setQ]=useState(''),[cat,setCat]=useState('All');const cats=['All',...Array.from(new Set(glossary.map(g=>g.category)))];const list=glossary.filter(g=>(cat==='All'||g.category===cat)&&(g.term+' '+g.definition).toLowerCase().includes(q.toLowerCase()));return <section className="page"><PageHero eyebrow="Reference" title="LitLab Glossary" text="Plain-language starting points for terms you will keep seeing." icon={<BookOpen/>}/><div className="glossary-tools"><div className="inline-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search terms…"/></div><div className="filter-chips">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></div><div className="glossary-grid">{list.map(g=><details key={g.term}><summary><span><b>{g.term}</b><small>{g.category}</small></span><ChevronDown/></summary><p>{g.definition}</p>{g.example&&<em>{g.example}</em>}</details>)}</div></section>}

function AboutPage(){return <section className="page"><PageHero eyebrow="About / CAS" title="Built by students, for students." text="LitLab is a student-created educational resource designed to make the first steps into DP English clearer and more approachable." icon={<Sparkles/>}/><div className="creator-cards"><div><span>Website / Start Here</span><h2>Rayan Sayed Ahmad</h2><p>Website development, design, interactive experience, technical implementation, Start Here / Overview and content integration.</p></div><div><span>Research / Content</span><h2>Elena Bizri</h2><p>Research and future content for Papers, IO, Extended Essay and Books, plus proofreading and explanation review.</p></div><div><span>Together</span><h2>Plan • test • improve</h2><p>Student feedback, evaluation, improvements and CAS reflection.</p></div></div><div className="about-grid"><div><h2>Why LitLab?</h2><p>Starting DP English can feel like being introduced to an entirely new vocabulary. LitLab is meant to give students a clearer map, then let them go deeper when they actually need a topic.</p><p>It is intentionally an evolving project. Detailed academic sections will be added after research rather than filled with invented “official” rules.</p></div><div className="insta-card"><Instagram/><span>Follow our DP journey</span><h2>@rhhs.ibdp.27</h2><a className="btn insta" href={INSTAGRAM} target="_blank" rel="noopener noreferrer">View our Instagram <ExternalLink/></a></div></div><div className="source-box"><h2>Official sources used for course-level facts</h2>{officialSources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.label}<ExternalLink/></a>)}</div><Callout type="official" title="Independent resource">LitLab is an independent student-made educational resource and is not affiliated with or endorsed by the International Baccalaureate Organization.</Callout></section>}

function PageHero({eyebrow,title,text,icon}:{eyebrow:string;title:string;text:string;icon:React.ReactNode}){return <header className="page-hero"><div><span className="eyebrow">{icon}{eyebrow}</span><h1>{title}</h1><p>{text}</p></div><div className="page-hero-mark">{icon}<span>LITLAB</span></div></header>}
function SectionHead({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <div className="section-head"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}

function Footer({go}:{go:Go}){return <footer><div className="footer-brand"><Logo/><p>Explore. Analyse. Understand.</p><span>Created by Rayan Sayed Ahmad & Elena Bizri</span></div><div><b>Explore</b>{nav.map(([s,l])=><button key={s} onClick={()=>go(s)}>{l}</button>)}<button onClick={()=>go('glossary')}>Glossary</button></div><div><b>Project</b><button onClick={()=>go('about')}>About / CAS</button><a href={INSTAGRAM} target="_blank" rel="noopener noreferrer"><Instagram/> @rhhs.ibdp.27</a></div><p className="legal">LitLab is an independent student-made educational resource and is not affiliated with or endorsed by the International Baccalaureate Organization.</p></footer>}

createRoot(document.getElementById('root')!).render(<App/>);
