import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Search,Sun,Moon,Menu,X,Compass,ArrowRight,Bookmark,Check,Clock,ChevronRight,BookOpen,Sparkles}from'lucide-react';import{guides,glossary,tips,Guide}from'./content';import'./styles.css';
import CardSwipe from './CardSwipe';
const Logo=()=> <div className="brand"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M7 10c5 0 9 2 13 6 4-4 8-6 13-6v20c-5 0-9 2-13 5-4-3-8-5-13-5z"/><path d="m20 3 2.5 9.5L32 15l-9.5 2.5L20 27l-2.5-9.5L8 15l9.5-2.5z"/></svg><span>Northstar <b>English</b></span></div>;
const badge=(s:string)=><span className={'badge '+s}>{s==='verified'?'Student-reviewed':s==='demo'?'Demo content':'Coming soon'}</span>;
const storedList=(key:string):string[]=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return[]}};
function App(){
 const [page,setPage]=useState(location.hash.slice(1)||'home'),[dark,setDark]=useState(localStorage.theme==='dark'),[menu,setMenu]=useState(false),[search,setSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false),[saved,setSaved]=useState<string[]>(()=>storedList('saved')),[done,setDone]=useState<string[]>(()=>storedList('done')),[focus,setFocus]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{const f=()=>{setPage(location.hash.slice(1)||'home');scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearchOpen(true)}if(e.key==='Escape'){setSearchOpen(false);setMenu(false)}};addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[]);
 const go=(p:string)=>{location.hash=p;setMenu(false)};
 const toggleSave=(s:string)=>setSaved(v=>{const n=v.includes(s)?v.filter(x=>x!==s):[...v,s];localStorage.saved=JSON.stringify(n);return n});
 const finish=(s:string)=>setDone(v=>{const n=v.includes(s)?v.filter(x=>x!==s):[...v,s];localStorage.done=JSON.stringify(n);return n});
 const results=useMemo(()=>{const q=search.toLowerCase();return q?[...guides.map(g=>({title:g.title,sub:g.description,to:g.slug})),...glossary.map(([title,sub])=>({title,sub,to:'glossary'}))].filter(x=>(x.title+x.sub).toLowerCase().includes(q)):[]},[search]);
 const guide=guides.find(g=>g.slug===page);
 return <><header><a href="#home" aria-label="Northstar English home"><Logo/></a><nav aria-label="Main navigation">{['Start','Paper 1','Paper 2','IO','Works'].map((n,i)=><a key={n} href={'#'+['start','paper-1','paper-2','io','works'][i]}>{n}</a>)}</nav><div className="actions"><button onClick={()=>setSearchOpen(true)} aria-label="Search"><Search/><span>Search</span><kbd>⌘K</kbd></button><button className="icon" onClick={()=>setDark(!dark)} aria-label="Switch theme">{dark?<Sun/>:<Moon/>}</button><button className="icon mobile" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<div className="mobile-nav">{guides.map(g=><button key={g.slug} onClick={()=>go(g.slug)}>{g.title}</button>)}<button onClick={()=>go('glossary')}>Glossary</button><button onClick={()=>go('about')}>About / CAS</button></div>}
 {searchOpen&&<div className="modal" role="dialog" aria-modal="true" aria-label="Site search" onMouseDown={()=>setSearchOpen(false)}><div className="searchbox" onMouseDown={e=>e.stopPropagation()}><Search/><input aria-label="Search guides and glossary" autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search guides and glossary…"/><button className="icon" aria-label="Close search" onClick={()=>setSearchOpen(false)}><X/></button>{search&&<div className="results">{results.length?results.map(r=><button key={r.title} onClick={()=>{go(r.to);setSearchOpen(false);setSearch('')}}><b>{r.title}</b><span>{r.sub}</span></button>):<p>No result yet. Try a broader word.</p>}</div>}</div></div>}
 <main>{page==='home'?<Home go={go} done={done}/>:guide?<GuidePage guide={guide} saved={saved} done={done} toggleSave={toggleSave} finish={finish} focus={focus} setFocus={setFocus}/>:page==='glossary'?<Glossary/>:page==='saved'?<Saved saved={saved} go={go}/>:<About/>}</main><Footer go={go}/></>
}
function Home({go,done}:{go:(s:string)=>void,done:string[]}){const [answer,setAnswer]=useState('');return <>
 <section className="hero"><div className="aurora"></div><div className="eyebrow"><Sparkles/> A student-made guide for students</div><h1>Find your way through<br/><em>DP English.</em></h1><p>You don’t need to understand everything immediately. Start here, explore what you need, and build confidence one idea at a time.</p><div className="hero-buttons"><button className="primary" onClick={()=>go('start')}>Start here <ArrowRight/></button><button className="secondary" onClick={()=>document.querySelector('#compass')?.scrollIntoView({behavior:'smooth'})}><Compass/> Open the compass</button></div><div className="trust"><span>Independent</span><span>Student-made</span><span>Built to grow</span></div></section>
 <section id="compass" className="section"><div className="section-title"><span>Northstar Compass</span><h2>Where do you want to go?</h2><p>Choose one direction. You can always come back.</p></div><div className="guide-grid">{guides.map((g,i)=><button key={g.slug} className="guide-card" onClick={()=>go(g.slug)}><div className="card-top"><span>0{i+1}</span>{done.includes(g.slug)&&<Check/>}</div><h3>{g.title}</h3><p>{g.description}</p><div>{badge(g.status)}<ChevronRight/></div></button>)}</div></section>
 <section className="swipe-section"><div className="swipe-copy"><span className="eyebrow">Your learning path</span><h2>One good move<br/>at a time.</h2><p>Swipe through a simple way of thinking about DP English. Each card gives you one useful next step—not another wall of information.</p><div className="swipe-note"><Compass/><span>Start anywhere. Your path does not have to be linear.</span></div></div><CardSwipe onNavigate={go}/></section>
 <section className="ink"><div><span className="eyebrow">A gentler first step</span><h2>Confusion is a starting point,<br/>not a verdict.</h2></div><div className="tip"><span>Tip of the visit</span><p>“{tips[Math.floor(Date.now()/86400000)%tips.length]}”</p></div></section>
 <section className="section"><div className="section-title"><span>How it works</span><h2>Small steps. Clear direction.</h2></div><div className="steps">{[['01','Find what you need','Use the Compass or fast search.'],['02','Understand the idea','Read concise explanations and examples.'],['03','Build confidence','Use quick checks and save progress.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div><div className="quiz"><div><span>Quick check</span><h3>What turns an observation into analysis?</h3></div>{['Naming a feature','Explaining how it shapes meaning','Making the sentence longer'].map((x,i)=><button key={x} className={answer===x?(i===1?'right':'wrong'):''} onClick={()=>setAnswer(x)}>{x}{answer===x&&<span>{i===1?'That’s it':'Try again'}</span>}</button>)}</div></section></>}
function GuidePage({guide,saved,done,toggleSave,finish,focus,setFocus}:{guide:Guide,saved:string[],done:string[],toggleSave:(s:string)=>void,finish:(s:string)=>void,focus:boolean,setFocus:(x:boolean)=>void}){return <article className={'guide '+(focus?'focus':'')}><div className="crumb">Compass <ChevronRight/> {guide.title}</div><header className="guide-head"><div><span className="eyebrow">{guide.kicker}</span><h1>{guide.title}</h1><p>{guide.description}</p><div className="meta">{badge(guide.status)}<span><Clock/> {guide.minutes} min read</span></div></div><div className="guide-tools"><button onClick={()=>toggleSave(guide.slug)}><Bookmark fill={saved.includes(guide.slug)?'currentColor':'none'}/>{saved.includes(guide.slug)?'Saved':'Save'}</button><button onClick={()=>setFocus(!focus)}><BookOpen/>{focus?'Exit focus':'Focus mode'}</button></div></header>{guide.sections.length?<div className="article-layout"><aside><b>On this page</b>{guide.sections.map(s=><a key={s.title} href={'#'+s.title.replaceAll(' ','-')}>{s.title}</a>)}</aside><div className="prose">{guide.sections.map((s,i)=><section key={s.title} id={s.title.replaceAll(' ','-')}><span className="num">0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p>{s.tip&&<div className="callout"><Compass/><div><b>Northstar tip</b><p>{s.tip}</p></div></div>}</section>)}<button className={'complete '+(done.includes(guide.slug)?'done':'')} onClick={()=>finish(guide.slug)}><Check/>{done.includes(guide.slug)?'Marked complete':'Mark this guide complete'}</button></div></div>:<Empty guide={guide}/>}</article>}
function Empty({guide}:{guide:Guide}){return <div className="empty"><Compass/><span>{badge(guide.status)}</span><h2>This guide is being built.</h2><p>The structure is ready. Verified student-created material will be added here after research and review—without pretending unfinished content is official guidance.</p><a href="#start">Explore Start Here <ArrowRight/></a></div>}
function Glossary(){const [q,setQ]=useState('');return <section className="page"><span className="eyebrow">Reference desk</span><h1>Global glossary</h1><p>Plain-language starting points. Assessment-specific terms should always be checked against current teacher and official guidance.</p><div className="filter"><Search/><input aria-label="Filter glossary terms" value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter terms"/></div><div className="glossary">{glossary.filter(x=>x.join(' ').toLowerCase().includes(q.toLowerCase())).map(([t,d])=><div key={t}><b>{t}</b><p>{d}</p></div>)}</div></section>}
function Saved({saved,go}:{saved:string[],go:(s:string)=>void}){return <section className="page"><span className="eyebrow">Your space</span><h1>Saved for later</h1>{saved.length?<div className="guide-grid">{saved.map(s=>{const g=guides.find(x=>x.slug===s);return g?<button key={s} className="guide-card" onClick={()=>go(s)}><h3>{g.title}</h3><p>{g.description}</p><div>{badge(g.status)}<ChevronRight/></div></button>:null})}</div>:<div className="empty"><Bookmark/><h2>Nothing saved yet.</h2><p>Use the bookmark button on a guide to keep it here.</p></div>}</section>}
function About(){return <section className="page"><span className="eyebrow">About the project</span><h1>Made by students,<br/>for students.</h1><p>Northstar English is an evolving IB CAS project: a practical service for students entering DP English and a creative collaboration between two student makers.</p><div className="roles"><div><span>Student 1</span><h2>Website / Technical Lead</h2><p>Architecture, design, development, accessibility, interactions, testing and content integration.</p></div><div><span>Student 2</span><h2>Research / Content Lead</h2><p>Research, academic guides, works, proofreading and making explanations understandable.</p></div><div><span>Together</span><h2>Plan, listen, improve</h2><p>Collecting student feedback, reflecting, evaluating usefulness and improving the service over time.</p></div></div><div className="disclaimer"><b>Independent resource</b><p>Northstar English is an independent student-made educational resource. It is not affiliated with, endorsed by, or an official resource of the International Baccalaureate Organization.</p></div></section>}
function Footer({go}:{go:(s:string)=>void}){return <footer><div><Logo/><p>Find your way through DP English.</p></div><div><b>Explore</b><button onClick={()=>go('start')}>Start Here</button><button onClick={()=>go('glossary')}>Glossary</button><button onClick={()=>go('saved')}>Saved</button></div><div><b>Project</b><button onClick={()=>go('about')}>About / CAS</button><a href="https://github.com/veyro-lb/northstar">GitHub</a></div><p className="legal">Independent student-made resource. Not affiliated with or endorsed by the International Baccalaureate Organization.</p></footer>}
createRoot(document.getElementById('root')!).render(<App/>);
