import './paper2-guide.css';
import{comparisonPairs,comparativeVocabulary,evidenceChecklist,miniExercises,mistakes,paragraphPairs,plans,practices,questionBreakdowns,themes,thesisPairs}from'./paper2-data';

const route=()=>location.hash.slice(1).split('#')[0]||'home';
const sections=[
 ['p2-overview','Overview'],['p2-question','Question'],['p2-works','Choose works'],['p2-comparison','Comparison'],['p2-vocab','Vocabulary'],['p2-thesis','Thesis'],['p2-paragraphs','Paragraphs'],['p2-themes','Themes'],['p2-methods','Methods'],['p2-evidence','Evidence'],['p2-planning','Planning'],['p2-mistakes','Mistakes'],['p2-practice','Practice']
] as const;

function esc(value:string){return value.replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]||ch))}
function list(items:string[]){return `<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}
function done(){try{return JSON.parse(localStorage.getItem('litlabDone')||'[]') as string[]}catch{return[]}}
function setDone(){const values=done();if(!values.includes('paper-2'))values.push('paper-2');localStorage.setItem('litlabDone',JSON.stringify(values))}

function formatTable(){return `<div class="p2-format-card">
 <div class="p2-table-title"><div><span>SL vs HL • QUICK REFERENCE</span><b>Paper 2 format at a glance</b></div><small>Working course reference</small></div>
 <div class="p2-table-wrap"><table class="p2-format-table"><thead><tr><th>Level</th><th>Question</th><th>Works</th><th>Time</th><th>Marks</th><th>Weighting</th><th>Mode</th></tr></thead><tbody>
 <tr><td data-label="Level"><strong class="p2-level">SL</strong></td><td data-label="Question"><b>Choose 1 of 4</b><span>unseen essay questions</span></td><td data-label="Works"><b>2 studied works</b></td><td data-label="Time"><strong>1h 45m</strong></td><td data-label="Marks"><strong>30</strong></td><td data-label="Weighting"><strong class="p2-weight">35%</strong></td><td data-label="Mode"><b>Closed book</b></td></tr>
 <tr><td data-label="Level"><strong class="p2-level hl">HL</strong></td><td data-label="Question"><b>Choose 1 of 4</b><span>unseen essay questions</span></td><td data-label="Works"><b>2 studied works</b></td><td data-label="Time"><strong>1h 45m</strong></td><td data-label="Marks"><strong>30</strong></td><td data-label="Weighting"><strong class="p2-weight">25%</strong></td><td data-label="Mode"><b>Closed book</b></td></tr>
 </tbody></table></div><p class="p2-format-caption">Use your teacher or current course guide to confirm final assessment details before an exam. The learning strategies below do not depend on those figures.</p></div>`}

function template(){return `<section class="page paper2-guide-page" aria-labelledby="paper2-title">
 <div class="p2-breadcrumb"><button type="button" data-go="papers">Papers</button><span>›</span><strong>Paper 2</strong></div>
 <header class="p2-hero"><div class="p2-hero-copy"><span class="p2-eyebrow">✦ PAPER 2 • LITLAB STUDY GUIDE</span><h1 id="paper2-title">Paper 2</h1><h2>Build one comparative argument.</h2><p>Bring two studied works into conversation. Strong Paper 2 writing compares <b>ideas, methods, and significance</b> instead of producing two separate mini-essays.</p><div class="p2-hero-actions"><button class="btn primary" type="button" data-scroll="p2-question">Start with the question →</button><button class="btn secondary" type="button" data-go="paper-1">Switch to Paper 1</button></div></div><div class="p2-hero-model" aria-hidden="true"><div><span>WORK A</span><i>↔</i><span>WORK B</span></div><b>SHARED IDEA</b><em>+</em><b>DIFFERENT METHOD</b><em>→</em><strong>COMPARATIVE ARGUMENT</strong></div></header>
 <nav class="p2-nav" aria-label="Paper 2 guide sections"><span>ON THIS GUIDE</span>${sections.map(([id,label],i)=>`<button type="button" data-scroll="${id}" class="${i===0?'current':''}">${label}</button>`).join('')}</nav>

 <section id="p2-overview" class="p2-section" data-p2-section><div class="p2-section-head"><span>01 • OVERVIEW</span><h2>Paper 2 is a comparative essay, not two book reports.</h2><p>You answer one unseen general question using two works studied in class. The comparison itself has to drive the argument.</p></div>${formatTable()}
 <div class="p2-overview-grid"><article><span>THE JOB</span><h3>Put two works into conversation.</h3><p>Organize paragraphs around shared ideas, choices, tensions, or effects. The relationship between the works should be visible throughout.</p></article><article><span>THE EVIDENCE</span><h3>Detailed reference beats quotation quantity.</h3><p>You are working from memory. Know precise scenes, moments, structural choices, symbols, and short phrases where useful. You do not need to memorize pages of quotations.</p></article><article><span>THE BIG TRAP</span><h3>Do not memorize one fixed essay.</h3><p>The question is unseen. Prepare flexible knowledge that can be recombined instead of forcing a rehearsed answer onto the wrong prompt.</p></article></div>
 <div class="p2-skill-grid"><div><b>Understanding</b><p>Know both works accurately and interpret them in relation to the question.</p></div><div><b>Analysis & evaluation</b><p>Explain how authorial choices shape meaning and compare those methods.</p></div><div><b>Focus & organization</b><p>Keep every paragraph attached to the question and the comparative thesis.</p></div><div><b>Language</b><p>Write clearly, precisely, and in an appropriate analytical register.</p></div></div>
 <div class="p2-restrictions"><b>Work selection reminder</b><p>The source material states that a work used for the Individual Oral cannot be reused for Paper 2, and at HL a work used for the HL Essay cannot be reused either. Confirm your own course choices with your teacher.</p></div></section>

 <section id="p2-question" class="p2-section" data-p2-section><div class="p2-section-head"><span>02 • UNDERSTANDING THE QUESTION</span><h2>Decode the prompt before choosing the books.</h2><p>The most dangerous Paper 2 mistake happens before writing begins: seeing one familiar word and forcing prepared material toward it.</p></div>
 <div class="p2-question-process">${['Read the whole question twice.','Underline the key concept.','Identify the instruction verb.','Notice qualifiers or restrictions.','Then decide which two works genuinely fit.'].map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><p>${x}</p></div>`).join('')}</div>
 <div class="p2-decoder"><div class="p2-decoder-tabs">${questionBreakdowns.map((x,i)=>`<button type="button" data-question-example="${i}" class="${i===0?'active':''}">Example ${String.fromCharCode(65+i)}</button>`).join('')}</div><article class="p2-decoder-card"><span>EXAMPLE QUESTION</span><h3>${esc(questionBreakdowns[0].question)}</h3><div><small>KEY CONCEPT</small><p>${esc(questionBreakdowns[0].concept)}</p></div><div><small>INSTRUCTION</small><p>${esc(questionBreakdowns[0].instruction)}</p></div><div><small>WHAT THIS REALLY NEEDS</small><p>${esc(questionBreakdowns[0].breakdown)}</p></div></article></div></section>

 <section id="p2-works" class="p2-section" data-p2-section><div class="p2-section-head"><span>03 • CHOOSING TWO WORKS</span><h2>Choose the pair that can answer this question — not simply your two favorite books.</h2><p>A shared theme is only the starting point. A strong pairing gives you enough method, contrast, evidence, and depth to sustain three developed comparative arguments.</p></div>
 <div class="p2-fit-grid"><article><span>01</span><h3>Concept fit</h3><p>Do both works engage seriously with the question’s central idea, rather than only touching it briefly?</p></article><article><span>02</span><h3>Method fit</h3><p>Can you explain how each writer constructs that idea through structure, perspective, symbolism, characterization, dialogue, form, or another choice?</p></article><article><span>03</span><h3>Evidence fit</h3><p>Can you recall precise scenes or moments from both works that support the comparison?</p></article><article><span>04</span><h3>Difference fit</h3><p>Can you make a meaningful contrast in method, scale, outcome, tone, or interpretation — not only list similarities?</p></article></div>
 <div class="p2-sim-diff"><div><b>SIMILARITIES GIVE YOU A BASE</b><p>Shared ground helps establish what both works care about.</p></div><span>+</span><div><b>DIFFERENCES GIVE YOU AN ARGUMENT</b><p>Contrasts often reveal why the two writers’ treatments matter differently.</p></div></div></section>

 <section id="p2-comparison" class="p2-section" data-p2-section><div class="p2-section-head"><span>04 • COMPARISON</span><h2>Move from “both” to “so what?”</h2><p>Comparison becomes analytical when you explain not only that two works differ, but <b>how the difference is constructed and what it reveals</b>.</p></div>
 <div class="p2-progression"><span>Both show power.</span><i>→</i><span>Both show power differently.</span><i>→</i><span>Institutional vs personal power.</span><i>→</i><strong>Different methods reveal different ideas about responsibility.</strong></div>
 <div class="p2-pair-grid">${comparisonPairs.map((x,i)=>`<details ${i===0?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span><b>${esc(x.weak)}</b><em>Improve →</em></summary><div><small>STRONGER COMPARISON</small><p>${esc(x.strong)}</p></div></details>`).join('')}</div></section>

 <section id="p2-vocab" class="p2-section" data-p2-section><div class="p2-section-head"><span>05 • COMPARATIVE VOCABULARY</span><h2>Use connective language to clarify thinking, not to fake comparison.</h2><p>You do not need “similarly” at the start of every sentence. Strong comparison can be built directly into sentence grammar.</p></div>
 <div class="p2-vocab-grid"><article><span>SIMILARITY</span>${comparativeVocabulary.similarity.map(x=>`<b>${esc(x)}</b>`).join('')}</article><article><span>CONTRAST</span>${comparativeVocabulary.contrast.map(x=>`<b>${esc(x)}</b>`).join('')}</article><article><span>DEGREE / NUANCE</span>${comparativeVocabulary.nuance.map(x=>`<b>${esc(x)}</b>`).join('')}</article></div>
 <div class="p2-wording-example"><div><small>MECHANICAL</small><p>“Similarly, Work B also uses imagery.”</p></div><i>→</i><div><small>MORE NATURAL</small><p>“Work B achieves a comparable effect through imagery, though it does so more sparingly than Work A.”</p></div></div></section>

 <section id="p2-thesis" class="p2-section" data-p2-section><div class="p2-section-head"><span>06 • COMPARATIVE THESIS</span><h2>A thesis should establish the relationship between the works.</h2><p>Answer the actual question, include both works, make an arguable conceptual claim, and bring authorial methods into the comparison where useful.</p></div>
 <div class="p2-thesis-formula"><span>QUESTION FOCUS</span><i>+</i><span>WORK A METHOD / VIEW</span><i>↔</i><span>WORK B METHOD / VIEW</span><i>→</i><strong>COMPARATIVE SIGNIFICANCE</strong></div>
 <div class="p2-thesis-table"><div class="p2-table-title"><div><span>WEAK → STRONGER</span><b>Five comparative thesis upgrades</b></div></div><div class="p2-table-wrap"><table><thead><tr><th>Weak thesis</th><th>Stronger thesis</th><th>What improved</th></tr></thead><tbody>${thesisPairs.map(x=>`<tr><td data-label="Weak thesis" class="p2-weak">${esc(x.weak)}</td><td data-label="Stronger thesis"><b>${esc(x.strong)}</b></td><td data-label="What improved">${esc(x.improved)}</td></tr>`).join('')}</tbody></table></div></div></section>

 <section id="p2-paragraphs" class="p2-section" data-p2-section><div class="p2-section-head"><span>07 • PARAGRAPH STRUCTURE</span><h2>Integrate the comparison inside each paragraph.</h2><p>A useful paragraph moves between both works in service of one shared sub-argument.</p></div>
 <div class="p2-paragraph-chain">${['Shared claim','Work A evidence','A choice + effect','Pivot','Work B evidence','B choice + comparison','Synthesis'].map((x,i)=>`<span>${x}</span>${i<6?'<i>→</i>':''}`).join('')}</div>
 <div class="p2-paragraph-pairs">${paragraphPairs.map((x,i)=>`<details ${i===0?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span><b>Paragraph upgrade</b><em>Open example</em></summary><div class="p2-para-compare"><article><small>WEAK</small><p>${esc(x.weak)}</p></article><article><small>STRONGER</small><p>${esc(x.strong)}</p></article></div><p class="p2-annotation"><b>Why it improves:</b> ${esc(x.note)}</p></details>`).join('')}</div>
 <div class="p2-warning"><b>Avoid the “Book A + Book B sentence” pattern.</b><p>An entire paragraph on one work followed by one token sentence on the second work is not integrated comparison.</p></div></section>

 <section id="p2-themes" class="p2-section" data-p2-section><div class="p2-section-head"><span>08 • THEMES / CONCEPTS</span><h2>Use theme labels as prompts, not as arguments.</h2><p>For each studied work, identify only the 3–4 concepts it engages with seriously and record its <b>specific angle</b> on each one.</p></div><div class="p2-theme-cloud">${themes.map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="p2-theme-example"><b>“Family” is not enough.</b><p>One work might frame family as inherited obligation while another frames it as chosen belonging. The difference is the revision material.</p></div></section>

 <section id="p2-methods" class="p2-section" data-p2-section><div class="p2-section-head"><span>09 • AUTHORIAL CHOICE COMPARISON</span><h2>Compare how meaning is made, not only what the works “say.”</h2><p>Theme-only comparison has a ceiling. Method comparison asks what each writer chooses to do and why that difference matters.</p></div>
 <div class="p2-method-demo"><div class="p2-method-work"><span>INVENTED WORK A • NOVEL</span><h3>Power through symbolism</h3><p>A decaying family estate physically crumbles as the patriarch’s authority weakens.</p></div><i>↔</i><div class="p2-method-work"><span>INVENTED WORK B • PLAY</span><h3>Power through dialogue</h3><p>A character’s shift from formal to informal address tracks a subtle reversal of power across scenes.</p></div></div>
 <div class="p2-method-upgrade"><small>THEME ONLY</small><p>“Both works show power declining.”</p><small>METHOD COMPARISON</small><p>“Work A externalizes the decline of power through a physical symbol that decays over time, while Work B enacts the same shift through the moment-to-moment medium of dialogue — reflecting the different scales at which novel and play can represent change.”</p></div><p class="p2-placeholder-note">The demonstration uses invented works so it does not pretend to describe your class texts. Replace these examples later when LitLab’s Book Profiles contain the actual studied works.</p></section>

 <section id="p2-evidence" class="p2-section" data-p2-section><div class="p2-section-head"><span>10 • EVIDENCE PREPARATION</span><h2>Memorize flexible building blocks, not an entire essay.</h2><p>Closed-book preparation works best when each remembered moment can answer more than one possible question.</p></div>
 <div class="p2-memory-formula"><span>MOMENT</span><i>→</i><span>CHOICE</span><i>→</i><span>EFFECT</span><i>→</i><span>THEME(S)</span><i>→</i><strong>BEST COMPARISON + WHY</strong></div>
 <div class="p2-evidence-grid">${evidenceChecklist.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><p>${esc(x)}</p></article>`).join('')}</div><div class="p2-strategy"><b>STUDENT STRATEGY</b><p>Create one physical or digital index card per work with these categories, then quiz yourself from the card rather than rereading full essays.</p></div></section>

 <section id="p2-planning" class="p2-section" data-p2-section><div class="p2-section-head"><span>11 • PLANNING</span><h2>Plan the comparison before writing the introduction.</h2><p>The five models below use invented works — <b>The Salt House</b> and <b>Undertow</b> — only to demonstrate a reusable planning structure.</p></div><div class="p2-plan-tabs">${plans.map((x,i)=>`<button type="button" data-plan="${i}" class="${i===0?'active':''}">${esc(x.title)}</button>`).join('')}</div><article class="p2-plan-card"></article></section>

 <section id="p2-mistakes" class="p2-section" data-p2-section><div class="p2-section-head"><span>12 • COMMON MISTAKES</span><h2>Most Paper 2 problems are structural before they are grammatical.</h2><p>Open a mistake to see why it weakens the essay, how to fix it, and what the fix looks like.</p></div><div class="p2-mistake-grid">${mistakes.map((x,i)=>`<details><summary><span>${String(i+1).padStart(2,'0')}</span><b>${esc(x.title)}</b><em>+</em></summary><div><section><small>WHY IT IS WEAK</small><p>${esc(x.why)}</p></section><section><small>FIX</small><p>${esc(x.fix)}</p></section><section><small>EXAMPLE</small><p>${esc(x.example)}</p></section></div></details>`).join('')}</div></section>

 <section id="p2-practice" class="p2-section" data-p2-section><div class="p2-section-head"><span>13 • ORIGINAL PRACTICE</span><h2>Fifteen prompts designed for flexible comparative preparation.</h2><p>These are original LitLab practice questions, not past-paper questions and not official IB assessment material. Use them to practice decoding, pairing works, planning, and thesis construction.</p></div>
 <div class="p2-practice-search"><label><span>Find a practice focus</span><input type="search" data-practice-search placeholder="Try power, family, structure, setting, ending…"></label><b data-practice-count>${practices.length} questions</b></div>
 <div class="p2-practice-layout"><div class="p2-practice-list"></div><article class="p2-practice-detail"></article></div>
 <div class="p2-mini-lab"><div><span>10 • MINI COMPARISON DRILLS</span><h3>Fast practice without writing a full essay.</h3><p>Choose one pair of works and answer each prompt in 2–3 analytical sentences.</p></div><div class="p2-mini-grid">${miniExercises.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><p>${esc(x)}</p></article>`).join('')}</div></div></section>

 <footer class="p2-finish"><div><span>✦ PAPER 2 STUDY GUIDE</span><h2>Compare deliberately, not mechanically.</h2><p>Know your works, decode the exact question, compare methods as well as ideas, and use every paragraph to develop the relationship between the two texts.</p></div><div><button class="btn primary" type="button" data-p2-complete>${done().includes('paper-2')?'Reviewed ✓':'Mark Paper 2 reviewed'}</button><button class="btn secondary" type="button" data-go="io">Continue to IO →</button></div></footer>
 </section>`}

function renderPlan(page:HTMLElement,index:number){const plan=plans[index];const card=page.querySelector<HTMLElement>('.p2-plan-card');if(!card)return;card.innerHTML=`<span>${esc(plan.title.toUpperCase())}</span><h3>${esc(plan.question)}</h3><div class="p2-plan-thesis"><small>THESIS</small><p>${esc(plan.thesis)}</p></div><div class="p2-plan-points">${plan.paragraphs.map((x,i)=>`<div><b>Paragraph ${i+1}</b><p>${esc(x)}</p></div>`).join('')}</div><div class="p2-plan-bottom"><div><small>EVIDENCE / MOMENTS</small><p>${esc(plan.evidence)}</p></div><div><small>COMPARISON</small><p>${esc(plan.comparison)}</p></div></div>`}

function renderPractice(page:HTMLElement,query=''){const q=query.trim().toLowerCase();const filtered=practices.map((x,i)=>({x,i})).filter(({x})=>!q||`${x.question} ${x.asking} ${x.goodWorks} ${x.argument} ${x.comparisons}`.toLowerCase().includes(q));const listEl=page.querySelector<HTMLElement>('.p2-practice-list');const count=page.querySelector<HTMLElement>('[data-practice-count]');if(count)count.textContent=`${filtered.length} question${filtered.length===1?'':'s'}`;if(!listEl)return;if(!filtered.length){listEl.innerHTML='<div class="p2-no-match">No practice question matches that search.</div>';page.querySelector<HTMLElement>('.p2-practice-detail')!.innerHTML='';return}listEl.innerHTML=filtered.map(({x,i},n)=>`<button type="button" data-practice="${i}" class="${n===0?'active':''}"><span>Q${String(i+1).padStart(2,'0')}</span><b>${esc(x.question)}</b></button>`).join('');renderPracticeDetail(page,filtered[0].i);listEl.querySelectorAll<HTMLButtonElement>('[data-practice]').forEach(button=>button.addEventListener('click',()=>{listEl.querySelectorAll('button').forEach(x=>x.classList.remove('active'));button.classList.add('active');renderPracticeDetail(page,Number(button.dataset.practice))}))}
function renderPracticeDetail(page:HTMLElement,index:number){const x=practices[index];const detail=page.querySelector<HTMLElement>('.p2-practice-detail');if(!detail)return;detail.innerHTML=`<span>ORIGINAL LITLAB PRACTICE • Q${String(index+1).padStart(2,'0')}</span><h3>${esc(x.question)}</h3><div class="p2-practice-info"><section><small>WHAT IT IS ASKING</small><p>${esc(x.asking)}</p></section><section><small>USEFUL WORK CHARACTERISTICS</small><p>${esc(x.goodWorks)}</p></section><section><small>POSSIBLE ARGUMENT</small><p>${esc(x.argument)}</p></section><section class="wide"><small>POSSIBLE THESIS</small><p><b>${esc(x.thesis)}</b></p></section></div><div class="p2-practice-plan"><b>Three paragraph directions</b>${x.paragraphs.map((p,i)=>`<div><span>${i+1}</span><p>${esc(p)}</p></div>`).join('')}</div><div class="p2-practice-bottom"><div><small>IMPORTANT COMPARISONS</small><p>${esc(x.comparisons)}</p></div><div><small>COMMON MISTAKE</small><p>${esc(x.mistake)}</p></div></div>`}

function bind(page:HTMLElement){page.querySelectorAll<HTMLButtonElement>('[data-go]').forEach(b=>b.addEventListener('click',()=>{location.hash=b.dataset.go||'home'}));page.querySelectorAll<HTMLButtonElement>('[data-scroll]').forEach(b=>b.addEventListener('click',()=>page.querySelector(`#${b.dataset.scroll}`)?.scrollIntoView({behavior:'smooth',block:'start'})));
 page.querySelectorAll<HTMLButtonElement>('[data-question-example]').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.questionExample);const x=questionBreakdowns[i];page.querySelectorAll('[data-question-example]').forEach(b=>b.classList.remove('active'));button.classList.add('active');const card=page.querySelector<HTMLElement>('.p2-decoder-card');if(card)card.innerHTML=`<span>EXAMPLE QUESTION</span><h3>${esc(x.question)}</h3><div><small>KEY CONCEPT</small><p>${esc(x.concept)}</p></div><div><small>INSTRUCTION</small><p>${esc(x.instruction)}</p></div><div><small>WHAT THIS REALLY NEEDS</small><p>${esc(x.breakdown)}</p></div>`}));
 page.querySelectorAll<HTMLButtonElement>('[data-plan]').forEach(button=>button.addEventListener('click',()=>{page.querySelectorAll('[data-plan]').forEach(b=>b.classList.remove('active'));button.classList.add('active');renderPlan(page,Number(button.dataset.plan))}));renderPlan(page,0);
 const search=page.querySelector<HTMLInputElement>('[data-practice-search]');search?.addEventListener('input',()=>renderPractice(page,search.value));renderPractice(page);
 page.querySelector<HTMLButtonElement>('[data-p2-complete]')?.addEventListener('click',e=>{setDone();(e.currentTarget as HTMLButtonElement).textContent='Reviewed ✓';(e.currentTarget as HTMLButtonElement).classList.add('reviewed')});
 const nav=[...page.querySelectorAll<HTMLButtonElement>('.p2-nav [data-scroll]')];const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;nav.forEach(b=>b.classList.toggle('current',b.dataset.scroll===visible.target.id))},{rootMargin:'-25% 0px -60% 0px',threshold:[0,.2,.5]});page.querySelectorAll<HTMLElement>('[data-p2-section]').forEach(s=>observer.observe(s));
}

let mounting=false;
function mount(){if(route()!=='paper-2')return;const main=document.querySelector<HTMLElement>('main#main');if(!main||mounting)return;mounting=true;main.classList.add('paper2-guide-main');let page=main.querySelector<HTMLElement>('.paper2-guide-page');if(!page){main.insertAdjacentHTML('beforeend',template());page=main.querySelector<HTMLElement>('.paper2-guide-page')!;bind(page)}mounting=false}
function unmount(){const main=document.querySelector<HTMLElement>('main#main');main?.classList.remove('paper2-guide-main');main?.querySelector('.paper2-guide-page')?.remove()}
function sync(){setTimeout(()=>{if(route()==='paper-2')mount();else unmount()},90)}
const root=document.getElementById('root');if(root)new MutationObserver(()=>{if(route()==='paper-2'&&!document.querySelector('.paper2-guide-page'))mount()}).observe(root,{childList:true,subtree:true});
window.addEventListener('hashchange',sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync();
