export type QuestionBreakdown={question:string;concept:string;instruction:string;breakdown:string};
export type ComparisonPair={weak:string;strong:string};
export type ThesisPair={weak:string;strong:string;improved:string};
export type ParagraphPair={weak:string;strong:string;note:string};
export type Plan={title:string;question:string;thesis:string;paragraphs:string[];evidence:string;comparison:string};
export type Mistake={title:string;why:string;fix:string;example:string};
export type PracticeQuestion={question:string;asking:string;goodWorks:string;argument:string;thesis:string;paragraphs:string[];comparisons:string;mistake:string};

export const questionBreakdowns:QuestionBreakdown[]=[
{question:'Compare and contrast the ways in which two works you have studied explore the tension between individual desire and social expectation.',concept:'The tension between individual desire and social expectation.',instruction:'Compare and contrast — both similarities and differences are expected.',breakdown:'Choose works where a character is genuinely caught between what they want and what society, family, or context expects of them — not works that only mention society in passing.'},
{question:'In what ways, and to what effect, do writers use structure to shape a reader’s understanding of a central relationship?',concept:'Structure’s effect on how a relationship is understood.',instruction:'“In what ways, and to what effect” asks for both method and evaluation.',breakdown:'Favor works where chronology, fragmentation, framing, parallel scenes, pacing, or withheld information actively shape the relationship.'},
{question:'Discuss the significance of setting in shaping meaning in two works you have studied.',concept:'Setting as a meaning-making device, not mere backdrop.',instruction:'“Discuss the significance” requires evaluation of how and how much setting matters.',breakdown:'Choose works where place changes, shapes characters, carries symbolic weight, or actively influences the work’s argument.'},
{question:'Compare the ways two writers use a central symbol or recurring image to develop meaning across a work.',concept:'A symbol or image’s cumulative development of meaning.',instruction:'“Compare the ways” focuses on method, not just what the symbol represents.',breakdown:'You need a recurring image you can trace across the work and explain how its meaning shifts, deepens, or is recontextualized.'}
];

export const comparisonPairs:ComparisonPair[]=[
{weak:'Both works show power.',strong:'Both works interrogate power, but Work A frames it as institutional while Work B frames it as deeply personal.'},
{weak:'Work A has a sad ending and so does Work B.',strong:'Both works resist neat resolution, though Work A’s ambiguous ending suggests unresolved guilt, while Work B’s abrupt ending enacts the very disruption its plot describes.'},
{weak:'Both works use symbolism.',strong:'Both writers rely on a central recurring symbol, but where Work A’s symbol accumulates meaning gradually, Work B’s is introduced late and destabilizes the reader’s prior understanding retroactively.'},
{weak:'Work A is about family and Work B is about family too.',strong:'Family functions very differently in each work: Work A presents it as a site of obligation and constraint, while Work B reconstructs it as a chosen, voluntary bond.'},
{weak:'Both authors use first-person narration.',strong:'Though both narrators speak in first person, Work A’s narrator is retrospective and self-aware, creating dramatic irony, while Work B’s narrator is immersed in the present moment, denying the reader that same distance.'},
{weak:'Both works are set in cities.',strong:'Both writers use an urban setting, but Work A’s city is a source of anonymity and freedom, while Work B’s is oppressive and inescapable — reflecting opposing attitudes toward modernity.'},
{weak:'Work A criticizes society and so does Work B.',strong:'Both works offer social critique, but Work A does so through satire that invites the reader to laugh before it unsettles them, while Work B critiques through tragedy, offering no such comic distance.'},
{weak:'Both texts have unreliable narrators.',strong:'Both narrators withhold information, but Work A’s unreliability stems from self-deception, while Work B’s stems from deliberate, self-aware manipulation of the listener.'},
{weak:'Both works deal with loss.',strong:'Loss operates on different scales in each work: Work A dramatizes a single, personal loss, while Work B uses that emotional register to gesture toward a broader, generational loss.'},
{weak:'The endings are different.',strong:'The two endings diverge sharply in function: Work A closes off interpretation with a clear resolution, while Work B’s open ending deliberately transfers interpretive responsibility onto the reader.'}
];

export const comparativeVocabulary={
similarity:['similarly','likewise','in the same way','both writers','correspondingly','equally'],
contrast:['whereas','while','in contrast','conversely','however','unlike','on the other hand','by comparison'],
nuance:['more explicitly','more subtly','to a greater extent','to a lesser extent','more overtly','less directly']
};

export const thesisPairs:ThesisPair[]=[
{weak:'Both Work A and Work B are about power and show it in different ways.',strong:'While Work A locates power within collapsing institutions, Work B relocates it inside the individual conscience, suggesting two fundamentally different accounts of where responsibility for abuse ultimately resides.',improved:'Names the mechanism of difference and states what that difference reveals.'},
{weak:'Work A and Work B both use symbolism to show loss.',strong:'Though both writers use a central symbol to represent loss, Work A’s symbol accumulates meaning gradually across the text, while Work B’s is introduced abruptly near the end, forcing a retroactive reassessment of everything that came before.',improved:'Moves from a shared technique to its distinct function in each work.'},
{weak:'The two books have similar themes but different settings.',strong:'Setting functions as more than backdrop in both works: Work A’s confined domestic setting mirrors its characters’ emotional restriction, while Work B’s sprawling, unstable setting reflects its characters’ fractured sense of belonging.',improved:'Replaces a vague observation with a precise claim about setting’s function.'},
{weak:'Both authors write about family relationships.',strong:'Both writers position family as a site of unresolved obligation, but Work A ultimately affirms the possibility of reconciliation while Work B refuses it, offering a more pessimistic view of what family bonds can survive.',improved:'Adds an evaluative dimension that gives the comparison a real argument.'},
{weak:'Work A and Work B both have unreliable narrators, which is interesting.',strong:'Both narrators withhold the truth from the reader, but where Work A’s unreliability arises from genuine self-deception, Work B’s is a deliberate, controlled manipulation — a distinction that shapes how much sympathy each narrator ultimately earns.',improved:'Replaces vague judgment with a precise mechanism and consequence.'}
];

export const paragraphPairs:ParagraphPair[]=[
{weak:'In Work A, the main character feels trapped by her family. The writer shows this through the setting of the small house. In Work B, the main character also feels trapped, but by his job instead.',strong:'Both writers use confined physical spaces to externalize a character’s psychological entrapment, though the source of that entrapment differs sharply. In Work A, the small, airless house becomes a spatial metaphor for inherited family obligation. Work B achieves a comparable effect through office spaces, but where Work A’s confinement is domestic and inherited, Work B’s is professional and chosen, suggesting a more self-inflicted form of entrapment. This distinction matters: Work A critiques inherited obligation, while Work B critiques self-imposed ambition.',note:'The stronger version integrates both works within one argument and closes by explaining what the comparison reveals.'},
{weak:'Work A uses a lot of imagery of water. Work B also uses water imagery. Both are effective.',strong:'Water imagery recurs in both works, but the two writers use it to opposing symbolic ends. In Work A, water is associated with cleansing and renewal, appearing at moments of emotional release. Work B inverts this association: recurring flood imagery signals danger and loss of control. Where Work A’s water imagery offers the possibility of emotional resolution, Work B’s denies it, reinforcing the bleaker trajectory of its narrative.',note:'The stronger version names the shared device precisely and builds around a genuine contrast rather than simply calling both effective.'},
{weak:'The ending of Work A is happy. The ending of Work B is sad. This shows they are different.',strong:'The two endings diverge in a way that reflects each work’s differing view of resolution itself. Work A resolves its central conflict through reconciliation, offering narrative closure. Work B, in contrast, ends mid-conversation, denying such resolution and transferring interpretive responsibility onto the reader. This suggests that while Work A ultimately affirms the possibility of repair, Work B is more skeptical, refusing the comfort of closure.',note:'The stronger version moves beyond emotional labels into what each ending’s structure suggests about the work’s larger argument.'}
];

export const themes=['power','identity','freedom','conflict','gender','belonging','class','memory','relationships','society','isolation','authority','morality','transformation','family','oppression','guilt','justice','appearance vs. reality','coming of age','voice / silence'];

export const evidenceChecklist=[
'8–12 important scenes or moments per work, spread across beginning, middle, and end.',
'A handful of short, memorable quotations where genuinely useful — not paragraphs.',
'Main characters and their central relationships or conflicts.',
'Recurring symbols and motifs, including how their meaning develops.',
'Key structural moments: opening, ending, major shifts, framing, non-linear elements.',
'The 3–4 authorial choices most central to how the work creates meaning.',
'The 3–4 themes or concepts the work engages with seriously.'
];

export const plans:Plan[]=[
{title:'Plan 1 • Desire vs expectation',question:'Compare and contrast the ways in which two works explore the tension between individual desire and social or familial expectation.',thesis:'While both The Salt House and Undertow dramatize a character caught between personal desire and inherited obligation, The Salt House ultimately affirms the possibility of resolution, while Undertow insists that some obligations cannot be escaped without cost.',paragraphs:['Compare the protagonists’ desire to leave and the different sources of obligation.','Compare how each work uses the home or house as a symbol of obligation.','Compare the differing resolutions — reconciliation versus irrecoverable rupture — and what each suggests about the cost of choosing individual desire.'],evidence:'Closing reconciliation on the shore in The Salt House; the final unresolved argument in Undertow.',comparison:'Both use a homecoming structure, but resolve it in opposite ways.'},
{title:'Plan 2 • Structure and relationships',question:'In what ways, and to what effect, do writers use structure to shape a reader’s understanding of a central relationship?',thesis:'The Salt House’s linear structure builds sympathy gradually for its central mother-daughter relationship, while Undertow’s fragmented, non-chronological structure forces the audience to actively reconstruct the sisters’ relationship, mirroring its fractured state.',paragraphs:['Linear chronology as a device for gradual, cumulative sympathy.','Fragmented scene order as a device that formally enacts brokenness.','Evaluate which structural choice more effectively serves each work’s larger argument.'],evidence:'Interwoven flashbacks in Undertow; steady dated diary entries in The Salt House.',comparison:'Both control emotional pacing through structure, but one builds steadily while the other deliberately disorients.'},
{title:'Plan 3 • Setting',question:'Discuss the significance of setting in shaping meaning in two works you have studied.',thesis:'Setting operates as an active force in both works: the eroding coastline in The Salt House materializes the family’s precarious economic and emotional state, while the claustrophobic, unchanging town in Undertow reinforces the sisters’ sense of being trapped by their past.',paragraphs:['The coastline’s erosion as a physical enactment of loss and instability.','The unchanging town as a symbol of stasis and inescapability.','Compare how each setting shapes character choices differently.'],evidence:'The house foundation being undercut by tides; repeated failed attempts to leave the town.',comparison:'Both use setting as more than backdrop, but one represents active loss while the other represents stagnant inescapability.'},
{title:'Plan 4 • Symbol / recurring image',question:'Compare the ways two writers use a central symbol or recurring image to develop meaning across a work.',thesis:'Both works build meaning through water imagery, but The Salt House develops it gradually as a symbol of both danger and renewal, while Undertow’s single, late flood image retroactively recontextualizes the play’s earlier tension.',paragraphs:['Trace gradual accumulation of water or tide imagery.','Analyze the delayed flood image and its retroactive effect.','Evaluate why gradual versus delayed symbolism suits each work.'],evidence:'Recurring tide descriptions marking chapters; the final-scene flood.',comparison:'Same central image, opposite pacing strategies, both tied to family instability.'},
{title:'Plan 5 • Narrative perspective',question:'Compare and contrast how two writers use a narrator or narrative perspective to control what the audience knows.',thesis:'The Salt House’s retrospective first-person narrator creates dramatic irony throughout, while Undertow’s alternating perspective between two sisters withholds full understanding until the final scene.',paragraphs:['Retrospective narration and reader foreknowledge.','Alternating perspective and withheld understanding or suspense.','Compare what each choice reveals about the writer’s priorities: emotional inevitability versus structural surprise.'],evidence:'An early retrospective warning in The Salt House; a late scene in Undertow replayed from the second sister’s perspective.',comparison:'Both control knowledge deliberately, but one builds irony while the other builds revelation.'}
];

export const mistakes:Mistake[]=[
{title:'Two separate mini-essays',why:'Discussing Work A fully and then Work B fully severely limits genuine comparative analysis.',fix:'Structure each paragraph around one shared idea and include both works within it.',example:'Do not make Paragraph 1 all Work A and Paragraph 2 all Work B; compare inside every main paragraph.'},
{title:'Plot comparison instead of technique comparison',why:'Retelling what happens, even side by side, is not analysis.',fix:'Filter plot through “what does this choice mean or do?”',example:'Move beyond “both parents leave” to what those moments reveal and how each writer constructs them.'},
{title:'Theme-only comparison',why:'A shared theme without method stays surface-level.',fix:'Pair every thematic claim with the specific choice that builds it.',example:'Not just “both show loss,” but how syntax, structure, symbolism, or perspective constructs loss differently.'},
{title:'Weak, vague thesis',why:'The essay has nothing specific to prove.',fix:'Name the conceptual relationship between the works and the mechanism that creates it.',example:'Replace “similar and different” with a claim about what differs and why that difference matters.'},
{title:'No authorial choices',why:'The essay becomes a book report about what the works are about.',fix:'Name concrete techniques in each paragraph.',example:'Use structure, symbolism, narrative perspective, characterization, dialogue, imagery, or form explicitly.'},
{title:'Memorized answer forced onto the question',why:'A pre-written argument drifts toward the question you practiced rather than the one asked.',fix:'Re-plan from the exact wording every time.',example:'Do not bend a generic power essay into a question about authority and resistance without rebuilding the argument.'},
{title:'Too much context',why:'Background that is not connected to analysis wastes time and focus.',fix:'Use context only when it directly explains a choice or interpretation.',example:'Avoid a biography paragraph that never returns to the text’s construction of meaning.'},
{title:'No evaluation',why:'Stopping at “this shows X” limits the depth of analysis.',fix:'Push toward judgments about significance, effectiveness, ambiguity, or consequences.',example:'Explain which treatment of grief is more emotionally convincing and why.'},
{title:'Unequal discussion of the works',why:'One work dominating the essay weakens the comparative requirement.',fix:'Plan roughly equal space and analytical depth for both.',example:'Check every paragraph before writing to ensure each work gets real attention.'},
{title:'Weak evidence choice',why:'Generic references do not specifically support the point.',fix:'Use the most precise analyzable moment available.',example:'Replace “a scene where the character is upset” with the exact moment and the detail that matters.'},
{title:'Repeating the same comparison',why:'It wastes space and signals weak planning.',fix:'Write a one-sentence argument for each planned paragraph and check that none overlap.',example:'Avoid three paragraphs that all reduce to “family is complicated.”'},
{title:'Choosing works only because they are similar',why:'This often produces shallow similarity claims.',fix:'Look for meaningful differences in method, form, scale, or conclusion.',example:'Two works can both address loss but treat it differently enough to sustain a stronger essay.'},
{title:'Ignoring part of the question',why:'Questions often contain multiple tasks.',fix:'Re-check every clause before finalizing the plan.',example:'If the prompt asks “in what ways, and to what effect,” do not answer only the “ways.”'},
{title:'Losing track of time',why:'An unfinished essay loses marks across multiple criteria.',fix:'Use fixed planning and writing checkpoints that you have practiced.',example:'Do not spend 30 minutes planning and leave yourself too little time to write.'},
{title:'Conclusion only restates the introduction',why:'It adds nothing and misses the chance to synthesize.',fix:'End with why the comparison matters as a whole.',example:'Give a final judgment about what the two works reveal when read together.'}
];

export const practices:PracticeQuestion[]=[
{question:'Compare and contrast how two works you have studied present the corrupting effect of power.',asking:'Whether and how power damages those who hold it in each work.',goodWorks:'A pairing where a character or institution’s authority visibly changes over the work.',argument:'Power corrupts differently depending on whether it is institutional or personal.',thesis:'Both works trace the corrupting effect of power, but one locates that corruption in a collapsing institution while the other locates it within a single conscience.',paragraphs:['How power is first established or gained.','The specific moment or choice marking corruption.','The consequences by the work’s end.'],comparisons:'Institutional vs personal power; gradual vs sudden corruption.',mistake:'Describing who has power without analyzing how corruption is constructed stylistically.'},
{question:'Discuss how two writers use family relationships to explore questions of identity.',asking:'How family shapes or constrains a character’s sense of self.',goodWorks:'Works with strong parent-child or sibling dynamics tied to self-understanding.',argument:'Family can be the source of identity or the obstacle to forming one.',thesis:'Family functions as a stabilizing force in one work and a constraining one in the other, reflecting opposing views of where identity originates.',paragraphs:['The family dynamic as introduced early.','A turning point where identity and family expectation collide.','Resolution or non-resolution of that tension.'],comparisons:'Identity formed through family vs against family.',mistake:'Summarizing family relationships without linking them to identity.'},
{question:'In what ways, and to what effect, do two writers use structure to control a reader’s emotional response?',asking:'How chronology, pacing, framing, or withheld information manages what readers feel and when.',goodWorks:'Works with distinctive structure such as non-linear order, framing, or withheld information.',argument:'Structure can build gradual sympathy or deliberate disorientation.',thesis:'One work’s linear structure builds cumulative sympathy, while the other’s fragmented structure denies the reader that same emotional stability.',paragraphs:['Overall structural shape.','A specific structural device and its emotional effect.','Evaluate which approach suits its subject matter better.'],comparisons:'Gradual vs disrupted emotional pacing.',mistake:'Describing structure without explaining its effect on the reader.'},
{question:'Compare the significance of a central symbol or motif in two works you have studied.',asking:'How a recurring image accumulates or shifts meaning across a work.',goodWorks:'Works with a clearly traceable recurring image, object, or motif.',argument:'The same type of symbol can be built gradually or introduced late for retroactive effect.',thesis:'Both writers rely on a central symbol, but one develops it cumulatively while the other withholds it until a single, transformative appearance.',paragraphs:['First appearance and initial meaning.','How meaning shifts or deepens.','Its function at the climax or ending.'],comparisons:'Gradual accumulation vs delayed revelation.',mistake:'Simply stating “the symbol represents X” without tracing how its meaning develops.'},
{question:'Discuss how two writers explore the tension between appearance and reality.',asking:'The gap between how something or someone seems and what is actually true.',goodWorks:'Works involving deception, performance, secrecy, self-deception, or dramatic irony.',argument:'The gap can be sustained by a character or imposed by circumstance.',thesis:'One work’s central deception is self-constructed, while the other’s is imposed by social circumstance beyond the character’s control.',paragraphs:['Establish the appearance or performance.','The moment reality breaks through.','Consequences of that revelation.'],comparisons:'Chosen vs imposed concealment.',mistake:'Treating appearance vs reality as only literal lying and missing self-deception or social performance.'},
{question:'Compare and contrast how two writers use setting to reflect a character’s internal state.',asking:'How setting operates as a mirror for psychology rather than mere backdrop.',goodWorks:'Works where physical environment shifts alongside character development.',argument:'Setting can mirror or ironically contrast a character’s emotional state.',thesis:'One work’s setting directly mirrors its protagonist’s emotional decline, while the other’s setting ironically contrasts with its characters’ internal turmoil.',paragraphs:['Initial setting and tone.','A moment where setting and emotion align or clash.','How setting shifts, or does not, by the end.'],comparisons:'Mirroring vs ironic contrast.',mistake:'Describing setting without explicitly linking it to psychology.'},
{question:'Discuss how two writers present the silencing — or voicing — of a marginalized character.',asking:'Who gets to speak, who is spoken over, and how that is constructed formally.',goodWorks:'Works with a marginalized character whose voice is restricted, filtered, or asserted.',argument:'Narrative perspective itself can enact silencing or empowerment.',thesis:'One work formally silences its marginalized character by denying narrative perspective, while the other grants direct voice, structurally asserting agency.',paragraphs:['Initial positioning of the character.','A moment of silencing or voicing.','Effect on the reader’s sympathy or understanding.'],comparisons:'Structural silencing vs structural empowerment.',mistake:'Discussing silence thematically without analyzing the narrative techniques that construct it.'},
{question:'Compare how two writers use an unreliable or limited narrative perspective.',asking:'How filtered narration shapes what readers can know or trust.',goodWorks:'Works with first-person or tightly focalized narration where knowledge is deliberately restricted.',argument:'Unreliability can arise from self-deception or deliberate manipulation.',thesis:'One narrator’s unreliability stems from genuine self-deception, while the other’s is a calculated manipulation of the reader’s trust.',paragraphs:['Establish the perspective and its limits.','A moment where unreliability becomes visible.','Effect of that revelation on interpretation.'],comparisons:'Unintentional vs deliberate unreliability.',mistake:'Calling a narrator unreliable without specific textual evidence.'},
{question:'Discuss how two writers explore the theme of transformation or change.',asking:'How and why characters change, or fail to, across a work.',goodWorks:'Works with a clear character arc or a clear refusal of one.',argument:'Transformation can be earned and gradual, or sudden and unstable.',thesis:'One work depicts transformation as a hard-won, gradual process, while the other suggests its character’s apparent change is fragile or reversible.',paragraphs:['Starting state.','Catalyst or process of change.','How permanent or genuine the change appears by the end.'],comparisons:'Durable vs fragile transformation.',mistake:'Summarizing that a character changes without analyzing how the change is constructed.'},
{question:'Compare and contrast how two writers use dialogue to reveal power dynamics between characters.',asking:'How speech patterns and exchanges expose who holds power.',goodWorks:'Dialogue-heavy works with characters of unequal status.',argument:'Shifts in address, interruption, or formality can track a changing power balance.',thesis:'One work uses shifting formality of address to track a gradual power reversal, while the other uses interruption and withheld response to establish imbalance from the outset.',paragraphs:['An early dialogue establishing power.','A dialogue marking a shift.','A late dialogue confirming the new balance.'],comparisons:'Gradual reversal vs established or static imbalance.',mistake:'Quoting dialogue without analyzing register, interruption, pronouns, or other linguistic features.'},
{question:'Discuss how two writers use memory or the past to shape a character’s present.',asking:'How recollection, nostalgia, or trauma informs present behavior or identity.',goodWorks:'Works with flashback, retrospective narration, or characters visibly shaped by past events.',argument:'Memory can be a source of stability or ongoing disruption.',thesis:'One work presents memory as something that grounds its protagonist, while the other presents it as an intrusive force the protagonist cannot escape.',paragraphs:['How the past is introduced or accessed.','A specific memory and its effect on present action.','Whether the character resolves or remains trapped by the past.'],comparisons:'Memory as grounding vs memory as intrusion.',mistake:'Retelling backstory without analyzing the technique used to deliver it.'},
{question:'Compare how two writers construct a central conflict between the individual and the community.',asking:'How a character’s needs or values clash with collective expectation.',goodWorks:'Works featuring a protagonist at odds with family, town, or institution.',argument:'The conflict can end in assimilation, exile, or uneasy compromise.',thesis:'One work resolves the individual-community conflict through reluctant compromise, while the other ends in the character’s total exile from the community.',paragraphs:['Individual values vs community values.','A key confrontation.','Resolution or lack of resolution.'],comparisons:'Compromise vs exile.',mistake:'Treating the community as vague backdrop rather than analyzing the figures or scenes that represent it.'},
{question:'Discuss how two writers use humor or irony in works that address serious subject matter.',asking:'The function of comic or ironic distance within otherwise serious texts.',goodWorks:'Works that blend serious themes with irony, dark humor, or satire.',argument:'Humor can either soften or sharpen a serious critique.',thesis:'One work’s irony creates critical distance that sharpens its social critique, while the other’s dark humor builds intimacy with a character’s suffering.',paragraphs:['An early ironic or humorous moment.','How that tone interacts with serious subject matter.','Evaluate the technique’s overall effect.'],comparisons:'Distancing irony vs intimacy-building humor.',mistake:'Noting irony without explaining what it achieves.'},
{question:'Compare and contrast the role of a secondary or minor character in shaping the meaning of two works.',asking:'How a non-protagonist contributes disproportionately to meaning.',goodWorks:'Works with a memorable secondary character who catalyzes change or embodies a theme.',argument:'Minor characters can function as foils, catalysts, or thematic mirrors.',thesis:'One work’s secondary character functions as a foil that exposes the protagonist’s flaws, while the other’s functions as a catalyst that directly drives the central conflict.',paragraphs:['Introduce the secondary character and relationship to the protagonist.','A key moment where they influence events or meaning.','Evaluate their thematic or structural function.'],comparisons:'Foil vs catalyst function.',mistake:'Describing actions without analyzing why the writer included the character structurally.'},
{question:'Discuss how two writers use an ending to shape the overall meaning of their work.',asking:'How the final scene or lines retroactively frame everything before them.',goodWorks:'Works with distinctive endings that resolve, complicate, or deliberately withhold resolution.',argument:'Endings can resolve, complicate, or refuse closure.',thesis:'One work’s resolved ending affirms the possibility of change, while the other’s open ending insists that some conflicts cannot be neatly resolved.',paragraphs:['What the ending resolves or leaves open.','The technique used to create that effect.','How the ending reframes an earlier moment.'],comparisons:'Closure vs deliberate irresolution.',mistake:'Describing what happens at the end without analyzing how the ending is constructed.'}
];

export const miniExercises=[
'Two works both featuring a death — compare how each handles the death structurally: on-page vs off-page; foreshadowed vs sudden.',
'Two works with a journey or departure — compare whether the journey is physical, emotional, or both.',
'Two works with a letter, message, or document — compare whether it functions as revelation or concealment.',
'Two works featuring silence as a character trait — compare what the silence communicates in each.',
'Two works with a mentor or authority figure — compare whether that figure is trustworthy or ultimately undermined.',
'Two works with a significant time jump — compare whether it elides trauma or simply controls pacing.',
'Two works using weather or natural imagery — compare whether nature mirrors or contrasts human emotion.',
'Two works with an unresolved central question — compare how each signals that the irresolution is deliberate.',
'Two works with a character returning to a childhood place — compare what the return reveals about change vs stasis.',
'Two works with a betrayal — compare whether the betrayal is revealed gradually or all at once, and to what effect.'
];
