export type Paper1Choice={term:string;definition:string;effect:string;meaning:string;bad:string};
export type Paper1Question={prompt:string;options:string[];correct:number;why:string};
export type Paper1Practice={title:string;type:string;text:string;visual?:string;theme:string;notice:string;choices:string;effects:string;interpretation:string;evaluation:string;thesis:string;paragraph:string;questions:Paper1Question[]};

export const approachSteps=[
  ['Read','Read the whole text once before annotating. Use the guiding question to know what to keep an eye on.','Get the shape of the text first; do not begin writing after reading only half.'],
  ['Understand the situation','Identify the text type, source clues and what is happening around the text.','Use headlines, bylines, captions, layout and framing information. Do not invent a backstory.'],
  ['Audience','Work out who the text is designed to reach, using language, assumed knowledge and direct address as evidence.','Avoid vague labels such as “everyone” or “readers.”'],
  ['Purpose','Ask what the text is trying to make the audience think, feel or do.','Narrow “to persuade” into what the audience is being persuaded to believe or do.'],
  ['Tone','Identify the writer’s attitude toward the subject and audience.','Track shifts. Strong texts often move between tones rather than staying emotionally flat.'],
  ['Patterns','Look for repeated words, structures, images, colors, contrasts and section lengths.','Prioritize the patterns that connect most clearly to purpose, audience or the central idea.'],
  ['Authorial choices','Name the language, structural, narrative or visual choices doing the most work.','Do not stop at naming a technique; the choice is the beginning of the analysis.'],
  ['Interpretation','Ask what larger idea or argument is being built beneath the surface topic.','Every interpretive claim should be traceable to specific evidence.'],
  ['Main argument','Decide what you will argue about how the text creates meaning.','A topic is not an argument. Your claim should be broad enough for several paragraphs but specific enough to guide them.'],
  ['Thesis','Turn the main argument into a precise thesis with relevant choices, central idea and analytical direction.','Avoid a technique list or a summary disguised as a thesis.'],
  ['Plan','Group the best annotations into distinct paragraph arguments with evidence.','If two paragraph plans sound almost identical, merge or replace one.'],
  ['Write','Follow the plan and keep pushing from observation to effect, meaning and evaluation.','Use short, precise references and keep an eye on time checkpoints.']
] as const;

export const toneBank=[
  ['Reflective','Thoughtful and carefully considering something, often looking back','A writer reconsidering a past decision or event'],
  ['Skeptical','Doubtful and questioning claims rather than accepting them','A writer examining a company’s promotional claims'],
  ['Nostalgic','Fondly longing for the past','A piece about a childhood home or a “simpler time”'],
  ['Accusatory','Directly blaming someone or something','A text naming a party responsible for a problem'],
  ['Urgent','Conveying that immediate action is needed','A climate warning or health emergency announcement'],
  ['Restrained','Deliberately holding back emotion despite a heavy subject','A formal statement responding to tragedy'],
  ['Celebratory','Joyful and marking an achievement or occasion','An article about a sports team’s victory'],
  ['Ironic','Creating a gap between surface wording and implied meaning','A text mocking a policy by apparently “praising” it'],
  ['Confrontational','Directly challenging the audience or a target','An open letter directly addressing a politician'],
  ['Critical','Pointing out flaws or problems in an evaluative way','A review or opinion column on a failed policy'],
  ['Persuasive','Aiming to convince the audience to believe or do something','An advertisement or campaign speech'],
  ['Satirical','Using humor, exaggeration or irony to criticize','A cartoon mocking a public figure’s behavior'],
  ['Detached','Emotionally distant and observing without personal investment','A clinical or strongly factual report'],
  ['Intimate','Personal and close, as if speaking to one person directly','A letter or first-person confessional piece'],
  ['Authoritative','Confident, expert and commanding trust','A doctor’s public-health guidance'],
  ['Hopeful','Optimistic about a future possibility','A speech about recovery after a crisis'],
  ['Pessimistic','Expecting an unfavorable outcome','A warning about an unaddressed problem'],
  ['Earnest','Sincere and serious without irony','A heartfelt appeal for donations'],
  ['Condescending','Talking down to the audience as if they know less','A text over-explaining basic concepts to adults'],
  ['Wistful','Gently sad and tinged with longing','A memory of something lost or changed']
] as const;

export const choiceGroups:Record<string,Paper1Choice[]>={
  Language:[
    {term:'Diction',definition:'Word choice.',effect:'Sets register and formality; shapes precision or vagueness.',meaning:'Can reveal attitude, social position or intended audience.',bad:'“The diction makes the text interesting.”'},
    {term:'Imagery',definition:'Language appealing to the senses.',effect:'Makes an abstract idea feel vivid or concrete.',meaning:'Can evoke emotion or reinforce a theme through sensory detail.',bad:'“The imagery paints a picture in the reader’s mind.”'},
    {term:'Metaphor',definition:'A direct comparison without “like” or “as.”',effect:'Compresses a complex idea into a familiar image.',meaning:'Reveals how the writer wants the subject understood.',bad:'“The metaphor makes it more descriptive.”'},
    {term:'Simile',definition:'A comparison using “like” or “as.”',effect:'Clarifies or intensifies a quality by comparison.',meaning:'Frames the subject through an external lens.',bad:'“The simile helps the reader visualize it.”'},
    {term:'Symbolism',definition:'An object or image carrying a larger idea.',effect:'Adds layered meaning beyond the literal.',meaning:'Connects a concrete detail to an abstract theme.',bad:'“The symbolism adds depth to the text.”'},
    {term:'Repetition',definition:'Deliberate reuse of a word, phrase or structure.',effect:'Builds emphasis, rhythm or urgency.',meaning:'Signals what the writer wants the audience to keep noticing.',bad:'“The repetition emphasizes the point.”'},
    {term:'Connotation',definition:'The implied or associative meaning of a word beyond its dictionary definition.',effect:'Colors the audience’s emotional response.',meaning:'Can reveal the writer’s underlying stance.',bad:'“The connotations make the word more powerful.”'},
    {term:'Semantic field',definition:'A cluster of related words around one idea.',effect:'Reinforces a single impression cumulatively.',meaning:'Signals a dominant idea, mood or preoccupation.',bad:'“The semantic field of war is used.”'},
    {term:'Rhetorical question',definition:'A question used for effect rather than to request an answer.',effect:'Involves the audience and can imply an expected answer.',meaning:'Guides the audience toward a conclusion without stating it directly.',bad:'“The rhetorical question makes the reader think.”'},
    {term:'Inclusive language',definition:'Language such as “we,” “us” and “our” that groups creator and audience.',effect:'Builds solidarity or shared responsibility.',meaning:'Positions the audience as already involved in the issue.',bad:'“Inclusive language engages the reader.”'},
    {term:'Pronoun choice',definition:'Selection of “I,” “you,” “we,” “they,” and related forms.',effect:'Shapes distance, closeness, blame and responsibility.',meaning:'Can include, exclude, accuse or unite.',bad:'“The pronouns make it more personal.”'},
    {term:'Imperatives',definition:'Commands such as “Act now” or “Consider this.”',effect:'Creates urgency and can position the writer as authoritative.',meaning:'Implies the audience must respond rather than only reflect.',bad:'“The imperative tells the reader what to do.”'},
    {term:'Modality',definition:'The degree of certainty expressed through words such as “must,” “might” and “could.”',effect:'High modality asserts confidence; low modality can signal caution or nuance.',meaning:'Reveals how certain the writer wants to appear about a claim.',bad:'“The modal verbs change the meaning.”'},
    {term:'Euphemism',definition:'A milder expression substituted for a harsher one.',effect:'Softens, minimizes or obscures a difficult reality.',meaning:'Can suggest tact, evasion or an attempt to manage reaction.',bad:'“The euphemism makes it sound nicer.”'},
    {term:'Irony',definition:'A gap between what is said or expected and what is meant or happens.',effect:'Can create humor, criticism or unease.',meaning:'May undermine a claim, expose hypocrisy or invite skepticism.',bad:'“The irony makes the text more interesting.”'},
    {term:'Hyperbole',definition:'Deliberate exaggeration.',effect:'Heightens emotion or emphasizes a point dramatically.',meaning:'Can signal strong feeling or invite doubt about objectivity.',bad:'“The hyperbole exaggerates the point.”'}
  ],
  Structure:[
    {term:'Juxtaposition',definition:'Two contrasting elements placed side by side.',effect:'Emphasizes their difference.',meaning:'Can suggest tension, hypocrisy or unresolved conflict.',bad:'“It uses juxtaposition to interest the reader.”'},
    {term:'Contrast',definition:'A broader pattern of difference across a text, not necessarily adjacent.',effect:'Highlights a shift or opposition over the whole piece.',meaning:'Can suggest change, conflict or duality.',bad:'“The contrast makes the text more effective.”'},
    {term:'Shifts',definition:'A change in tone, focus, tense or perspective partway through.',effect:'Signals a turning point in the argument or mood.',meaning:'Can mark development, reversal or complication of an idea.',bad:'“There is a shift in the text.”'},
    {term:'Beginnings / endings',definition:'The opening and closing lines or sections.',effect:'Frame how the audience enters and leaves the text.',meaning:'Can make first and final impressions carry special weight.',bad:'“The ending concludes the text.”'},
    {term:'Sentence length',definition:'The deliberate use of shorter or longer sentences.',effect:'Short sentences can create pace, tension or impact; longer ones can create flow, complexity or accumulation.',meaning:'May mirror an emotional or intellectual state.',bad:'“The short sentences make it more dramatic.”'},
    {term:'Paragraph length',definition:'How information is grouped and paced across paragraphs.',effect:'Short paragraphs can isolate ideas; long ones can build sustained argument.',meaning:'Shapes whether ideas are received quickly or cumulatively.',bad:'“The paragraphs are structured well.”'},
    {term:'Syntax',definition:'Sentence construction and word order.',effect:'Unusual order can foreground a word, create emphasis or slow reading.',meaning:'Draws attention to what the writer considers important.',bad:'“The syntax is complex.”'},
    {term:'Pacing',definition:'The speed at which information or events are revealed.',effect:'Fast pacing can create urgency; slow pacing can build tension or reflection.',meaning:'Controls how the audience experiences time within the text.',bad:'“The pacing is fast.”'},
    {term:'Chronology',definition:'The order in which events or ideas are presented.',effect:'Non-linear order can create suspense, highlight cause and effect, or mirror memory.',meaning:'Shapes how a sequence of events is understood.',bad:'“The chronology tells a story.”'},
    {term:'Fragmentation',definition:'Deliberately incomplete or broken sentences or structures.',effect:'Can mimic disrupted thought, urgency or shock.',meaning:'May suggest breakdown, distraction or emotional overwhelm.',bad:'“The fragments are used for effect.”'},
    {term:'Cyclical structure',definition:'The text returns to an opening idea or image at the end.',effect:'Creates closure or a sense of inescapability.',meaning:'Can suggest something unresolved, repeating or inevitable.',bad:'“The cyclical structure ties the text together.”'}
  ],
  Narrative:[
    {term:'Perspective',definition:'The vantage point from which events are told.',effect:'Shapes what the audience can and cannot know.',meaning:'Controls sympathy, bias and interpretation.',bad:'“The perspective makes it more interesting.”'},
    {term:'Narrator',definition:'The voice telling the story.',effect:'Shapes tone, reliability and distance from events.',meaning:'Filters events through a particular consciousness or agenda.',bad:'“The narrator tells the story.”'},
    {term:'Focalization',definition:'Whose thoughts or perceptions the narrative filters through, even if it is not first person.',effect:'Restricts knowledge to a particular awareness.',meaning:'Can build intimacy with or scrutiny of a character.',bad:'“The focalization is on the character.”'},
    {term:'Characterization',definition:'How a person is constructed through action, dialogue and description.',effect:'Builds sympathy, judgment or complexity around a figure.',meaning:'Can use an individual to represent a broader idea or social type.',bad:'“The characterization makes the character realistic.”'},
    {term:'Dialogue',definition:'Represented speech between figures.',effect:'Reveals relationships, conflict and power dynamics through interaction.',meaning:'Can show character or tension rather than explaining it directly.',bad:'“The dialogue moves the story forward.”'},
    {term:'Voice',definition:'The distinctive way a narrator or figure sounds.',effect:'Creates intimacy, authenticity or distance.',meaning:'Can reflect identity, attitude or social position.',bad:'“The voice is engaging.”'},
    {term:'Reliability',definition:'The degree to which a narrator’s account can be trusted.',effect:'Creates suspicion, dramatic irony or the need for inference.',meaning:'Invites the audience to read between the lines.',bad:'“The narrator is unreliable, which is interesting.”'}
  ],
  Visual:[
    {term:'Layout',definition:'The arrangement of text and visual elements on the page.',effect:'Guides the eye and establishes hierarchy.',meaning:'Signals what the producer wants noticed first.',bad:'“The layout is well organized.”'},
    {term:'Framing',definition:'What is included or excluded within an image’s borders.',effect:'Focuses attention and can isolate or contextualize a subject.',meaning:'Shapes how the viewer interprets the subject’s situation.',bad:'“The framing focuses on the subject.”'},
    {term:'Composition',definition:'The overall visual arrangement of elements within an image.',effect:'Can create balance, imbalance, tension or harmony.',meaning:'Directs the emotional response to the image as a whole.',bad:'“The composition looks good.”'},
    {term:'Typography',definition:'Font choice, size, weight and style.',effect:'Can signal tone, urgency or hierarchy of information.',meaning:'Reflects the intended register of the message.',bad:'“The typography is bold.”'},
    {term:'Color',definition:'Use of specific colors or color schemes.',effect:'Can evoke mood or associations such as warmth, danger or calm.',meaning:'May carry cultural or symbolic meaning.',bad:'“The colors make it stand out.”'},
    {term:'Gaze',definition:'The direction a person in an image is looking and where the viewer’s eye is drawn.',effect:'Creates connection or distance and directs attention.',meaning:'Can position the viewer as included, implicated or excluded.',bad:'“The gaze is interesting.”'},
    {term:'Salience',definition:'What is made most visually prominent through size, color, position or contrast.',effect:'Establishes a clear focal point.',meaning:'Reveals the producer’s priorities.',bad:'“It is salient because it stands out.”'},
    {term:'Image placement',definition:'Where an image sits relative to words and other images.',effect:'Creates relationships of emphasis or sequence.',meaning:'Guides interpretation of accompanying text.',bad:'“The image is placed well.”'},
    {term:'Visual hierarchy',definition:'The order in which elements draw the eye.',effect:'Controls the sequence in which the viewer processes information.',meaning:'Reflects what the producer treats as most and least important.',bad:'“There is a visual hierarchy.”'},
    {term:'Image / text relationship',definition:'How an image supports, contradicts or extends nearby words.',effect:'Can reinforce, complicate or undercut the verbal message.',meaning:'Adds meaning that neither mode could create alone.',bad:'“The image matches the text.”'}
  ]
};

export const analysisExamples=[
  {label:'Dark room',steps:['Observation — “The room is dark.”','Choice — Minimal, monosyllabic diction creates a stark break from more elaborate sentences.','Effect — The flatness slows the audience and creates emotional emptiness.','Meaning — The physical setting begins to mirror emotional numbness.','Evaluation — The abruptness is effective because the audience experiences the emptiness instead of simply being told about it.','Wider idea — Isolation and emotional withdrawal.']},
  {label:'Family advertisement',steps:['Observation — The advertisement uses a smiling family.','Choice — A centered visual of a smiling multigenerational family surrounds the product.','Effect — The product becomes associated with warmth and belonging rather than only function.','Meaning — The company is selling an emotional experience of connection.','Evaluation — The strategy is persuasive because it reaches the audience through emotional need before rational product evaluation.','Wider idea — Advertising can sell identity and belonging over utility.']},
  {label:'Repeated “we”',steps:['Observation — The speaker repeats “we.”','Choice — Inclusive pronouns repeatedly bind speaker and audience together.','Effect — A sense of collective responsibility and shared stake develops.','Meaning — The audience is positioned as already implicated in both the problem and the solution.','Evaluation — This can be powerful because disagreement begins to feel like separation from the community the speech constructs.','Wider idea — Collective rather than purely individual responsibility.']},
  {label:'Statistics first',steps:['Observation — The article uses several statistics.','Choice — Three statistics are front-loaded before any human perspective appears.','Effect — Credibility and urgency are established before an emotional response develops.','Meaning — The writer wants the claim to appear objectively difficult to dispute before moving into persuasion.','Evaluation — This can work well for a skeptical audience, though it may alienate readers who need an emotional entry point.','Wider idea — Authority is built through evidence before feeling.']},
  {label:'Question ending',steps:['Observation — The text ends with a question.','Choice — A direct rhetorical question replaces a neat resolution.','Effect — The audience is denied comfortable closure.','Meaning — The issue remains mentally active after the text ends.','Evaluation — The ending is effective because it turns the audience from passive recipient into someone who must continue the argument internally.','Wider idea — Provoking ongoing reflection rather than only informing.']}
] as const;

export const evaluationExamples=[
  'This juxtaposition is particularly powerful because it forces two realities the audience might prefer to keep separate into direct contact.',
  'The metaphor is effective not simply because it is vivid, but because it reframes an abstract debate in terms the audience can feel physically.',
  'The writer’s restraint is more convincing than overt emotional appeal would have been because it allows the facts to carry moral weight without appearing manipulative.',
  'This tone shift is subtle but consequential: it quietly repositions the audience from observer to participant without directly ordering them to act.',
  'The repetition risks feeling heavy-handed, but its placement at the structural turning point makes it land as emphasis rather than excess.',
  'The euphemism is a limited choice here: while it softens the subject for a general audience, it also risks minimizing the severity the writer otherwise wants the audience to grasp.',
  'The rhetorical question succeeds because it withholds an explicit answer the audience must supply, making the conclusion feel self-generated rather than imposed.',
  'The structural fragmentation is convincing because it enacts the breakdown the text describes rather than merely telling the audience about it.',
  'The inclusive pronoun is strategically effective because it makes rejecting the argument feel like rejecting the community the speaker has constructed.',
  'The image’s framing is powerful precisely because of what it excludes: cropping out wider context forces attention onto the individual rather than systemic causes.'
] as const;

export const thesisPairs=[
  {weak:'The writer uses many techniques to make the article interesting.',better:'Through escalating statistics and a late shift into first-person testimony, the writer builds an argument that moves the audience from detached awareness to personal urgency.',why:'Specific choices create a clear analytical direction rather than a generic technique list.'},
  {weak:'This speech is about climate change and it is very persuasive.',better:'By repeatedly positioning the audience as both cause and potential solution through inclusive pronouns, the speaker constructs collective responsibility as the speech’s central persuasive strategy.',why:'The revision moves from topic plus vague judgment to a specific mechanism and interpretation.'},
  {weak:'The advertisement uses imagery and color to appeal to the reader.',better:'The advertisement’s warm color palette and domestic imagery work together to sell an idea of belonging rather than the product itself, appealing to emotional need over practical benefit.',why:'The choices are connected to the idea they construct.'},
  {weak:'The author’s tone changes throughout the text.',better:'The shift from a detached, factual tone to an intimate, confessional one mirrors the narrator’s movement from denial to acceptance.',why:'The actual shift is named and connected to meaning.'},
  {weak:'This cartoon criticizes politicians using satire.',better:'Through exaggerated visual caricature and an ironic caption that contradicts the image, the cartoonist exposes the gap between political rhetoric and political action.',why:'The revision identifies the mechanism of the satire and the critique it constructs.'}
] as const;

export const paragraphPairs=[
  {weak:'The writer uses imagery in the text. For example, she describes the sky as “bruised.” This is a good technique because it makes the writing more descriptive and interesting.',better:'The writer’s description of the sky as “bruised” extends beyond simple visual imagery into implied violence, framing the natural world itself as something harmed. This connects to the text’s broader concern with damage — environmental and emotional — suggesting that injury has seeped into the setting itself. The choice is especially effective because it implies large-scale harm without stating it outright, trusting the audience to make the connection.',why:'It analyzes the kind of imagery, connects it to the larger idea and explains why the indirectness is effective.'},
  {weak:'The speaker uses a rhetorical question at the end. This makes the audience think about the topic. It is effective because rhetorical questions are persuasive.',better:'The speech’s closing rhetorical question, left deliberately unanswered, denies the audience the comfort of a resolved argument. Rather than telling the audience what to conclude, the speaker makes them complete the argument themselves, which can make the final position feel self-generated rather than imposed.',why:'It explains the specific effect in this text instead of assuming a device is automatically persuasive.'},
  {weak:'The article has short paragraphs which makes it easy to read. This is effective because it keeps the reader’s attention.',better:'The article’s unusually short paragraphs — some only a single sentence — create a clipped, urgent rhythm that mirrors the breaking-news register of the subject matter. Rather than simply aiding readability, the structure enacts the sense of unfolding crisis so that form and content reinforce one another.',why:'It replaces a generic readability claim with an argument about pace, form, content and purpose.'}
] as const;

export const commonMistakes=[
  ['Summary instead of analysis','Describing content does not explain how meaning is constructed.','Ask after every point: am I explaining what happens, or how the text makes it mean something?','“The article talks about pollution getting worse.”','“The escalating statistics make the scale of pollution feel inescapable before the writer states an opinion.”'],
  ['Technique spotting','Naming a device without explaining its function adds little analysis.','Follow the choice with effect, meaning and where useful evaluation.','“The writer uses a metaphor.”','“The ‘sinking ship’ metaphor turns an abstract financial problem into immediate physical danger.”'],
  ['Vague effects','“Interesting,” “powerful” and “effective” do not specify what changed.','Describe the exact change in the audience’s understanding, feeling or position.','“This makes the text more effective.”','“This makes the danger feel immediate rather than distant, moving the audience from abstract concern to personal urgency.”'],
  ['Ignoring audience and purpose','Analysis floats without explaining who the choice is designed to affect and what it serves.','Return to audience and purpose when they genuinely explain why the choice works.','“The writer uses statistics to inform.”','“The dense statistical opening establishes credibility for an audience already engaged with policy before the emotional appeal arrives.”'],
  ['Unsupported interpretation','A deeper claim without textual support becomes speculation.','Put specific evidence underneath every interpretive leap.','“This text is really about the writer’s childhood trauma.”','Ground the interpretation in choices the text actually provides.'],
  ['Huge sweeping claims','One short text rarely supports a universal statement about humanity, society or all texts of a type.','Scale the claim to what this text actually demonstrates.','“This proves all advertising is manipulative.”','“This advertisement relies on aspiration more than practical product information.”'],
  ['Weak thesis','A topic sentence gives the response no argument to develop.','Use a focused interpretation connected to relevant authorial choices and analytical direction.','“This text uses techniques to persuade.”','“Through a shift from statistical distance to personal testimony, the writer turns awareness into urgency.”'],
  ['No evaluation','Stopping at effect can leave analysis underdeveloped.','Ask what makes the choice effective, limited, subtle, risky or especially suitable here.','“This creates urgency.”','“The urgency is especially effective after the reflective opening because the change in pace jolts the audience.”'],
  ['Forcing terminology','Incorrect terminology damages precision and can distract from sound reasoning.','Use simpler accurate language when a technical label is uncertain.','Calling any contrast “juxtaposition.”','Name juxtaposition only when the placement of contrasting elements is actually doing analytical work.'],
  ['Fancy vocabulary, weak reasoning','Sophisticated words cannot replace clear logic.','Prioritize precision and explanation over sounding impressive.','“The masterful deployment of linguistic virtuosity engenders resonance.”','“The short blunt sentences slow the audience down and force attention onto an uncomfortable idea.”'],
  ['Repeating paragraph ideas','Repeated sub-arguments waste time and stop the essay from developing.','Write each paragraph claim in one sentence before drafting and check for overlap.','Two paragraphs both argue only that the audience feels worried.','Give each paragraph a distinct function that builds on the previous one.'],
  ['Bad evidence choice','A quotation that does not demonstrate the claim cannot carry the analysis.','Use the shortest precise phrase that actually does the work.','Quoting an entire sentence for one word’s connotation.','Quote the key word or short phrase and unpack it closely.'],
  ['Losing focus on the guiding question','A response can become unfocused if it starts with one focus and then drifts away.','Use the guiding question as your focus, or establish a clear alternative technical/formal focus from the start.','Mentioning the guiding question only in the introduction.','Build the chosen focus into the line of argument throughout.'],
  ['Losing track of time','Over-annotating can leave too little time for a developed response.','Use practice-based checkpoints and move on even when a stage does not feel perfect.','Spending 30 minutes annotating and leaving 20 minutes to write.','Use a planned allocation and protect writing time.'],
  ['Conclusion only repeats the introduction','Word-for-word repetition adds no synthesis.','Briefly show what the argument reveals when the points are considered together.','“In conclusion, the writer uses techniques to persuade.”','“Ultimately, moving the audience from statistical distance to emotional proximity makes the argument felt as well as understood.”']
] as const;

export const paper1Practices:Paper1Practice[]=[
  {
    title:'The Last Green Corner',type:'Opinion column',
    text:'We are told, again, that this is progress. That the small park at the end of Miller Street — the one with the crooked oak and the bench nobody ever fixed — must make way for what the council calls “essential development.” I have watched three generations of this neighborhood pass through that gate. I have watched it shrink, year after year, quietly, the way most things disappear: not all at once, but piece by piece, until one day you look up and there is nothing left to lose. We do not need another announcement telling us this is necessary. We need someone, anywhere in this process, to ask what it is we are actually trading away.',
    theme:'The slow erosion of shared community spaces in the name of “progress,” and the absence of accountability in that process.',
    notice:'Specific personal details (“crooked oak,” “bench nobody ever fixed”); the shift from personal history to collective “we”; “piece by piece”; the final unanswered question.',
    choices:'Nostalgic imagery; inclusive pronouns; a pattern of gradual diminishment; a closing rhetorical question; ironic use of institutional language such as “essential development” and “progress.”',
    effects:'Builds emotional investment before the argument becomes abstract; makes loss feel cumulative; positions the audience to question official framing.',
    interpretation:'The piece is less about one park than about institutional language making repeated community loss feel inevitable and unquestionable.',
    evaluation:'Grounding an abstract critique in small sensory details is effective because it makes a familiar development-versus-community argument feel personal rather than generic.',
    thesis:'Through specific nostalgic imagery, patterns of gradual diminishment and a closing rhetorical question, the writer exposes how institutional language such as “progress” can make community loss feel inevitable rather than accountable.',
    paragraph:'Claim: the pattern of gradual loss reframes the park closure as part of a longer erosion. Evidence: “shrink, year after year, quietly… piece by piece.” Choice: structural repetition of diminishment. Effect: loss feels cumulative. Meaning: the closure becomes one part of an ongoing pattern. Evaluation: this is effective because a local decision is made to represent a larger process. Connection: the language of “progress” conceals accumulated loss.',
    questions:[
      {prompt:'What is the most likely effect of the phrase “piece by piece”?',options:['It shows confusion about the timeline.','It reinforces the pattern of gradual, barely noticed loss.','It suggests the park was destroyed all at once.','It is only descriptive and has no link to the argument.'],correct:1,why:'It continues the pattern created by “shrink” and “quietly,” strengthening the central idea of gradual erosion.'},
      {prompt:'The repeated “we” in the final sentences primarily functions to…',options:['confuse who is speaking.','distance the writer from the community.','position the audience as a shared stakeholder in the loss.','formally address the local council.'],correct:2,why:'Inclusive pronouns bind writer and audience into a shared position, making the loss a collective issue rather than somebody else’s problem.'},
      {prompt:'How are “progress” and “essential development” being used?',options:['As genuine praise for the council.','As neutral factual language.','Ironically, to question how institutional language frames loss.','Only as quotations for factual accuracy.'],correct:2,why:'The surrounding nostalgic and critical tone undercuts the official wording, making the labels part of the critique.'},
      {prompt:'What is the effect of ending on a question?',options:['It shows the writer has run out of argument.','It denies comfortable resolution and keeps the issue active.','It directly answers the main concern.','It has no particular effect.'],correct:1,why:'The unanswered question refuses neat closure and transfers some responsibility for reflection to the audience.'},
      {prompt:'Why include the “crooked oak” and “bench nobody ever fixed”?',options:['Only to provide factual description.','To establish personal and emotional investment before the abstract argument.','To distract from the argument.','To demonstrate horticultural expertise.'],correct:1,why:'Specific, imperfect details make the place feel lived-in and personally meaningful, giving the later critique emotional grounding.'}
    ]
  },
  {
    title:'SwiftBrew',type:'Advertisement',
    text:'Mornings shouldn’t be a fight. SwiftBrew — ready in 90 seconds, so you can stop rushing and start your day the way you meant to. Because the best version of you doesn’t need to skip breakfast.',
    visual:'Warm-toned photo of a single steaming mug on a sunlit windowsill, generous uncluttered white space, and the product name in a clean rounded font at the bottom.',
    theme:'Selling ease and self-improvement rather than only a beverage machine: the product becomes a small act of self-care within a rushed life.',
    notice:'Second-person “you”; contrast between “a fight” and an intentional morning; minimalist warm composition; the precise “90 seconds” claim.',
    choices:'Direct address; juxtaposition of rushed and calm mornings; warm color and white space; a punchy opening fragment; aspirational “best version of you” language.',
    effects:'Creates immediate identification with a common frustration; visual calm reinforces verbal ease; the product becomes symbolic of intentional living.',
    interpretation:'The advertisement is less about coffee-making speed than about selling control and self-worth in a culture of rushed mornings.',
    evaluation:'The strategy is persuasive because it reframes a minor purchase as an act of self-respect, raising its emotional stakes.',
    thesis:'Through second-person address, warm minimalist visual composition and the language of self-improvement, the advertisement sells emotional control over a rushed life rather than only practical function.',
    paragraph:'Claim: the advertisement reframes a mundane appliance as self-care. Evidence: “the best version of you doesn’t need to skip breakfast.” Choice: aspirational language connecting the product to self-worth. Effect: the purchase becomes identity-affirming. Meaning: convenience is framed as self-respect. Evaluation: the reframing turns a low-stakes decision into an emotionally significant one.',
    questions:[
      {prompt:'The fragment “Mornings shouldn’t be a fight” primarily…',options:['provides a factual claim about all mornings.','creates an immediate relatable hook through abrupt conversational structure.','confuses the audience about the product.','establishes a formal academic register.'],correct:1,why:'Its brevity resembles spoken frustration and immediately gives the audience a problem they may recognize.'},
      {prompt:'What is the likely purpose of the warm tone and generous white space?',options:['To reduce printing costs.','To visually reinforce the calm uncluttered life promised by the words.','To hide the product price.','It has no relationship with the wording.'],correct:1,why:'The visual calm and verbal promise of ease support the same aspirational message.'},
      {prompt:'“The best version of you” is best understood as…',options:['a neutral technical description.','aspirational language linking the product to self-worth and identity.','an imperative command.','specialist vocabulary.'],correct:1,why:'The phrase connects consumption with identity and personal improvement rather than with the appliance’s technical function.'},
      {prompt:'The contrast between “a fight” and the intended morning is…',options:['juxtaposition establishing opposing versions of the same morning.','an accidental contradiction.','a literal physical fight.','a neutral transition between unrelated ideas.'],correct:0,why:'The product is positioned as the bridge between a rushed reality and an idealized alternative.'},
      {prompt:'Who is the most likely target audience?',options:['Coffee-industry professionals seeking specifications.','Busy people who feel rushed and want more control over their mornings.','Children because the sentences are simple.','People with no interest in self-improvement.'],correct:1,why:'The language of rushing, control and self-improvement targets people who recognize a hectic routine and want an easier one.'}
    ]
  },
  {
    title:'A Seat at This Table',type:'Speech excerpt to a town council',
    text:'Good evening. My name doesn’t matter much here — I’m one of maybe forty students in this town who bothered to write something down. What matters is this: you keep asking us what we want for our future, and then you make the decisions before we’ve finished answering. Tonight I am not asking for permission to care about this town. I am telling you that we already do — and that a seat at this table, not a survey sent home in a backpack, is what respect actually looks like. Give us the seat. We’ll bring the ideas.',
    theme:'The gap between symbolic consultation of young people and genuine inclusion in decision-making; a demand for structural rather than token respect.',
    notice:'The modest opening; direct “you” address; survey-versus-seat contrast; short final commands.',
    choices:'Second-person accountability; juxtaposition between symbolic consultation and real power; imperatives; tonal shift from modest to assertive.',
    effects:'The opening builds credibility before the demand; the concrete image of a “seat at this table” makes representation tangible.',
    interpretation:'Youth involvement is reframed not as a favor adults may grant, but as a form of respect already owed to young residents who are participating.',
    evaluation:'The modest-to-assertive tonal shift is effective because it can lower defensiveness before the speaker delivers a bold demand.',
    thesis:'Through a deliberate shift from modest self-introduction to direct imperative, and a central juxtaposition between symbolic and structural inclusion, the speaker reframes youth participation as an entitlement already earned rather than a favor to be granted.',
    paragraph:'Claim: juxtaposition exposes the gap between symbolic and genuine inclusion. Evidence: “a survey sent home in a backpack” versus “a seat at this table.” Effect: the political complaint becomes concrete. Meaning: current consultation appears performative. Evaluation: the images are immediately visual and easy for the council to judge. Connection: real respect requires structural change, not gesture.',
    questions:[
      {prompt:'Why open with “My name doesn’t matter much here”?',options:['The speaker forgot their name.','To build modest credibility before becoming more assertive.','To insult the council.','It has no connection to the later argument.'],correct:1,why:'The understatement lowers the audience’s guard and gives the later demand a deliberate tonal build.'},
      {prompt:'The survey-versus-seat contrast is best described as…',options:['a random detail.','juxtaposition between symbolic and structural inclusion.','a literal discussion of school furniture.','euphemism.'],correct:1,why:'Two concrete images are opposed to make the difference between being consulted and actually sharing power visible.'},
      {prompt:'What does “Give us the seat” do at the end?',options:['Softens the argument.','Turns the argument into a direct unambiguous demand.','Confuses the purpose.','Has no rhetorical effect.'],correct:1,why:'The imperative converts the earlier explanation into a clear action the audience is being asked to take.'},
      {prompt:'Why shift from modest to assertive?',options:['To confuse the audience.','To reduce defensiveness before the central demand.','To demonstrate poor public speaking.','The shift has no effect.'],correct:1,why:'The controlled progression helps the speaker earn attention before increasing pressure.'},
      {prompt:'Who is directly addressed?',options:['Other students.','The town council members at the meeting.','A general online audience.','The speaker’s family.'],correct:1,why:'The stated setting and repeated second-person “you” make the council the direct addressee.'}
    ]
  },
  {
    title:'What I Learned From Failing the Audition',type:'Personal blog reflection',
    text:'I didn’t get the part. I want to say that first, plainly, because I spent a long time trying to bury it in softer language — “it wasn’t the right fit,” “the timing wasn’t right.” It was simpler than that. I wasn’t good enough that day, for that role, in that room. And here is the strange thing I didn’t expect: once I stopped softening it, I finally had something honest to work with. You cannot improve at something you refuse to name clearly.',
    theme:'The value of honest self-assessment over comforting self-deception, and the idea that avoiding difficult truths can block growth.',
    notice:'Blunt opening; listed euphemisms; movement from softer wording to plain statement; final generalization from “I” to “you.”',
    choices:'Confessional first-person voice; euphemisms named and rejected; short declarative sentences; an aphoristic final statement.',
    effects:'Bluntness establishes trust; rejecting euphemisms makes honesty feel earned; the final “you” invites the audience to apply the insight personally.',
    interpretation:'The words people choose to describe failure can either protect them from growth or create the clarity needed for it.',
    evaluation:'Naming and rejecting the euphemisms is effective because the reader witnesses the shift toward honesty in real time instead of simply being told honesty matters.',
    thesis:'By explicitly naming and rejecting the euphemisms she first used, the writer demonstrates rather than merely argues that honest self-assessment — however uncomfortable — is a condition for genuine growth.',
    paragraph:'Claim: direct blunt language models the honesty being argued for. Evidence: “I wasn’t good enough that day, for that role, in that room.” Choice: declarative plainness replacing euphemism. Effect: the form performs honesty. Meaning: comforting vagueness becomes a barrier to improvement. Evaluation: the linguistic shift enacts the argument and makes it more convincing than an abstract claim would be.',
    questions:[
      {prompt:'Why list the euphemisms before rejecting them?',options:['To show she agrees with them.','To demonstrate the shift toward honest self-assessment.','Because she cannot decide which is true.','They are unrelated to the main idea.'],correct:1,why:'The reader sees the writer move from self-protection to clearer naming rather than only hearing a lesson about honesty.'},
      {prompt:'What does “I didn’t get the part” establish?',options:['A vague comforting summary.','Bluntness and honesty from the first line.','Confusion about the outcome.','A delayed main point.'],correct:1,why:'The short declaration immediately creates the direct register the reflection later defends.'},
      {prompt:'What is the effect of the final “You cannot improve…” sentence?',options:['It narrows the idea to one audition.','It generalizes the personal anecdote into a broader insight.','It contradicts the passage.','It has no clear function.'],correct:1,why:'The move from “I” to “you” turns one experience into a principle the audience is invited to test against their own life.'},
      {prompt:'The tone is best described as…',options:['detached and clinical.','reflective and increasingly direct/confessional.','purely celebratory.','angry and accusatory.'],correct:1,why:'The piece is self-examining and becomes more candid as the writer abandons softer language.'},
      {prompt:'Why did the writer initially use “it wasn’t the right fit”?',options:['She believed it was the only possible truth.','It was a softer way of avoiding a harder judgment about her performance.','Someone instructed her to say it.','The text gives no reason.'],correct:1,why:'The passage explicitly calls such phrases “softer language” used to bury a more uncomfortable conclusion.'}
    ]
  },
  {
    title:'Eastgate Water Advisory',type:'Public notice',
    text:'Residents of the Eastgate district are advised that recent testing has identified elevated mineral content in the local water supply. While levels remain within an acceptable range for most uses, residents in sensitive categories may wish to consult alternative sources as a precaution. The relevant department is actively monitoring the situation and will provide further updates as appropriate. We thank residents for their continued patience.',
    theme:'An official body communicates a potentially concerning issue while managing public reaction through restrained, non-alarming language.',
    notice:'Passive constructions; “sensitive categories”; hedging such as “acceptable range” and “as appropriate”; closing gratitude that assumes patience.',
    choices:'Passive voice; euphemistic wording; hedging modality; formal bureaucratic register; a closing statement that presumes calm compliance.',
    effects:'The register creates an impression of calm control but can obscure responsibility and severity; vague categorization may under-inform people who most need to act.',
    interpretation:'The notice may prioritize managing public perception and minimizing alarm over maximum clarity.',
    evaluation:'The restrained tone is double-edged: it can prevent panic, but the same restraint risks under-serving residents who need specific information.',
    thesis:'Through passive constructions, euphemism and hedging modality, the notice prioritizes calm public perception over full transparency, revealing a tension between reassurance and genuine informativeness.',
    paragraph:'Claim: vague categorization avoids specifying who is at risk. Evidence: “residents in sensitive categories.” Choice: unspecific noun phrase. Effect: reduces alarm but leaves at-risk people uncertain. Meaning: public perception appears to compete with clarity. Evaluation: the choice is limited because avoiding panic may come at the expense of the notice’s informational purpose.',
    questions:[
      {prompt:'“Elevated mineral content” is best understood as…',options:['fully transparent scientific language.','euphemism that softens a potentially concerning issue.','hyperbole exaggerating severity.','direct blunt language.'],correct:1,why:'The phrase presents the issue in controlled, less alarming terms rather than naming a more threatening interpretation.'},
      {prompt:'What is the likely effect of “are advised” rather than “we advise you”?',options:['It makes responsibility more visible.','It obscures who is responsible for the advisory.','It has no effect.','It makes the notice emotionally engaging.'],correct:1,why:'The passive construction removes a clear agent and creates institutional distance.'},
      {prompt:'Why is “residents in sensitive categories” potentially weak?',options:['It is too specific.','It is vague and may fail to tell at-risk people whether the advice applies to them.','It is grammatically incorrect.','It has no link to purpose.'],correct:1,why:'The notice’s purpose is to inform, so unclear categorization can undermine usefulness for the people most affected.'},
      {prompt:'“We thank residents for their continued patience” primarily assumes…',options:['residents are already angry.','a calm compliant response rather than directly acknowledging concern.','residents already have full information.','nothing about audience reaction.'],correct:1,why:'The wording frames the desired response as patient waiting and helps maintain the controlled bureaucratic tone.'},
      {prompt:'The register is best described as…',options:['emotional and urgent.','formal, restrained and bureaucratic.','informal and conversational.','satirical and ironic.'],correct:1,why:'Passive constructions, hedging and impersonal wording consistently create institutional distance.'},
      {prompt:'Which is the strongest evaluation of the restrained tone?',options:['It is entirely successful with no drawbacks.','It prevents panic but risks under-informing residents who need clear guidance.','It is completely ineffective.','Tone has no bearing on effectiveness.'],correct:1,why:'Evaluation weighs both what the choice achieves and what it costs rather than making a one-sided judgment.'}
    ]
  }
];
